/********************************************************************
* graf/src/G__Graf2.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error graf/src/G__Graf2.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Graf2();
extern void G__cpp_setup_inheritanceG__Graf2();
extern void G__cpp_setup_typetableG__Graf2();
extern void G__cpp_setup_memvarG__Graf2();
extern void G__cpp_setup_globalG__Graf2();
extern void G__cpp_setup_memfuncG__Graf2();
extern void G__cpp_setup_funcG__Graf2();
extern void G__set_cpp_environmentG__Graf2();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "graf/inc/TTF.h"
#include "graf/inc/TCurlyLine.h"
#include "graf/inc/TMarker.h"
#include "graf/inc/TGraphSmooth.h"
#include "graf/inc/TGraphErrors.h"
#include "graf/inc/TGraphAsymmErrors.h"
#include "graf/inc/TLink.h"
#include "graf/inc/TText.h"
#include "graf/inc/TCutG.h"
#include "graf/inc/TArrow.h"
#include "graf/inc/TDiamond.h"
#include "graf/inc/TLegendEntry.h"
#include "graf/inc/TLine.h"
#include "graf/inc/TPaveStats.h"
#include "graf/inc/TGraph.h"
#include "graf/inc/TWbox.h"
#include "graf/inc/TCurlyArc.h"
#include "graf/inc/TPaveLabel.h"
#include "graf/inc/TGaxis.h"
#include "graf/inc/TPoints.h"
#include "graf/inc/TBox.h"
#include "graf/inc/TArc.h"
#include "graf/inc/TPavesText.h"
#include "graf/inc/TEllipse.h"
#include "graf/inc/TPaveText.h"
#include "graf/inc/TMultiGraph.h"
#include "graf/inc/TLegend.h"
#include "graf/inc/TPave.h"
#include "graf/inc/TImage.h"
#include "graf/inc/TSpline.h"
#include "graf/inc/TAttImage.h"
#include "graf/inc/TPolyLine.h"
#include "graf/inc/TCrown.h"
#include "graf/inc/TLatex.h"
#include "graf/inc/TFrame.h"
#include "graf/inc/TGraphBentErrors.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Graf2LN_TClass;
extern G__linked_taginfo G__G__Graf2LN_TBuffer;
extern G__linked_taginfo G__G__Graf2LN_TMemberInspector;
extern G__linked_taginfo G__G__Graf2LN_TObject;
extern G__linked_taginfo G__G__Graf2LN_TNamed;
extern G__linked_taginfo G__G__Graf2LN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Graf2LN_TList;
extern G__linked_taginfo G__G__Graf2LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__Graf2LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Graf2LN_TString;
extern G__linked_taginfo G__G__Graf2LN_TVirtualPad;
extern G__linked_taginfo G__G__Graf2LN_FT_BBox;
extern G__linked_taginfo G__G__Graf2LN_FT_Matrix;
extern G__linked_taginfo G__G__Graf2LN_TTGlyph;
extern G__linked_taginfo G__G__Graf2LN_TTF;
extern G__linked_taginfo G__G__Graf2LN_TTFcLcLdA;
extern G__linked_taginfo G__G__Graf2LN_TAttLine;
extern G__linked_taginfo G__G__Graf2LN_TAttFill;
extern G__linked_taginfo G__G__Graf2LN_TAttMarker;
extern G__linked_taginfo G__G__Graf2LN_TF1;
extern G__linked_taginfo G__G__Graf2LN_TArrayD;
extern G__linked_taginfo G__G__Graf2LN_TVectorD;
extern G__linked_taginfo G__G__Graf2LN_TH1F;
extern G__linked_taginfo G__G__Graf2LN_TSpline;
extern G__linked_taginfo G__G__Graf2LN_TGraph;
extern G__linked_taginfo G__G__Graf2LN_TGraphSmooth;
extern G__linked_taginfo G__G__Graf2LN_TAttText;
extern G__linked_taginfo G__G__Graf2LN_TText;
extern G__linked_taginfo G__G__Graf2LN_TTextcLcLdA;
extern G__linked_taginfo G__G__Graf2LN_TLink;
extern G__linked_taginfo G__G__Graf2LN_TLinkcLcLdA;
extern G__linked_taginfo G__G__Graf2LN_TBox;
extern G__linked_taginfo G__G__Graf2LN_TPave;
extern G__linked_taginfo G__G__Graf2LN_TLegendEntry;
extern G__linked_taginfo G__G__Graf2LN_TPoints;
extern G__linked_taginfo G__G__Graf2LN_TLegend;
extern G__linked_taginfo G__G__Graf2LN_TAttImage;
extern G__linked_taginfo G__G__Graf2LN_TPaletteEditor;
extern G__linked_taginfo G__G__Graf2LN_TImagePalette;
extern G__linked_taginfo G__G__Graf2LN_TAttImagecLcLEImageQuality;
extern G__linked_taginfo G__G__Graf2LN_Segment_t;
extern G__linked_taginfo G__G__Graf2LN_TArrayL;
extern G__linked_taginfo G__G__Graf2LN_TPoint;
extern G__linked_taginfo G__G__Graf2LN_TImage;
extern G__linked_taginfo G__G__Graf2LN_TImagecLcLEImageFileTypes;
extern G__linked_taginfo G__G__Graf2LN_TImagecLcLEText3DType;
extern G__linked_taginfo G__G__Graf2LN_TImagecLcLECharType;
extern G__linked_taginfo G__G__Graf2LN_TImagecLcLETileType;
extern G__linked_taginfo G__G__Graf2LN_TImagecLcLECoordMode;
extern G__linked_taginfo G__G__Graf2LN_TImagecLcLEColorChan;
extern G__linked_taginfo G__G__Graf2LN_TSplinePoly;
extern G__linked_taginfo G__G__Graf2LN_TSplinePoly3;
extern G__linked_taginfo G__G__Graf2LN_TSplinePoly5;
extern G__linked_taginfo G__G__Graf2LN_TSpline3;
extern G__linked_taginfo G__G__Graf2LN_TSpline5;
extern G__linked_taginfo G__G__Graf2LN_FormSize_t;
extern G__linked_taginfo G__G__Graf2LN_TextSpec_t;
extern G__linked_taginfo G__G__Graf2LN_FormSize;
extern G__linked_taginfo G__G__Graf2LN_TLatex;
extern G__linked_taginfo G__G__Graf2LN_TLatexcLcLdA;

/* STUB derived class for protected member access */
