/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Tps.xs. Do not edit this file, edit Tps.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Tps.xs"
#include "ZLIB/Tps/VTps.hh"


#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif

using namespace ZLIB;

#line 26 "Tps.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 168 "Tps.c"

XS_EUPXS(XS_Zlib__Space_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Space_new)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "CLASS, dim, order");
    {
	int	dim = (int)SvIV(ST(1))
;
	int	order = (int)SvIV(ST(2))
;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	Space *	RETVAL;
#line 23 "Tps.xs"
	RETVAL = new Space(dim, order);
#line 186 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Space_mltOrder); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Space_mltOrder)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Space *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Space *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Space::mltOrder() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 30 "Tps.xs"
	if(items == 1) RETVAL = THIS->mltOrder();
	if(items == 2) {
	  int value = (int ) SvIV(ST(1));
          THIS->mltOrder(value);
	  RETVAL = value;
	}
#line 219 "Tps.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Space_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Space_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Space *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Space *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Space::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Zlib__Tps_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	Tps *	RETVAL;

	RETVAL = new Tps();
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Tps *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Zlib__Tps_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Tps *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::size() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	RETVAL = THIS->size();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_order); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_order)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::order() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 57 "Tps.xs"
	if(items == 1) RETVAL = THIS->order(); 
        if(items == 2) {
	     int o = (int ) SvIV(ST(1));
             THIS->order(o);
             RETVAL = o;
	}
#line 342 "Tps.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_value)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::value() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 70 "Tps.xs"
	int index;

	if(SvIOK(ST(1))){
	   index = (int ) SvIV( ST(1) );
	}
        else{
	  if(SvNOK(ST(1))){ index = (int ) SvNV( ST(1) );}
	  else{
	     warn( "ZlibTps::value(...) -- index is not defined" );
             XSRETURN_UNDEF;	  
	  }
        }	  
	if(items == 2) RETVAL = (*THIS)[index]; 
        if(items == 3) {
	     double v = (double ) SvNV(ST(2));
             (*THIS)[index] = v;
             RETVAL = v;
	}
#line 386 "Tps.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_add)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::add() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 94 "Tps.xs"
        char* CLASS = "Zlib::Tps";
	RETVAL  = new Tps(*THIS);

        int flag = 0;

	if(SvNOK(ST(1))){
	  *RETVAL += (double ) SvNV( ST(1) );
           flag += 1;
	}
	if(SvIOK(ST(1))){
	    *RETVAL += (double ) SvIV( ST(1) );
            flag += 1;
	}	  
        if(SvROK(ST(1))){
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             *RETVAL += *((Tps *) SvIV((SV*) SvRV( ST(1) ))); 
             flag += 1;
	  }
        }
        if(!flag)
	{
	    warn( "ZLIB::Tps::add(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}
#line 435 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_multiply); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_multiply)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::multiply() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 124 "Tps.xs"
        char* CLASS = "Zlib::Tps";
	RETVAL  = new Tps(*THIS);

        int flag = 0;

	if(SvNOK(ST(1))){
	  *RETVAL *= (double ) SvNV( ST(1) );
           flag += 1;
	}
	if(SvIOK(ST(1))){
	  *RETVAL *= (double ) SvIV( ST(1) );
           flag += 1;
	}	  
        if(SvROK(ST(1))){
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             *RETVAL *= *((Tps *) SvIV((SV*) SvRV( ST(1) ))); 
             flag += 1;
	  }
        }
        if(!flag)
	{
	    warn( "ZLIB::Tps::multiply(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}
#line 485 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_subtract); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_subtract)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::subtract() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 154 "Tps.xs"
 	char* CLASS = "Zlib::Tps";
	RETVAL  = new Tps(*THIS);	    

        int flag = 0;

	if(SvNOK(ST(1))){
	  *RETVAL -= (double ) SvNV( ST(1) );
           flag += 1;
	}
	if(SvIOK(ST(1))){
	  *RETVAL -= (double ) SvIV( ST(1) );
           flag += 1;
	}	  
 	if(SvROK(ST(1))){       
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             *RETVAL -= *((Tps *) SvIV((SV*) SvRV( ST(1) ))); 
             flag += 1;
	  }
        }
        if(!flag)
	{
	    warn( "ZLIB::Tps::subtract(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}

        int r = (int) SvIV( ST(2) );
        if(r) *RETVAL *= -1.;

#line 539 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_divide); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_divide)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::divide() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 188 "Tps.xs"
        char* CLASS = "Zlib::Tps";

        int flag = 0;

        int r = (int) SvIV( ST(2) );

	if(SvNOK(ST(1))){
           if(r){
     	     RETVAL  = new Tps((double ) SvNV( ST(1) ), 0);
	    *RETVAL /= (*THIS);
           }
           else{
	      RETVAL  = new Tps(*THIS);
	     *RETVAL /= (double ) SvNV( ST(1) );
	   }
           flag += 1;
	}	
	if(SvIOK(ST(1))){
           if(r){
     	      RETVAL  = new Tps((double ) SvIV( ST(1) ), 0);
	     *RETVAL /= (*THIS);
           }
           else{
	      RETVAL  = new Tps(*THIS);
	     *RETVAL /= (double ) SvIV( ST(1) );
	   }
           flag += 1;
	}
	if(SvROK(ST(1))){  
	   if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             if(r){
               RETVAL   = new Tps(*((Tps *) SvIV((SV*) SvRV( ST(1) ))));
	      *RETVAL  /= (*THIS);
             }
             else{
	       RETVAL  = new Tps(*THIS);
              *RETVAL /= *((Tps *) SvIV((SV*) SvRV( ST(1) ))); 
	     }
             flag += 1;
           }
        }
        if(!flag)
	{
	    warn( "ZLIB::Tps::divide(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}

#line 612 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_D); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_D)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, iv");
    {
	int	iv = (int)SvIV(ST(1))
;
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::D() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 242 "Tps.xs"
	char* CLASS = "Zlib::Tps";

	RETVAL = new Tps;
       *RETVAL = D(*THIS, iv);

#line 645 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_poisson); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_poisson)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, tps");
    {
	Tps*	tps;
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		tps = (Tps *) SvIV((SV*) SvRV( ST(1) ));
	else{
		warn( "Zlib::Tps::poisson() -- tps is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::poisson() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 254 "Tps.xs"
	char* CLASS = "Zlib::Tps";

        RETVAL = new Tps;
       *RETVAL = poisson(*THIS, *tps);

#line 685 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_vpoisson); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_vpoisson)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, vtps");
    {
	VTps*	vtps;
	Tps *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		vtps = (VTps *) SvIV((SV*) SvRV( ST(1) ));
	else{
		warn( "Zlib::Tps::vpoisson() -- vtps is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::vpoisson() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 266 "Tps.xs"
	char* CLASS = "Zlib::VTps";

        RETVAL = new VTps(vtps->size());
       *RETVAL = poisson(*THIS, *vtps);

#line 725 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__Tps_sqrt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__Tps_sqrt)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Tps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Tps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::Tps::sqrt() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 277 "Tps.xs"
        char* CLASS = "Zlib::Tps";

	RETVAL  = new Tps;
       *RETVAL  = sqrt(*THIS);

#line 756 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, size");
    {
	int	size = (int)SvIV(ST(1))
;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	VTps *	RETVAL;

	RETVAL = new VTps(size);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	VTps *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Zlib__VTps_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	VTps *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::size() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	RETVAL = THIS->size();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_order); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_order)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	VTps *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::order() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 301 "Tps.xs"
	if(items == 1) RETVAL = THIS->order(); 
        if(items == 2) {
	     int o = (int ) SvIV(ST(1));
             THIS->order(o);
             RETVAL = o;
	}
#line 859 "Tps.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_value)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	VTps *	THIS;
	Tps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::value() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 313 "Tps.xs"
	int index;
	char* CLASS = "Zlib::Tps"; 	

	if(SvIOK(ST(1))){
	   index = (int ) SvIV( ST(1) );
	}
        else{
	  if(SvNOK(ST(1))){ index = (int ) SvNV( ST(1) );}
	  else{
	     warn( "ZLIB::Tps::value(...) -- index is not defined" );
             XSRETURN_UNDEF;	  
	  }
        }	  
	if(items == 2) RETVAL = new Tps((*THIS)[index]); 
        if(items == 3) {
	     if(SvTYPE(SvRV(ST(2))) == SVt_PVMG ){
                 RETVAL = new Tps(*( (Tps *) SvIV((SV*) SvRV( ST(2) )) )); 
                (*THIS)[index] = *RETVAL;
	     }
             else{
	         warn( "ZLIB::VTps::value(...) -- argument is not blessed SV reference" );
                 XSRETURN_UNDEF;
	     }
        }
#line 908 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_add)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	VTps *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::add() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 343 "Tps.xs"
        char* CLASS = "Zlib::VTps";
	RETVAL  = new VTps(*THIS);

        int flag = 0;

	if(SvNOK(ST(1))){
	  *RETVAL += (double ) SvNV( ST(1) );
           flag += 1;
	}
	if(SvIOK(ST(1))){
	    *RETVAL += (double ) SvIV( ST(1) );
            flag += 1;
	}	  
        if(SvROK(ST(1))){
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             *RETVAL += *((VTps *) SvIV((SV*) SvRV( ST(1) ))); 
             flag += 1;
	  }
        }
        if(!flag)
	{
	    warn( "ZLIB::VTps::add(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}
#line 958 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_subtract); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_subtract)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	VTps *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::subtract() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 375 "Tps.xs"
 	char* CLASS = "Zlib::VTps";
	RETVAL  = new VTps(*THIS);	    

        int flag = 0;

	if(SvNOK(ST(1))){
	  *RETVAL -= (double ) SvNV( ST(1) );
           flag += 1;
	}
	if(SvIOK(ST(1))){
	  *RETVAL -= (double ) SvIV( ST(1) );
           flag += 1;
	}	  
 	if(SvROK(ST(1))){       
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             *RETVAL -= *((VTps *) SvIV((SV*) SvRV( ST(1) ))); 
             flag += 1;
	  }
        }
        if(!flag)
	{
	    warn( "ZLIB::VTps::subtract(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}

        int r = (int) SvIV( ST(2) );
        if(r) *RETVAL *= -1.;

#line 1012 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_multiply); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_multiply)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	VTps *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::multiply() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 409 "Tps.xs"
        char* CLASS = "Zlib::VTps";
        double v;

        int flag = 0;

        int r = (int) SvIV( ST(2) );

	if(SvNOK(ST(1))){
	   RETVAL  = new VTps(*THIS);
	  *RETVAL *= (double ) SvNV( ST(1) );
           flag += 1;
	}	
	if(SvIOK(ST(1))){
	   RETVAL  = new VTps(*THIS);
	  *RETVAL *= (double ) SvIV( ST(1) );
           flag += 1;
	}
	if(SvROK(ST(1))){  
	   if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             if(r){
               RETVAL   = new VTps(*((VTps *) SvIV((SV*) SvRV( ST(1) ))));
	      *RETVAL  *= (*THIS);
             }
             else{
	       RETVAL  = new VTps(*THIS);
              *RETVAL *= *((VTps *) SvIV((SV*) SvRV( ST(1) ))); 
	     }
             flag += 1;
           }
        }
        if(!flag)
	{
	    warn( "ZLIB::VTps::multiply(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}

#line 1074 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_divide); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_divide)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	VTps *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::divide() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 451 "Tps.xs"
        char* CLASS = "Zlib::VTps";
        double v;

        int flag = 0;

        int r = (int) SvIV( ST(2) );

	if(SvNOK(ST(1))){
           if(r){
     	     RETVAL  = new VTps(THIS->size());
            *RETVAL  = (double ) SvNV( ST(1) );
	    *RETVAL /= (*THIS);
           }
           else{
	      RETVAL  = new VTps(*THIS);
	     *RETVAL /= (double ) SvNV( ST(1) );
	   }
           flag += 1;
	}	
	if(SvIOK(ST(1))){
           if(r){
     	      RETVAL  = new VTps(THIS->size());
             *RETVAL  = (double ) SvNV( ST(1) );            
	     *RETVAL /= (*THIS);
           }
           else{
	      RETVAL  = new VTps(*THIS);
	     *RETVAL /= (double ) SvIV( ST(1) );
	   }
           flag += 1;
	}
	if(SvROK(ST(1))){  
	   if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
             if(r){
               RETVAL   = new VTps(*((VTps *) SvIV((SV*) SvRV( ST(1) ))));
	      *RETVAL  /= (*THIS);
             }
             else{
	       RETVAL  = new VTps(*THIS);
              *RETVAL /= *((VTps *) SvIV((SV*) SvRV( ST(1) ))); 
	     }
             flag += 1;
           }
        }
        if(!flag)
	{
	    warn( "ZLIB::VTps::divide(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}

#line 1150 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_D); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_D)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, iv");
    {
	int	iv = (int)SvIV(ST(1))
;
	VTps *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::D() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 508 "Tps.xs"
	char* CLASS = "Zlib::VTps";

	RETVAL = new VTps(THIS->size());
       *RETVAL = D(*THIS, iv);

#line 1183 "Tps.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Zlib__VTps_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_read)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, file");
    {
	char*	file = (char *)SvPV_nolen(ST(1))
;
	VTps *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::read() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	THIS->read(file);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Zlib__VTps_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Zlib__VTps_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, file");
    {
	char*	file = (char *)SvPV_nolen(ST(1))
;
	VTps *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (VTps *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Zlib::VTps::write() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	THIS->write(file);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Zlib__Tps); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Zlib__Tps)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Zlib::Space::new", XS_Zlib__Space_new, file, "$$$");
        (void)newXSproto_portable("Zlib::Space::mltOrder", XS_Zlib__Space_mltOrder, file, "$;@");
        (void)newXSproto_portable("Zlib::Space::DESTROY", XS_Zlib__Space_DESTROY, file, "$");
        (void)newXSproto_portable("Zlib::Tps::new", XS_Zlib__Tps_new, file, "$");
        (void)newXSproto_portable("Zlib::Tps::DESTROY", XS_Zlib__Tps_DESTROY, file, "$");
        (void)newXSproto_portable("Zlib::Tps::size", XS_Zlib__Tps_size, file, "$");
        (void)newXSproto_portable("Zlib::Tps::order", XS_Zlib__Tps_order, file, "$;@");
        (void)newXSproto_portable("Zlib::Tps::value", XS_Zlib__Tps_value, file, "$;@");
        (void)newXSproto_portable("Zlib::Tps::add", XS_Zlib__Tps_add, file, "$;@");
        (void)newXSproto_portable("Zlib::Tps::multiply", XS_Zlib__Tps_multiply, file, "$;@");
        (void)newXSproto_portable("Zlib::Tps::subtract", XS_Zlib__Tps_subtract, file, "$;@");
        (void)newXSproto_portable("Zlib::Tps::divide", XS_Zlib__Tps_divide, file, "$;@");
        (void)newXSproto_portable("Zlib::Tps::D", XS_Zlib__Tps_D, file, "$$");
        (void)newXSproto_portable("Zlib::Tps::poisson", XS_Zlib__Tps_poisson, file, "$$");
        (void)newXSproto_portable("Zlib::Tps::vpoisson", XS_Zlib__Tps_vpoisson, file, "$$");
        (void)newXSproto_portable("Zlib::Tps::sqrt", XS_Zlib__Tps_sqrt, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::new", XS_Zlib__VTps_new, file, "$$");
        (void)newXSproto_portable("Zlib::VTps::DESTROY", XS_Zlib__VTps_DESTROY, file, "$");
        (void)newXSproto_portable("Zlib::VTps::size", XS_Zlib__VTps_size, file, "$");
        (void)newXSproto_portable("Zlib::VTps::order", XS_Zlib__VTps_order, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::value", XS_Zlib__VTps_value, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::add", XS_Zlib__VTps_add, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::subtract", XS_Zlib__VTps_subtract, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::multiply", XS_Zlib__VTps_multiply, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::divide", XS_Zlib__VTps_divide, file, "$;@");
        (void)newXSproto_portable("Zlib::VTps::D", XS_Zlib__VTps_D, file, "$$");
        (void)newXSproto_portable("Zlib::VTps::read", XS_Zlib__VTps_read, file, "$$");
        (void)newXSproto_portable("Zlib::VTps::write", XS_Zlib__VTps_write, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

