/********************************************************************
* gl/src/G__GL.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error gl/src/G__GL.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__GL();
extern void G__cpp_setup_inheritanceG__GL();
extern void G__cpp_setup_typetableG__GL();
extern void G__cpp_setup_memvarG__GL();
extern void G__cpp_setup_globalG__GL();
extern void G__cpp_setup_memfuncG__GL();
extern void G__cpp_setup_funcG__GL();
extern void G__set_cpp_environmentG__GL();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "gl/inc/TViewerOpenGL.h"
#include "gl/inc/TGLRenderArea.h"
#include "gl/inc/TGLEditor.h"
#include "gl/inc/TArcBall.h"
#include "gl/inc/TGLCamera.h"
#include "gl/inc/TGLSceneObject.h"
#include "gl/inc/TX11GL.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GLLN_TClass;
extern G__linked_taginfo G__G__GLLN_TBuffer;
extern G__linked_taginfo G__G__GLLN_TMemberInspector;
extern G__linked_taginfo G__G__GLLN_TObject;
extern G__linked_taginfo G__G__GLLN_TList;
extern G__linked_taginfo G__G__GLLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__GLLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GLLN_TVirtualPad;
extern G__linked_taginfo G__G__GLLN_TBuffer3D;
extern G__linked_taginfo G__G__GLLN_TVirtualViewer3D;
extern G__linked_taginfo G__G__GLLN_TQObject;
extern G__linked_taginfo G__G__GLLN_Event_t;
extern G__linked_taginfo G__G__GLLN_TGObject;
extern G__linked_taginfo G__G__GLLN_TGWindow;
extern G__linked_taginfo G__G__GLLN_TPoint;
extern G__linked_taginfo G__G__GLLN_TGFrame;
extern G__linked_taginfo G__G__GLLN_TGCompositeFrame;
extern G__linked_taginfo G__G__GLLN_TGLayoutHints;
extern G__linked_taginfo G__G__GLLN_TContextMenu;
extern G__linked_taginfo G__G__GLLN_TGVerticalFrame;
extern G__linked_taginfo G__G__GLLN_TGMainFrame;
extern G__linked_taginfo G__G__GLLN_TGLSceneObject;
extern G__linked_taginfo G__G__GLLN_TGLFrustum;
extern G__linked_taginfo G__G__GLLN_TGLSelection;
extern G__linked_taginfo G__G__GLLN_TGLCamera;
extern G__linked_taginfo G__G__GLLN_TGLRender;
extern G__linked_taginfo G__G__GLLN_pairlEdoublecOdoublegR;
extern G__linked_taginfo G__G__GLLN_RootCsg;
extern G__linked_taginfo G__G__GLLN_RootCsgcLcLBaseMesh;
extern G__linked_taginfo G__G__GLLN_TGLGeometryEditor;
extern G__linked_taginfo G__G__GLLN_TGShutterItem;
extern G__linked_taginfo G__G__GLLN_TGShutter;
extern G__linked_taginfo G__G__GLLN_TGLRenderArea;
extern G__linked_taginfo G__G__GLLN_TGPopupMenu;
extern G__linked_taginfo G__G__GLLN_TGLColorEditor;
extern G__linked_taginfo G__G__GLLN_TGLSceneEditor;
extern G__linked_taginfo G__G__GLLN_TGLLightEditor;
extern G__linked_taginfo G__G__GLLN_TGMenuBar;
extern G__linked_taginfo G__G__GLLN_TGCanvas;
extern G__linked_taginfo G__G__GLLN_TArcBall;
extern G__linked_taginfo G__G__GLLN_TViewerOpenGL;
extern G__linked_taginfo G__G__GLLN_TViewerOpenGLcLcLEViews;
extern G__linked_taginfo G__G__GLLN_TViewerOpenGLcLcLEAction;
extern G__linked_taginfo G__G__GLLN_pairlEunsignedsPintcORootCsgcLcLBaseMeshmUgR;
extern G__linked_taginfo G__G__GLLN_vectorlEpairlEunsignedsPintcORootCsgcLcLBaseMeshmUgRcOallocatorlEpairlEunsignedsPintcORootCsgcLcLBaseMeshmUgRsPgRsPgR;
extern G__linked_taginfo G__G__GLLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcORootCsgcLcLBaseMeshmUgRcOallocatorlEpairlEunsignedsPintcORootCsgcLcLBaseMeshmUgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GLLN_TViewerOpenGLcLcL277;
extern G__linked_taginfo G__G__GLLN_TGLWindow;
extern G__linked_taginfo G__G__GLLN_TGCheckButton;
extern G__linked_taginfo G__G__GLLN_TGNumberEntry;
extern G__linked_taginfo G__G__GLLN_TGLMatView;
extern G__linked_taginfo G__G__GLLN_TGHSlider;
extern G__linked_taginfo G__G__GLLN_TGButton;
extern G__linked_taginfo G__G__GLLN_TGLColorEditorcLcLELightMode;
extern G__linked_taginfo G__G__GLLN_TGLGeometryEditorcLcLdA;
extern G__linked_taginfo G__G__GLLN_TGLSceneEditorcLcLdA;
extern G__linked_taginfo G__G__GLLN_TGLLightEditorcLcLEBuiltInLight;
extern G__linked_taginfo G__G__GLLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__G__GLLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GLLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__G__GLLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GLLN_vectorlETGLMeshmUcOallocatorlETGLMeshmUgRsPgR;
extern G__linked_taginfo G__G__GLLN_reverse_iteratorlEvectorlETGLMeshmUcOallocatorlETGLMeshmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GLLN_TVirtualGLImp;
extern G__linked_taginfo G__G__GLLN_Display;
extern G__linked_taginfo G__G__GLLN_XVisualInfo;
extern G__linked_taginfo G__G__GLLN_TX11GL;

/* STUB derived class for protected member access */
