/********************************************************************
* g3d/src/G__G3D.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error g3d/src/G__G3D.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__G3D();
extern void G__cpp_setup_inheritanceG__G3D();
extern void G__cpp_setup_typetableG__G3D();
extern void G__cpp_setup_memvarG__G3D();
extern void G__cpp_setup_globalG__G3D();
extern void G__cpp_setup_memfuncG__G3D();
extern void G__cpp_setup_funcG__G3D();
extern void G__set_cpp_environmentG__G3D();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "g3d/inc/TTRD2.h"
#include "g3d/inc/TMixture.h"
#include "g3d/inc/TCONS.h"
#include "g3d/inc/TTRAP.h"
#include "g3d/inc/THelix.h"
#include "g3d/inc/TPGON.h"
#include "g3d/inc/TSPHE.h"
#include "g3d/inc/TPolyLine3D.h"
#include "g3d/inc/TPoints3DABC.h"
#include "g3d/inc/TGTRA.h"
#include "g3d/inc/TMarker3DBox.h"
#include "g3d/inc/TCONE.h"
#include "g3d/inc/THYPE.h"
#include "g3d/inc/TBRIK.h"
#include "g3d/inc/TPCON.h"
#include "g3d/inc/TShape.h"
#include "g3d/inc/TUtil3D.h"
#include "g3d/inc/TXTRU.h"
#include "g3d/inc/TTRD1.h"
#include "g3d/inc/TELTU.h"
#include "g3d/inc/TRotMatrix.h"
#include "g3d/inc/TAxis3D.h"
#include "g3d/inc/TNode.h"
#include "g3d/inc/TMaterial.h"
#include "g3d/inc/TTUBE.h"
#include "g3d/inc/TPolyMarker3D.h"
#include "g3d/inc/TCTUB.h"
#include "g3d/inc/TGeometry.h"
#include "g3d/inc/TNodeDiv.h"
#include "g3d/inc/TPARA.h"
#include "g3d/inc/TTUBS.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__G3DLN_TClass;
extern G__linked_taginfo G__G__G3DLN_TBuffer;
extern G__linked_taginfo G__G__G3DLN_TMemberInspector;
extern G__linked_taginfo G__G__G3DLN_TObject;
extern G__linked_taginfo G__G__G3DLN_TNamed;
extern G__linked_taginfo G__G__G3DLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__G3DLN_TList;
extern G__linked_taginfo G__G__G3DLN_TBrowser;
extern G__linked_taginfo G__G__G3DLN_TObjArray;
extern G__linked_taginfo G__G__G3DLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__G3DLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__G3DLN_TCollection;
extern G__linked_taginfo G__G__G3DLN_TString;
extern G__linked_taginfo G__G__G3DLN_TVirtualPad;
extern G__linked_taginfo G__G__G3DLN_TAttFill;
extern G__linked_taginfo G__G__G3DLN_TMaterial;
extern G__linked_taginfo G__G__G3DLN_TAttLine;
extern G__linked_taginfo G__G__G3DLN_TAtt3D;
extern G__linked_taginfo G__G__G3DLN_TBuffer3D;
extern G__linked_taginfo G__G__G3DLN_TNode;
extern G__linked_taginfo G__G__G3DLN_TShape;
extern G__linked_taginfo G__G__G3DLN_TBRIK;
extern G__linked_taginfo G__G__G3DLN_TTRD2;
extern G__linked_taginfo G__G__G3DLN_TMixture;
extern G__linked_taginfo G__G__G3DLN_TTUBE;
extern G__linked_taginfo G__G__G3DLN_TTUBS;
extern G__linked_taginfo G__G__G3DLN_TCONS;
extern G__linked_taginfo G__G__G3DLN_TTRAP;
extern G__linked_taginfo G__G__G3DLN_TPolyLine3D;
extern G__linked_taginfo G__G__G3DLN_TRotMatrix;
extern G__linked_taginfo G__G__G3DLN_EHelixRangeType;
extern G__linked_taginfo G__G__G3DLN_THelix;
extern G__linked_taginfo G__G__G3DLN_TPCON;
extern G__linked_taginfo G__G__G3DLN_TPGON;
extern G__linked_taginfo G__G__G3DLN_TSPHE;
extern G__linked_taginfo G__G__G3DLN_TPoints3DABC;
extern G__linked_taginfo G__G__G3DLN_TGTRA;
extern G__linked_taginfo G__G__G3DLN_TH1;
extern G__linked_taginfo G__G__G3DLN_TMarker3DBox;
extern G__linked_taginfo G__G__G3DLN_TCONE;
extern G__linked_taginfo G__G__G3DLN_THYPE;
extern G__linked_taginfo G__G__G3DLN_TVirtualUtil3D;
extern G__linked_taginfo G__G__G3DLN_TUtil3D;
extern G__linked_taginfo G__G__G3DLN_TXTRU;
extern G__linked_taginfo G__G__G3DLN_TXTRUcLcLEXYChecked;
extern G__linked_taginfo G__G__G3DLN_TXTRUcLcLEZChecked;
extern G__linked_taginfo G__G__G3DLN_TTRD1;
extern G__linked_taginfo G__G__G3DLN_TELTU;
extern G__linked_taginfo G__G__G3DLN_THashList;
extern G__linked_taginfo G__G__G3DLN_TAxis;
extern G__linked_taginfo G__G__G3DLN_TGaxis;
extern G__linked_taginfo G__G__G3DLN_TView;
extern G__linked_taginfo G__G__G3DLN_TAxis3D;
extern G__linked_taginfo G__G__G3DLN_TNodecLcLdA;
extern G__linked_taginfo G__G__G3DLN_TAttMarker;
extern G__linked_taginfo G__G__G3DLN_TPolyMarker3D;
extern G__linked_taginfo G__G__G3DLN_TCTUB;
extern G__linked_taginfo G__G__G3DLN_TGeometry;
extern G__linked_taginfo G__G__G3DLN_TNodeDiv;
extern G__linked_taginfo G__G__G3DLN_TPARA;

/* STUB derived class for protected member access */
