/********************************************************************
* histpainter/src/G__HistPainter.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error histpainter/src/G__HistPainter.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__HistPainter();
extern void G__cpp_setup_inheritanceG__HistPainter();
extern void G__cpp_setup_typetableG__HistPainter();
extern void G__cpp_setup_memvarG__HistPainter();
extern void G__cpp_setup_globalG__HistPainter();
extern void G__cpp_setup_memfuncG__HistPainter();
extern void G__cpp_setup_funcG__HistPainter();
extern void G__set_cpp_environmentG__HistPainter();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "histpainter/inc/TLego.h"
#include "histpainter/inc/TPaletteAxis.h"
#include "histpainter/inc/THistPainter.h"
#include "histpainter/inc/TGraphPainter.h"
#include "histpainter/inc/TPainter3dAlgorithms.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__HistPainterLN_TClass;
extern G__linked_taginfo G__G__HistPainterLN_TBuffer;
extern G__linked_taginfo G__G__HistPainterLN_TMemberInspector;
extern G__linked_taginfo G__G__HistPainterLN_TObject;
extern G__linked_taginfo G__G__HistPainterLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__HistPainterLN_TList;
extern G__linked_taginfo G__G__HistPainterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__HistPainterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__HistPainterLN_TString;
extern G__linked_taginfo G__G__HistPainterLN_TAttLine;
extern G__linked_taginfo G__G__HistPainterLN_TAttFill;
extern G__linked_taginfo G__G__HistPainterLN_TF1;
extern G__linked_taginfo G__G__HistPainterLN_TH1;
extern G__linked_taginfo G__G__HistPainterLN_TAxis;
extern G__linked_taginfo G__G__HistPainterLN_TF3;
extern G__linked_taginfo G__G__HistPainterLN_TPainter3dAlgorithms;
extern G__linked_taginfo G__G__HistPainterLN_TBox;
extern G__linked_taginfo G__G__HistPainterLN_TPave;
extern G__linked_taginfo G__G__HistPainterLN_TGaxis;
extern G__linked_taginfo G__G__HistPainterLN_TVirtualHistPainter;
extern G__linked_taginfo G__G__HistPainterLN_TPaletteAxis;
extern G__linked_taginfo G__G__HistPainterLN_TPaletteAxiscLcLdA;
extern G__linked_taginfo G__G__HistPainterLN_TCutG;
extern G__linked_taginfo G__G__HistPainterLN_TGraphPainter;
extern G__linked_taginfo G__G__HistPainterLN_THistPainter;
extern G__linked_taginfo G__G__HistPainterLN_TGraph2D;
extern G__linked_taginfo G__G__HistPainterLN_TGraphDelaunay;

/* STUB derived class for protected member access */
