/********************************************************************
* minuit/src/G__Minuit.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error minuit/src/G__Minuit.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Minuit();
extern void G__cpp_setup_inheritanceG__Minuit();
extern void G__cpp_setup_typetableG__Minuit();
extern void G__cpp_setup_memvarG__Minuit();
extern void G__cpp_setup_globalG__Minuit();
extern void G__cpp_setup_memfuncG__Minuit();
extern void G__cpp_setup_funcG__Minuit();
extern void G__set_cpp_environmentG__Minuit();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "minuit/inc/TLinearFitter.h"
#include "minuit/inc/TFitter.h"
#include "minuit/inc/TMinuit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MinuitLN_TClass;
extern G__linked_taginfo G__G__MinuitLN_TBuffer;
extern G__linked_taginfo G__G__MinuitLN_TMemberInspector;
extern G__linked_taginfo G__G__MinuitLN_TObject;
extern G__linked_taginfo G__G__MinuitLN_TNamed;
extern G__linked_taginfo G__G__MinuitLN_TObjArray;
extern G__linked_taginfo G__G__MinuitLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__MinuitLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MinuitLN_TString;
extern G__linked_taginfo G__G__MinuitLN_TMethodCall;
extern G__linked_taginfo G__G__MinuitLN_TVectorD;
extern G__linked_taginfo G__G__MinuitLN_TMatrixD;
extern G__linked_taginfo G__G__MinuitLN_TMatrixDSym;
extern G__linked_taginfo G__G__MinuitLN_TFormula;
extern G__linked_taginfo G__G__MinuitLN_TVirtualFitter;
extern G__linked_taginfo G__G__MinuitLN_TLinearFitter;
extern G__linked_taginfo G__G__MinuitLN_TMinuit;
extern G__linked_taginfo G__G__MinuitLN_TFitter;
extern G__linked_taginfo G__G__MinuitLN_TMinuitcLcLdA;

/* STUB derived class for protected member access */
