/********************************************************************
* gui/src/G__Gui1.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error gui/src/G__Gui1.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Gui1();
extern void G__cpp_setup_inheritanceG__Gui1();
extern void G__cpp_setup_typetableG__Gui1();
extern void G__cpp_setup_memvarG__Gui1();
extern void G__cpp_setup_globalG__Gui1();
extern void G__cpp_setup_memfuncG__Gui1();
extern void G__cpp_setup_funcG__Gui1();
extern void G__set_cpp_environmentG__Gui1();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "gui/inc/TGObject.h"
#include "gui/inc/TGClient.h"
#include "gui/inc/TGWindow.h"
#include "gui/inc/TGPicture.h"
#include "gui/inc/TGDimension.h"
#include "gui/inc/TGFrame.h"
#include "gui/inc/TGLayout.h"
#include "gui/inc/TGString.h"
#include "gui/inc/TGWidget.h"
#include "gui/inc/TGIcon.h"
#include "gui/inc/TGLabel.h"
#include "gui/inc/TGButton.h"
#include "gui/inc/TGTextBuffer.h"
#include "gui/inc/TGTextEntry.h"
#include "gui/inc/TGMsgBox.h"
#include "gui/inc/TGMenu.h"
#include "gui/inc/TGGC.h"
#include "gui/inc/TGShutter.h"
#include "gui/inc/TG3DLine.h"
#include "gui/inc/TGProgressBar.h"
#include "gui/inc/TGButtonGroup.h"
#include "gui/inc/TGNumberEntry.h"
#include "gui/inc/TGTableLayout.h"
#include "gui/inc/WidgetMessageTypes.h"
#include "gui/inc/TGIdleHandler.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Gui1LN_TClass;
extern G__linked_taginfo G__G__Gui1LN_TBuffer;
extern G__linked_taginfo G__G__Gui1LN_TMemberInspector;
extern G__linked_taginfo G__G__Gui1LN_TObject;
extern G__linked_taginfo G__G__Gui1LN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Gui1LN_TList;
extern G__linked_taginfo G__G__Gui1LN_TTimer;
extern G__linked_taginfo G__G__Gui1LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__Gui1LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Gui1LN_TRefCnt;
extern G__linked_taginfo G__G__Gui1LN_TString;
extern G__linked_taginfo G__G__Gui1LN_TColor;
extern G__linked_taginfo G__G__Gui1LN_EGEventType;
extern G__linked_taginfo G__G__Gui1LN_EGraphicsFunction;
extern G__linked_taginfo G__G__Gui1LN_SetWindowAttributes_t;
extern G__linked_taginfo G__G__Gui1LN_Event_t;
extern G__linked_taginfo G__G__Gui1LN_GCValues_t;
extern G__linked_taginfo G__G__Gui1LN_PictureAttributes_t;
extern G__linked_taginfo G__G__Gui1LN_EInitialState;
extern G__linked_taginfo G__G__Gui1LN_TGClient;
extern G__linked_taginfo G__G__Gui1LN_TGObject;
extern G__linked_taginfo G__G__Gui1LN_THashList;
extern G__linked_taginfo G__G__Gui1LN_TGWindow;
extern G__linked_taginfo G__G__Gui1LN_TGResourcePool;
extern G__linked_taginfo G__G__Gui1LN_TGPicturePool;
extern G__linked_taginfo G__G__Gui1LN_TGPicture;
extern G__linked_taginfo G__G__Gui1LN_TGGCPool;
extern G__linked_taginfo G__G__Gui1LN_TGGC;
extern G__linked_taginfo G__G__Gui1LN_TGFontPool;
extern G__linked_taginfo G__G__Gui1LN_TGFont;
extern G__linked_taginfo G__G__Gui1LN_TGMimeTypes;
extern G__linked_taginfo G__G__Gui1LN_TGUnknownWindowHandler;
extern G__linked_taginfo G__G__Gui1LN_TGIdleHandler;
extern G__linked_taginfo G__G__Gui1LN_THashTable;
extern G__linked_taginfo G__G__Gui1LN_TGSelectedPicture;
extern G__linked_taginfo G__G__Gui1LN_TGDimension;
extern G__linked_taginfo G__G__Gui1LN_TGPosition;
extern G__linked_taginfo G__G__Gui1LN_TGLongPosition;
extern G__linked_taginfo G__G__Gui1LN_TGInsets;
extern G__linked_taginfo G__G__Gui1LN_TGRectangle;
extern G__linked_taginfo G__G__Gui1LN_TQObject;
extern G__linked_taginfo G__G__Gui1LN_ELayoutHints;
extern G__linked_taginfo G__G__Gui1LN_TGFrame;
extern G__linked_taginfo G__G__Gui1LN_TGCompositeFrame;
extern G__linked_taginfo G__G__Gui1LN_TGLayoutHints;
extern G__linked_taginfo G__G__Gui1LN_TGFrameElement;
extern G__linked_taginfo G__G__Gui1LN_TGLayoutManager;
extern G__linked_taginfo G__G__Gui1LN_TGVerticalLayout;
extern G__linked_taginfo G__G__Gui1LN_TGHorizontalLayout;
extern G__linked_taginfo G__G__Gui1LN_TGRowLayout;
extern G__linked_taginfo G__G__Gui1LN_TGColumnLayout;
extern G__linked_taginfo G__G__Gui1LN_TGMatrixLayout;
extern G__linked_taginfo G__G__Gui1LN_TGTileLayout;
extern G__linked_taginfo G__G__Gui1LN_TGListLayout;
extern G__linked_taginfo G__G__Gui1LN_TGListDetailsLayout;
extern G__linked_taginfo G__G__Gui1LN_TGString;
extern G__linked_taginfo G__G__Gui1LN_TGHotString;
extern G__linked_taginfo G__G__Gui1LN_TContextMenu;
extern G__linked_taginfo G__G__Gui1LN_EFrameState;
extern G__linked_taginfo G__G__Gui1LN_EFrameCleanup;
extern G__linked_taginfo G__G__Gui1LN_EFrameType;
extern G__linked_taginfo G__G__Gui1LN_EMWMHints;
extern G__linked_taginfo G__G__Gui1LN_TGVerticalFrame;
extern G__linked_taginfo G__G__Gui1LN_TGHorizontalFrame;
extern G__linked_taginfo G__G__Gui1LN_TGMainFrame;
extern G__linked_taginfo G__G__Gui1LN_TGMainFramecLcLdA;
extern G__linked_taginfo G__G__Gui1LN_TGTransientFrame;
extern G__linked_taginfo G__G__Gui1LN_TGTransientFramecLcLEPlacement;
extern G__linked_taginfo G__G__Gui1LN_TGGroupFrame;
extern G__linked_taginfo G__G__Gui1LN_TGGroupFramecLcLETitlePos;
extern G__linked_taginfo G__G__Gui1LN_EWidgetMessageTypes;
extern G__linked_taginfo G__G__Gui1LN_ETextJustification;
extern G__linked_taginfo G__G__Gui1LN_EWidgetStatus;
extern G__linked_taginfo G__G__Gui1LN_TGWidget;
extern G__linked_taginfo G__G__Gui1LN_TGIcon;
extern G__linked_taginfo G__G__Gui1LN_TGLabel;
extern G__linked_taginfo G__G__Gui1LN_EButtonState;
extern G__linked_taginfo G__G__Gui1LN_TGToolTip;
extern G__linked_taginfo G__G__Gui1LN_TGButtonGroup;
extern G__linked_taginfo G__G__Gui1LN_TGButton;
extern G__linked_taginfo G__G__Gui1LN_TGTextButton;
extern G__linked_taginfo G__G__Gui1LN_TGPictureButton;
extern G__linked_taginfo G__G__Gui1LN_TGCheckButton;
extern G__linked_taginfo G__G__Gui1LN_TGRadioButton;
extern G__linked_taginfo G__G__Gui1LN_TGTextBuffer;
extern G__linked_taginfo G__G__Gui1LN_TBlinkTimer;
extern G__linked_taginfo G__G__Gui1LN_TGTextEntry;
extern G__linked_taginfo G__G__Gui1LN_TGTextEntrycLcLEEchoMode;
extern G__linked_taginfo G__G__Gui1LN_TGTextEntrycLcLEInsertMode;
extern G__linked_taginfo G__G__Gui1LN_EMsgBoxIcon;
extern G__linked_taginfo G__G__Gui1LN_EMsgBoxButton;
extern G__linked_taginfo G__G__Gui1LN_TGMsgBox;
extern G__linked_taginfo G__G__Gui1LN_EMenuEntryState;
extern G__linked_taginfo G__G__Gui1LN_EMenuEntryType;
extern G__linked_taginfo G__G__Gui1LN_TGPopupMenu;
extern G__linked_taginfo G__G__Gui1LN_TGMenuBar;
extern G__linked_taginfo G__G__Gui1LN_TGMenuTitle;
extern G__linked_taginfo G__G__Gui1LN_TGMenuEntry;
extern G__linked_taginfo G__G__Gui1LN_TGCanvas;
extern G__linked_taginfo G__G__Gui1LN_TGShutterItem;
extern G__linked_taginfo G__G__Gui1LN_TGShutter;
extern G__linked_taginfo G__G__Gui1LN_TGHorizontal3DLine;
extern G__linked_taginfo G__G__Gui1LN_TGVertical3DLine;
extern G__linked_taginfo G__G__Gui1LN_TGProgressBar;
extern G__linked_taginfo G__G__Gui1LN_TGProgressBarcLcLEBarType;
extern G__linked_taginfo G__G__Gui1LN_TGProgressBarcLcLEFillType;
extern G__linked_taginfo G__G__Gui1LN_TGProgressBarcLcLdA;
extern G__linked_taginfo G__G__Gui1LN_TGHProgressBar;
extern G__linked_taginfo G__G__Gui1LN_TGVProgressBar;
extern G__linked_taginfo G__G__Gui1LN_TMap;
extern G__linked_taginfo G__G__Gui1LN_TGVButtonGroup;
extern G__linked_taginfo G__G__Gui1LN_TGHButtonGroup;
extern G__linked_taginfo G__G__Gui1LN_TGNumberFormat;
extern G__linked_taginfo G__G__Gui1LN_TGNumberFormatcLcLEStyle;
extern G__linked_taginfo G__G__Gui1LN_TGNumberFormatcLcLEAttribute;
extern G__linked_taginfo G__G__Gui1LN_TGNumberFormatcLcLELimit;
extern G__linked_taginfo G__G__Gui1LN_TGNumberFormatcLcLEStepSize;
extern G__linked_taginfo G__G__Gui1LN_TGNumberEntryField;
extern G__linked_taginfo G__G__Gui1LN_TGNumberEntry;
extern G__linked_taginfo G__G__Gui1LN_ETableLayoutHints;
extern G__linked_taginfo G__G__Gui1LN_TGTableLayoutHints;
extern G__linked_taginfo G__G__Gui1LN_TGTableLayout;
extern G__linked_taginfo G__G__Gui1LN_TGTableLayoutcLcLTableData;

/* STUB derived class for protected member access */
