//
// File generated by utils/src/rootcint_tmp at Wed Jul  1 06:28:26 2020.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "G__Rint.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void TTabCom_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TTabCom_IsA(const void*);
   static void *new_TTabCom(void *p = 0);
   static void *newArray_TTabCom(Long_t size);
   static void delete_TTabCom(void *p);
   static void deleteArray_TTabCom(void *p);
   static void destruct_TTabCom(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::TTabCom*)
   {
      ::TTabCom *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("TTabCom", ::TTabCom::Class_Version(), "rint/inc/TTabCom.h", 61,
                  typeid(::TTabCom), DefineBehavior(ptr, ptr),
                  &::TTabCom::Dictionary, &TTabCom_IsA, 0,
                  sizeof(::TTabCom) );
      instance.SetNew(&new_TTabCom);
      instance.SetNewArray(&newArray_TTabCom);
      instance.SetDelete(&delete_TTabCom);
      instance.SetDeleteArray(&deleteArray_TTabCom);
      instance.SetDestructor(&destruct_TTabCom);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::TTabCom*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

namespace ROOT {
   void TRint_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TRint_IsA(const void*);
   static void delete_TRint(void *p);
   static void deleteArray_TRint(void *p);
   static void destruct_TRint(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::TRint*)
   {
      ::TRint *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("TRint", ::TRint::Class_Version(), "rint/inc/TRint.h", 35,
                  typeid(::TRint), DefineBehavior(ptr, ptr),
                  &::TRint::Dictionary, &TRint_IsA, 0,
                  sizeof(::TRint) );
      instance.SetDelete(&delete_TRint);
      instance.SetDeleteArray(&deleteArray_TRint);
      instance.SetDestructor(&destruct_TRint);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::TRint*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *TTabCom::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TTabCom::Class_Name()
{
   return "TTabCom";
}

//______________________________________________________________________________
const char *TTabCom::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::TTabCom*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TTabCom::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::TTabCom*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TTabCom::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::TTabCom*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TTabCom::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::TTabCom*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TRint::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TRint::Class_Name()
{
   return "TRint";
}

//______________________________________________________________________________
const char *TRint::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::TRint*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TRint::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::TRint*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TRint::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::TRint*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TRint::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::TRint*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TRint::Streamer(TBuffer &R__b)
{
   // Stream an object of class TRint.

   TApplication::Streamer(R__b);
}

//______________________________________________________________________________
void TRint::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TRint.

      TClass *R__cl = ::TRint::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fNcmd", &fNcmd);
      R__insp.Inspect(R__cl, R__parent, "fDefaultPrompt", &fDefaultPrompt);
      fDefaultPrompt.ShowMembers(R__insp, strcat(R__parent,"fDefaultPrompt.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fPrompt[64]", fPrompt);
      R__insp.Inspect(R__cl, R__parent, "fInterrupt", &fInterrupt);
      R__insp.Inspect(R__cl, R__parent, "*fInputHandler", &fInputHandler);
      TApplication::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TRint_IsA(const void *obj) {
      return ((::TRint*)obj)->IsA();
   }
   // Wrapper around operator delete
   static void delete_TRint(void *p) {
      delete ((::TRint*)p);
   }
   static void deleteArray_TRint(void *p) {
      delete [] ((::TRint*)p);
   }
   static void destruct_TRint(void *p) {
      typedef ::TRint current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TRint

//______________________________________________________________________________
void TTabCom::Streamer(TBuffer &R__b)
{
   // Stream an object of class TTabCom.

   ::Error("TTabCom::Streamer", "version id <=0 in ClassDef, dummy Streamer() called"); if (R__b.IsReading()) { }
}

//______________________________________________________________________________
void TTabCom::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TTabCom.

      TClass *R__cl = ::TTabCom::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fpClasses", &fpClasses);
      R__insp.Inspect(R__cl, R__parent, "*fpNamespaces", &fpNamespaces);
      R__insp.Inspect(R__cl, R__parent, "*fpDirectives", &fpDirectives);
      R__insp.Inspect(R__cl, R__parent, "*fpEnvVars", &fpEnvVars);
      R__insp.Inspect(R__cl, R__parent, "*fpFiles", &fpFiles);
      R__insp.Inspect(R__cl, R__parent, "*fpGlobals", &fpGlobals);
      R__insp.Inspect(R__cl, R__parent, "*fpGlobalFuncs", &fpGlobalFuncs);
      R__insp.Inspect(R__cl, R__parent, "*fpPragmas", &fpPragmas);
      R__insp.Inspect(R__cl, R__parent, "*fpSysIncFiles", &fpSysIncFiles);
      R__insp.Inspect(R__cl, R__parent, "*fpUsers", &fpUsers);
      R__insp.Inspect(R__cl, R__parent, "*fBuf", &fBuf);
      R__insp.Inspect(R__cl, R__parent, "*fpLoc", &fpLoc);
      R__insp.Inspect(R__cl, R__parent, "fPat[25][1024]", fPat);
      R__insp.Inspect(R__cl, R__parent, "*fRegExp[25]", &fRegExp);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TTabCom_IsA(const void *obj) {
      return ((::TTabCom*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_TTabCom(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TTabCom : new ::TTabCom;
   }
   static void *newArray_TTabCom(Long_t size) {
      return new ::TTabCom[size];
   }
   // Wrapper around operator delete
   static void delete_TTabCom(void *p) {
      delete ((::TTabCom*)p);
   }
   static void deleteArray_TTabCom(void *p) {
      delete [] ((::TTabCom*)p);
   }
   static void destruct_TTabCom(void *p) {
      typedef ::TTabCom current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TTabCom

/********************************************************
* rint/src/G__Rint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableG__Rint();

extern "C" void G__set_cpp_environmentG__Rint() {
  G__add_compiledheader("base/inc/TROOT.h");
  G__add_compiledheader("base/inc/TMemberInspector.h");
  G__add_compiledheader("rint/inc/TTabCom.h");
  G__add_compiledheader("rint/inc/TRint.h");
  G__cpp_reset_tagtableG__Rint();
}
class G__rintdIsrcdIG__RintdOcxx_tag {};

void* operator new(size_t size,G__rintdIsrcdIG__RintdOcxx_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__rintdIsrcdIG__RintdOcxx_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_rintdIsrcdIG__RintdOcxx() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevG__Rint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TTabCom */
static int G__G__Rint_129_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TTabCom *p=NULL;
   if(G__getaryconstruct()) p=new TTabCom[G__getaryconstruct()];
   else p=::new((G__rintdIsrcdIG__RintdOcxx_tag*)G__getgvp()) TTabCom;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__RintLN_TTabCom);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TTabCom*)(G__getstructoffset()))->Hook((char*)G__int(libp->para[0]),(int*)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfClasses());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfCppDirectives());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfFilesInPath((const char*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfEnvVars());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfGlobalFunctions());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfGlobals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfPragmas());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfSysIncFiles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TTabCom*)(G__getstructoffset()))->GetListOfUsers());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearClasses();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearCppDirectives();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearEnvVars();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearFiles();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearGlobalFunctions();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearGlobals();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearPragmas();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearSysIncFiles();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearUsers();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ClearAll();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashClasses();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashCppDirectives();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashEnvVars();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashFiles();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashGlobalFunctions();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashGlobals();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashPragmas();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashSysIncFiles();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashUsers();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->RehashAll();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,99,(long)TTabCom::AllAgreeOnChar((int)G__int(libp->para[0]),(const TSeqCol*)G__int(libp->para[1])
,*(Int_t*)G__Intref(&libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TTabCom::AppendListOfFilesInDirectory((const char*)G__int(libp->para[0]),(TSeqCol*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        TString *pobj,xobj=TTabCom::DetermineClass((const char*)G__int(libp->para[0]));
        pobj=new TString(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)TTabCom::ExcludedByFignore(*((TString*)G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        TString *pobj,xobj=TTabCom::GetSysIncludePath();
        pobj=new TString(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_7_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)TTabCom::IsDirectory((const char*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_8_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TTabCom::NewListOfFilesInPath((const char*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_9_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)TTabCom::PathIsSpecifiedInFileName(*(TString*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_0_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TTabCom::NoMsg((Int_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_2_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TTabCom::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_3_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TTabCom::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_4_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TTabCom::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_5_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TTabCom::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_6_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TTabCom*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_7_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_8_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_9_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TTabCom*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_0_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TTabCom::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_1_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TTabCom::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_2_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TTabCom::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_129_3_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TTabCom::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TTabCom G__TTTabCom;
static int G__G__Rint_129_4_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TTabCom *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         ((TTabCom *)((G__getstructoffset())+sizeof(TTabCom)*i))->~G__TTTabCom();
   else {
     long G__Xtmp=G__getgvp();
     G__setgvp(G__PVOID);
     ((TTabCom *)(G__getstructoffset()))->~G__TTTabCom();
     G__setgvp(G__Xtmp);
     G__operator_delete((void*)G__getstructoffset());
   }
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TRint */
static int G__G__Rint_172_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TRint *p=NULL;
   switch(libp->paran) {
   case 6:
      p = new TRint(
(const char*)G__int(libp->para[0]),(int*)G__int(libp->para[1])
,(char**)G__int(libp->para[2]),(void*)G__int(libp->para[3])
,(int)G__int(libp->para[4]),(Bool_t)G__int(libp->para[5]));
      break;
   case 5:
      p = new TRint(
(const char*)G__int(libp->para[0]),(int*)G__int(libp->para[1])
,(char**)G__int(libp->para[2]),(void*)G__int(libp->para[3])
,(int)G__int(libp->para[4]));
      break;
   case 4:
      p = new TRint(
(const char*)G__int(libp->para[0]),(int*)G__int(libp->para[1])
,(char**)G__int(libp->para[2]),(void*)G__int(libp->para[3]));
      break;
   case 3:
      p = new TRint(
(const char*)G__int(libp->para[0]),(int*)G__int(libp->para[1])
,(char**)G__int(libp->para[2]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__RintLN_TRint);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((TRint*)(G__getstructoffset()))->GetPrompt());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((TRint*)(G__getstructoffset()))->SetPrompt((const char*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->SetEchoMode((Bool_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((TRint*)(G__getstructoffset()))->HandleTermInput());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->PrintLogo();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->Run((Bool_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->Run();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->Terminate((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->Interrupt();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TRint::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TRint::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TRint::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TRint::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TRint*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TRint*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TRint::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TRint::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TRint::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Rint_172_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TRint::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__Rint_172_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TRint *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TRint(*(TRint*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__G__RintLN_TRint);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TRint G__TTRint;
static int G__G__Rint_172_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TRint *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TRint *)((G__getstructoffset())+sizeof(TRint)*i);
   else  delete (TRint *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__Rint_172_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TRint *dest = (TRint*)(G__getstructoffset());
   *dest = (*(TRint*)libp->para[0].ref);
   const TRint& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TTabCom */

/* TRint */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__Rint {
 public:
  G__Sizep2memfuncG__Rint() {p=&G__Sizep2memfuncG__Rint::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__Rint::*p)();
};

size_t G__get_sizep2memfuncG__Rint()
{
  G__Sizep2memfuncG__Rint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__Rint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__RintLN_TRint))) {
     TRint *G__Lderived;
     G__Lderived=(TRint*)0x1000;
     {
       TApplication *G__Lpbase=(TApplication*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__RintLN_TRint),G__get_linked_tagnum(&G__G__RintLN_TApplication),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__RintLN_TRint),G__get_linked_tagnum(&G__G__RintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__RintLN_TRint),G__get_linked_tagnum(&G__G__RintLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__Rint() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,
-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__G__RintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.42 2005/03/10 17:57:04 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__RintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__RintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.42 2005/03/10 17:57:04 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__RintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__RintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.42 2005/03/10 17:57:04 rdm Exp $",0);
   G__search_typename2("TSeqCol",117,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TContainer",117,G__get_linked_tagnum(&G__G__RintLN_TList),0,G__get_linked_tagnum(&G__G__RintLN_TTabCom));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TContIter",117,G__get_linked_tagnum(&G__G__RintLN_TListIter),0,G__get_linked_tagnum(&G__G__RintLN_TTabCom));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TTabCom */
static void G__setup_memvarTTabCom(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__RintLN_TTabCom));
   { TTabCom *p; p=(TTabCom*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLdA),-1,-2,1,"kDebug=17",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kUNKNOWN_CONTEXT=-1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kSYS_UserName=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kSYS_EnvVar=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_stdout=2",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_stderr=3",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_stdin=4",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_Edit=5",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_Load=6",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_Exec=7",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_EXec=8",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_pragma=9",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_includeSYS=10",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_includePWD=11",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCINT_cpp=12",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kROOT_Load=13",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kSYS_FileName=14",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_ScopeMember=15",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_DirectMember=16",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_IndirectMember=17",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_ScopeProto=18",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_DirectProto=19",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_IndirectProto=20",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_NewProto=21",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_ConstructorProto=22",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_Global=23",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kCXX_GlobalProto=24",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,-2,1,"kNUM_PAT=25",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpClasses=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpNamespaces=",0,"Contains the names of namespaces registered in CINT.");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpDirectives=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpEnvVars=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpFiles=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpGlobals=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpGlobalFuncs=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpPragmas=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpSysIncFiles=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),-1,4,"fpUsers=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,67,0,0,-1,-1,-1,4,"fBuf=",0,"initialized by Hook()");
   G__memvar_setup((void*)NULL,73,0,0,-1,-1,-1,4,"fpLoc=",0,"initialized by Hook()");
   G__memvar_setup((void*)NULL,114,0,0,-1,G__defined_typename("Pattern_t"),-1,4,"fPat[25][1024]=",0,"array of patterns");
   G__memvar_setup((void*)NULL,67,0,1,-1,-1,-1,4,"fRegExp[25]=",0,"corresponding regular expression plain text");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TRint */
static void G__setup_memvarTRint(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__RintLN_TRint));
   { TRint *p; p=(TRint*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNcmd=",0,"command history number");
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__G__RintLN_TString),-1,-1,4,"fDefaultPrompt=",0,"default prompt: \"root [%d] \"");
   G__memvar_setup((void*)NULL,99,0,0,-1,-1,-1,4,"fPrompt[64]=",0,"interpreter prompt");
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fInterrupt=",0,"if true macro execution will be stopped");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TFileHandler),-1,-1,4,"fInputHandler=",0,"terminal input handler");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__Rint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTTabCom(void) {
   /* TTabCom */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__RintLN_TTabCom));
   G__memfunc_setup("TTabCom",650,G__G__Rint_129_1_0,105,G__get_linked_tagnum(&G__G__RintLN_TTabCom),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Hook",401,G__G__Rint_129_2_0,105,-1,G__defined_typename("Int_t"),0,2,1,1,0,
"C - - 0 - buf I - - 0 - pLoc",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfClasses",1599,G__G__Rint_129_3_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfCppDirectives",2214,G__G__Rint_129_4_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfFilesInPath",1960,G__G__Rint_129_5_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,1,1,1,1,"C - - 10 - path",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfEnvVars",1590,G__G__Rint_129_6_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfGlobalFunctions",2427,G__G__Rint_129_7_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfGlobals",1589,G__G__Rint_129_8_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfPragmas",1596,G__G__Rint_129_9_0,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfSysIncFiles",1981,G__G__Rint_129_0_1,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetListOfUsers",1411,G__G__Rint_129_1_1,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearClasses",1205,G__G__Rint_129_2_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearCppDirectives",1820,G__G__Rint_129_3_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearEnvVars",1196,G__G__Rint_129_4_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearFiles",986,G__G__Rint_129_5_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearGlobalFunctions",2033,G__G__Rint_129_6_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearGlobals",1195,G__G__Rint_129_7_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearPragmas",1202,G__G__Rint_129_8_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearSysIncFiles",1587,G__G__Rint_129_9_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearUsers",1017,G__G__Rint_129_0_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearAll",768,G__G__Rint_129_1_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashClasses",1321,G__G__Rint_129_2_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashCppDirectives",1936,G__G__Rint_129_3_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashEnvVars",1312,G__G__Rint_129_4_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashFiles",1102,G__G__Rint_129_5_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashGlobalFunctions",2149,G__G__Rint_129_6_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashGlobals",1311,G__G__Rint_129_7_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashPragmas",1318,G__G__Rint_129_8_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashSysIncFiles",1703,G__G__Rint_129_9_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashUsers",1133,G__G__Rint_129_0_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RehashAll",884,G__G__Rint_129_1_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AllAgreeOnChar",1336,G__G__Rint_129_2_3,99,-1,G__defined_typename("Char_t"),0,3,3,1,0,
"i - - 0 - i U 'TSeqCollection' 'TSeqCol' 10 - pList "
"i - 'Int_t' 1 - nGoodStrings",(char*)NULL,(void*)(Char_t (*)(int,const TSeqCol*,Int_t&))(&TTabCom::AllAgreeOnChar),0);
   G__memfunc_setup("AppendListOfFilesInDirectory",2824,G__G__Rint_129_3_3,121,-1,-1,0,2,3,1,0,
"C - - 10 - dirName U 'TSeqCollection' 'TSeqCol' 0 - pList",(char*)NULL,(void*)(void (*)(const char*,TSeqCol*))(&TTabCom::AppendListOfFilesInDirectory),0);
   G__memfunc_setup("DetermineClass",1427,G__G__Rint_129_4_3,117,G__get_linked_tagnum(&G__G__RintLN_TString),-1,0,1,3,1,0,"C - - 10 - varName","TROOT",(void*)(TString (*)(const char*))(&TTabCom::DetermineClass),0);
   G__memfunc_setup("ExcludedByFignore",1715,G__G__Rint_129_5_3,103,-1,G__defined_typename("Bool_t"),0,1,3,1,0,"u 'TString' - 0 - s",(char*)NULL,(void*)(Bool_t (*)(TString))(&TTabCom::ExcludedByFignore),0);
   G__memfunc_setup("GetSysIncludePath",1712,G__G__Rint_129_6_3,117,G__get_linked_tagnum(&G__G__RintLN_TString),-1,0,0,3,1,0,"","TROOT",(void*)(TString (*)())(&TTabCom::GetSysIncludePath),0);
   G__memfunc_setup("IsDirectory",1137,G__G__Rint_129_7_3,103,-1,G__defined_typename("Bool_t"),0,1,3,1,0,"C - - 10 - fileName","TSystem",(void*)(Bool_t (*)(const char*))(&TTabCom::IsDirectory),0);
   G__memfunc_setup("NewListOfFilesInPath",1970,G__G__Rint_129_8_3,85,G__get_linked_tagnum(&G__G__RintLN_TSeqCollection),G__defined_typename("TSeqCol"),0,1,3,1,0,"C - - 10 - path",(char*)NULL,(void*)(TSeqCol* (*)(const char*))(&TTabCom::NewListOfFilesInPath),0);
   G__memfunc_setup("PathIsSpecifiedInFileName",2445,G__G__Rint_129_9_3,103,-1,G__defined_typename("Bool_t"),0,1,3,1,0,"u 'TString' - 11 - fileName",(char*)NULL,(void*)(Bool_t (*)(const TString&))(&TTabCom::PathIsSpecifiedInFileName),0);
   G__memfunc_setup("NoMsg",484,G__G__Rint_129_0_4,121,-1,-1,0,1,3,1,0,"i - 'Int_t' 0 - errorLevel",(char*)NULL,(void*)(void (*)(Int_t))(&TTabCom::NoMsg),0);
   G__memfunc_setup("TTabCom",650,(G__InterfaceMethod)NULL,105,G__get_linked_tagnum(&G__G__RintLN_TTabCom),-1,0,1,1,4,0,"u 'TTabCom' - 11 - -","private and not implemented",(void*)NULL,0);
   G__memfunc_setup("Complete",825,(G__InterfaceMethod)NULL,105,-1,G__defined_typename("Int_t"),0,3,1,4,0,
"u 'TRegexp' - 11 - re U 'TSeqCollection' 'TSeqCol' 10 - pListOfCandidates "
"C - - 10 - appendage",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CopyMatch",904,(G__InterfaceMethod)NULL,121,-1,-1,0,4,1,4,8,
"C - - 0 - dest C - - 10 - localName "
"C - - 10 0 appendage C - - 10 0 fullName",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DetermineContext",1666,(G__InterfaceMethod)NULL,105,G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t),-1,0,0,1,4,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeterminePath",1322,(G__InterfaceMethod)NULL,117,G__get_linked_tagnum(&G__G__RintLN_TString),-1,0,2,1,4,8,
"u 'TString' - 11 - fileName C - - 10 - defaultPath",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ExtendPath",1013,(G__InterfaceMethod)NULL,117,G__get_linked_tagnum(&G__G__RintLN_TString),-1,0,2,1,4,8,
"C - - 10 - originalPath u 'TString' - 0 - newBase",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("InitPatterns",1253,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeClassFromClassName",2175,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,1,1,4,8,"C - - 10 - className",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TryMakeClassFromClassName",2494,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,1,1,4,8,"C - - 10 - className",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeClassFromVarName",1970,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,2,1,4,0,
"C - - 10 - varName i 'TTabCom::EContext_t' - 1 - context",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetPattern",1034,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"i 'TTabCom::EContext_t' - 0 - handle C - - 10 - regexp",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__G__Rint_129_2_5,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&TTabCom::Class),0);
   G__memfunc_setup("Class_Name",982,G__G__Rint_129_3_5,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TTabCom::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__G__Rint_129_4_5,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&TTabCom::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__G__Rint_129_5_5,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&TTabCom::Dictionary),0);
   G__memfunc_setup("IsA",253,G__G__Rint_129_6_5,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__G__Rint_129_7_5,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__G__Rint_129_8_5,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__Rint_129_9_5,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__G__Rint_129_0_6,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TTabCom::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__G__Rint_129_1_6,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TTabCom::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__G__Rint_129_2_6,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TTabCom::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__G__Rint_129_3_6,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TTabCom::DeclFileLine),0);
   // automatic destructor
   G__memfunc_setup("~TTabCom",776,G__G__Rint_129_4_6,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTRint(void) {
   /* TRint */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__RintLN_TRint));
   G__memfunc_setup("TRint",497,G__G__Rint_172_1_0,105,G__get_linked_tagnum(&G__G__RintLN_TRint),-1,0,6,1,1,0,
"C - - 10 - appClassName I - - 0 - argc "
"C - - 2 - argv Y - - 0 0 options "
"i - - 0 0 numOptions g - 'Bool_t' 0 kFALSE noLogo",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetPrompt",930,G__G__Rint_172_2_0,67,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetPrompt",942,G__G__Rint_172_3_0,67,-1,-1,0,1,1,1,1,"C - - 10 - newPrompt",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetEchoMode",1072,G__G__Rint_172_4_0,121,-1,-1,0,1,1,1,0,"g - 'Bool_t' 0 - mode",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("HandleTermInput",1524,G__G__Rint_172_5_0,103,-1,G__defined_typename("Bool_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("PrintLogo",926,G__G__Rint_172_6_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Run",309,G__G__Rint_172_7_0,121,-1,-1,0,1,1,1,0,"g - 'Bool_t' 0 kFALSE retrn",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Terminate",937,G__G__Rint_172_8_0,121,-1,-1,0,1,1,1,0,"i - - 0 - status",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Interrupt",973,G__G__Rint_172_9_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__G__Rint_172_0_1,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&TRint::Class),0);
   G__memfunc_setup("Class_Name",982,G__G__Rint_172_1_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TRint::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__G__Rint_172_2_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&TRint::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__G__Rint_172_3_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&TRint::Dictionary),0);
   G__memfunc_setup("IsA",253,G__G__Rint_172_4_1,85,G__get_linked_tagnum(&G__G__RintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__G__Rint_172_5_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__G__Rint_172_6_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__Rint_172_7_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__G__Rint_172_8_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TRint::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__G__Rint_172_9_1,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TRint::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__G__Rint_172_0_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TRint::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__G__Rint_172_1_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TRint::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("TRint",497,G__G__Rint_172_2_2,(int)('i'),G__get_linked_tagnum(&G__G__RintLN_TRint),-1,0,1,1,1,0,"u 'TRint' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TRint",623,G__G__Rint_172_3_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__G__Rint_172_4_2,(int)('u'),G__get_linked_tagnum(&G__G__RintLN_TRint),-1,1,1,1,1,0,"u 'TRint' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__Rint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__Rint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__Rint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__RintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__G__RintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__G__RintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TRegexp = { "TRegexp" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TSeqCollection = { "TSeqCollection" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TListIter = { "TListIter" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TApplication = { "TApplication" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TTabCom = { "TTabCom" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TTabComcLcLdA = { "TTabCom::$" , 101 , -1 };
G__linked_taginfo G__G__RintLN_TTabComcLcLEContext_t = { "TTabCom::EContext_t" , 101 , -1 };
G__linked_taginfo G__G__RintLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TFileHandler = { "TFileHandler" , 99 , -1 };
G__linked_taginfo G__G__RintLN_TRint = { "TRint" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__Rint() {
  G__G__RintLN_TClass.tagnum = -1 ;
  G__G__RintLN_TBuffer.tagnum = -1 ;
  G__G__RintLN_TMemberInspector.tagnum = -1 ;
  G__G__RintLN_TObject.tagnum = -1 ;
  G__G__RintLN_TList.tagnum = -1 ;
  G__G__RintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__G__RintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__RintLN_TRegexp.tagnum = -1 ;
  G__G__RintLN_TString.tagnum = -1 ;
  G__G__RintLN_TSeqCollection.tagnum = -1 ;
  G__G__RintLN_TListIter.tagnum = -1 ;
  G__G__RintLN_TApplication.tagnum = -1 ;
  G__G__RintLN_TTabCom.tagnum = -1 ;
  G__G__RintLN_TTabComcLcLdA.tagnum = -1 ;
  G__G__RintLN_TTabComcLcLEContext_t.tagnum = -1 ;
  G__G__RintLN_TQObject.tagnum = -1 ;
  G__G__RintLN_TFileHandler.tagnum = -1 ;
  G__G__RintLN_TRint.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__Rint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__G__RintLN_TClass);
   G__get_linked_tagnum(&G__G__RintLN_TBuffer);
   G__get_linked_tagnum(&G__G__RintLN_TMemberInspector);
   G__get_linked_tagnum(&G__G__RintLN_TObject);
   G__get_linked_tagnum(&G__G__RintLN_TList);
   G__get_linked_tagnum(&G__G__RintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__G__RintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__G__RintLN_TRegexp);
   G__get_linked_tagnum(&G__G__RintLN_TString);
   G__get_linked_tagnum(&G__G__RintLN_TSeqCollection);
   G__get_linked_tagnum(&G__G__RintLN_TListIter);
   G__get_linked_tagnum(&G__G__RintLN_TApplication);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__RintLN_TTabCom),sizeof(TTabCom),-1,1792,"Perform comand line completion when hitting <TAB>",G__setup_memvarTTabCom,G__setup_memfuncTTabCom);
   G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLdA);
   G__get_linked_tagnum(&G__G__RintLN_TTabComcLcLEContext_t);
   G__get_linked_tagnum(&G__G__RintLN_TQObject);
   G__get_linked_tagnum(&G__G__RintLN_TFileHandler);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__RintLN_TRint),sizeof(TRint),-1,62464,"ROOT Interactive Application Interface",G__setup_memvarTRint,G__setup_memfuncTRint);
}
extern "C" void G__cpp_setupG__Rint(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__Rint()");
  G__set_cpp_environmentG__Rint();
  G__cpp_setup_tagtableG__Rint();

  G__cpp_setup_inheritanceG__Rint();

  G__cpp_setup_typetableG__Rint();

  G__cpp_setup_memvarG__Rint();

  G__cpp_setup_memfuncG__Rint();
  G__cpp_setup_globalG__Rint();
  G__cpp_setup_funcG__Rint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__Rint();
  return;
}
class G__cpp_setup_initG__Rint {
  public:
    G__cpp_setup_initG__Rint() { G__add_setup_func("G__Rint",(G__incsetup)(&G__cpp_setupG__Rint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__Rint() { G__remove_setup_func("G__Rint"); }
};
G__cpp_setup_initG__Rint G__cpp_setup_initializerG__Rint;

