
/* Includes added by #pragma extra_include */
#include "vector"
#include "string"
/********************************************************************
* base/src/G__Base2.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error base/src/G__Base2.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Base2();
extern void G__cpp_setup_inheritanceG__Base2();
extern void G__cpp_setup_typetableG__Base2();
extern void G__cpp_setup_memvarG__Base2();
extern void G__cpp_setup_globalG__Base2();
extern void G__cpp_setup_memfuncG__Base2();
extern void G__cpp_setup_funcG__Base2();
extern void G__set_cpp_environmentG__Base2();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "base/inc/TSystem.h"
#include "base/inc/TComplex.h"
#include "base/inc/TBuffer3DTypes.h"
#include "base/inc/TView.h"
#include "base/inc/TROOT.h"
#include "base/inc/TDirectory.h"
#include "base/inc/TStringLong.h"
#include "base/inc/TPoint.h"
#include "base/inc/TException.h"
#include "base/inc/TAttAxis.h"
#include "base/inc/TMemberInspector.h"
#include "base/inc/TQConnection.h"
#include "base/inc/TAttPad.h"
#include "base/inc/TVirtualPS.h"
#include "base/inc/TError.h"
#include "base/inc/TRefCnt.h"
#include "base/inc/TNamed.h"
#include "base/inc/TVirtualGL.h"
#include "base/inc/TAttMarker.h"
#include "base/inc/TCanvasImp.h"
#include "base/inc/TVirtualViewer3D.h"
#include "base/inc/TKey.h"
#include "base/inc/TEnv.h"
#include "base/inc/TVirtualUtilPad.h"
#include "base/inc/TContextMenu.h"
#include "base/inc/TPadView3D.h"
#include "base/inc/TFree.h"
#include "base/inc/TMD5.h"
#include "base/inc/TProcessID.h"
#include "base/inc/TContextMenuImp.h"
#include "base/inc/TBrowserImp.h"
#include "base/inc/TTask.h"
#include "base/inc/TRandom3.h"
#include "base/inc/TSysEvtHandler.h"
#include "base/inc/TExec.h"
#include "base/inc/TQCommand.h"
#include "base/inc/TVirtualPad.h"
#include "base/inc/TApplicationImp.h"
#include "base/inc/TSystemDirectory.h"
#include "base/inc/TStopwatch.h"
#include "base/inc/TKeyMapFile.h"
#include "base/inc/TSystemFile.h"
#include "base/inc/TObject.h"
#include "base/inc/TStorage.h"
#include "base/inc/TMessageHandler.h"
#include "base/inc/TRegexp.h"
#include "base/inc/TAtt3D.h"
#include "base/inc/TPluginManager.h"
#include "base/inc/TProcessUUID.h"
#include "base/inc/TString.h"
#include "base/inc/TAttLine.h"
#include "base/inc/TRef.h"
#include "base/inc/TUUID.h"
#include "base/inc/TFolder.h"
#include "base/inc/TMath.h"
#include "base/inc/TBuffer.h"
#include "base/inc/TGuiFactory.h"
#include "base/inc/TRandom.h"
#include "base/inc/TRealData.h"
#include "base/inc/TVirtualUtil3D.h"
#include "base/inc/TObjString.h"
#include "base/inc/TRandom2.h"
#include "base/inc/TBrowser.h"
#include "base/inc/TVirtualFitter.h"
#include "base/inc/TFile.h"
#include "base/inc/TQObject.h"
#include "base/inc/TMapFile.h"
#include "base/inc/TDatime.h"
#include "base/inc/TApplication.h"
#include "base/inc/TVirtualUtilHist.h"
#include "base/inc/TControlBarImp.h"
#include "base/inc/TTimer.h"
#include "base/inc/TAttText.h"
#include "base/inc/TVirtualPadEditor.h"
#include "base/inc/TInspectorImp.h"
#include "base/inc/TAttFill.h"
#include "base/inc/TTime.h"
#include "base/inc/TBenchmark.h"
#include "base/inc/TColor.h"
#include "base/inc/TBuffer3D.h"
#include "base/inc/TStyle.h"

#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Base2LN_type_info;
extern G__linked_taginfo G__G__Base2LN_TClass;
extern G__linked_taginfo G__G__Base2LN_TBuffer;
extern G__linked_taginfo G__G__Base2LN_TMemberInspector;
extern G__linked_taginfo G__G__Base2LN_TObject;
extern G__linked_taginfo G__G__Base2LN_TNamed;
extern G__linked_taginfo G__G__Base2LN_TMemberStreamer;
extern G__linked_taginfo G__G__Base2LN_ROOT;
extern G__linked_taginfo G__G__Base2LN_va_list;
extern G__linked_taginfo G__G__Base2LN_TStorage;
extern G__linked_taginfo G__G__Base2LN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base2LN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base2LN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base2LN_string;
extern G__linked_taginfo G__G__Base2LN_TList;
extern G__linked_taginfo G__G__Base2LN_TBrowser;
extern G__linked_taginfo G__G__Base2LN_TObjArray;
extern G__linked_taginfo G__G__Base2LN_TMethod;
extern G__linked_taginfo G__G__Base2LN_TTimer;
extern G__linked_taginfo G__G__Base2LN_TObjectcLcLdA;
extern G__linked_taginfo G__G__Base2LN_TStreamerInfo;
extern G__linked_taginfo G__G__Base2LN_TExMap;
extern G__linked_taginfo G__G__Base2LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_TCollection;
extern G__linked_taginfo G__G__Base2LN_TMath;
extern G__linked_taginfo G__G__Base2LN_TRefCnt;
extern G__linked_taginfo G__G__Base2LN_TRefCntcLcLEReferenceFlag;
extern G__linked_taginfo G__G__Base2LN_stringcLcLiterator;
extern G__linked_taginfo G__G__Base2LN_stringcLcLdA;
extern G__linked_taginfo G__G__Base2LN_TRegexp;
extern G__linked_taginfo G__G__Base2LN_TString;
extern G__linked_taginfo G__G__Base2LN_TSubString;
extern G__linked_taginfo G__G__Base2LN_TStringRef;
extern G__linked_taginfo G__G__Base2LN_TStringLong;
extern G__linked_taginfo G__G__Base2LN_TStringcLcLEStripType;
extern G__linked_taginfo G__G__Base2LN_TStringcLcLECaseCompare;
extern G__linked_taginfo G__G__Base2LN_TSeqCollection;
extern G__linked_taginfo G__G__Base2LN_TObjLink;
extern G__linked_taginfo G__G__Base2LN_TDatime;
extern G__linked_taginfo G__G__Base2LN_TFile;
extern G__linked_taginfo G__G__Base2LN_TDirectory;
extern G__linked_taginfo G__G__Base2LN_TInetAddress;
extern G__linked_taginfo G__G__Base2LN_TUUID;
extern G__linked_taginfo G__G__Base2LN_TUUIDcLcLuuid_time_t;
extern G__linked_taginfo G__G__Base2LN_TKey;
extern G__linked_taginfo G__G__Base2LN_TColor;
extern G__linked_taginfo G__G__Base2LN_TDataType;
extern G__linked_taginfo G__G__Base2LN_TStyle;
extern G__linked_taginfo G__G__Base2LN_TVirtualPad;
extern G__linked_taginfo G__G__Base2LN_TVirtualProof;
extern G__linked_taginfo G__G__Base2LN_TApplication;
extern G__linked_taginfo G__G__Base2LN_TInterpreter;
extern G__linked_taginfo G__G__Base2LN_TGlobal;
extern G__linked_taginfo G__G__Base2LN_TFunction;
extern G__linked_taginfo G__G__Base2LN_TFolder;
extern G__linked_taginfo G__G__Base2LN_TPluginManager;
extern G__linked_taginfo G__G__Base2LN_TProcessUUID;
extern G__linked_taginfo G__G__Base2LN_TClassGenerator;
extern G__linked_taginfo G__G__Base2LN_ROOTcLcLTMapTypeToTClass;
extern G__linked_taginfo G__G__Base2LN_TROOT;
extern G__linked_taginfo G__G__Base2LN_TSystem;
extern G__linked_taginfo G__G__Base2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_TDictionary;
extern G__linked_taginfo G__G__Base2LN_THashList;
extern G__linked_taginfo G__G__Base2LN_TFree;
extern G__linked_taginfo G__G__Base2LN_TDataMember;
extern G__linked_taginfo G__G__Base2LN_TRealData;
extern G__linked_taginfo G__G__Base2LN_TMethodCall;
extern G__linked_taginfo G__G__Base2LN_TQConnection;
extern G__linked_taginfo G__G__Base2LN_TQClass;
extern G__linked_taginfo G__G__Base2LN_TQObject;
extern G__linked_taginfo G__G__Base2LN_TQObjSender;
extern G__linked_taginfo G__G__Base2LN_TSysEvtHandler;
extern G__linked_taginfo G__G__Base2LN_TFileHandler;
extern G__linked_taginfo G__G__Base2LN_ESignals;
extern G__linked_taginfo G__G__Base2LN_TSignalHandler;
extern G__linked_taginfo G__G__Base2LN_TTime;
extern G__linked_taginfo G__G__Base2LN_TFdSet;
extern G__linked_taginfo G__G__Base2LN_EAccessMode;
extern G__linked_taginfo G__G__Base2LN_ELogLevel;
extern G__linked_taginfo G__G__Base2LN_ELogFacility;
extern G__linked_taginfo G__G__Base2LN_ESysConstants;
extern G__linked_taginfo G__G__Base2LN_EFpeMask;
extern G__linked_taginfo G__G__Base2LN_EFileModeMask;
extern G__linked_taginfo G__G__Base2LN_FileStat_t;
extern G__linked_taginfo G__G__Base2LN_UserGroup_t;
extern G__linked_taginfo G__G__Base2LN_TProcessEventTimer;
extern G__linked_taginfo G__G__Base2LN_TSystemcLcLEAclicMode;
extern G__linked_taginfo G__G__Base2LN_TComplex;
extern G__linked_taginfo G__G__Base2LN_TPoint;
extern G__linked_taginfo G__G__Base2LN_TQSlot;
extern G__linked_taginfo G__G__Base2LN_TOrdCollection;
extern G__linked_taginfo G__G__Base2LN_TEnv;
extern G__linked_taginfo G__G__Base2LN_TMD5;
extern G__linked_taginfo G__G__Base2LN_TProcessID;
extern G__linked_taginfo G__G__Base2LN_TTask;
extern G__linked_taginfo G__G__Base2LN_TRandom;
extern G__linked_taginfo G__G__Base2LN_TRandom3;
extern G__linked_taginfo G__G__Base2LN_TExec;
extern G__linked_taginfo G__G__Base2LN_TQCommand;
extern G__linked_taginfo G__G__Base2LN_TQUndoManager;
extern G__linked_taginfo G__G__Base2LN_TSystemFile;
extern G__linked_taginfo G__G__Base2LN_TSystemDirectory;
extern G__linked_taginfo G__G__Base2LN_TStopwatch;
extern G__linked_taginfo G__G__Base2LN_TStopwatchcLcLEState;
extern G__linked_taginfo G__G__Base2LN_TMapFile;
extern G__linked_taginfo G__G__Base2LN_TKeyMapFile;
extern G__linked_taginfo G__G__Base2LN_TMessageHandler;
extern G__linked_taginfo G__G__Base2LN_TRegexpcLcLEStatVal;
extern G__linked_taginfo G__G__Base2LN_TPluginHandler;
extern G__linked_taginfo G__G__Base2LN_TBits;
extern G__linked_taginfo G__G__Base2LN_TObjString;
extern G__linked_taginfo G__G__Base2LN_TRef;
extern G__linked_taginfo G__G__Base2LN_TRefcLcLdA;
extern G__linked_taginfo G__G__Base2LN_TRandom2;
extern G__linked_taginfo G__G__Base2LN_TMapRec;
extern G__linked_taginfo G__G__Base2LN_TMapFilecLcLdA;
extern G__linked_taginfo G__G__Base2LN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__Base2LN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<string,allocator<string> > G__vectorlEstringcOallocatorlEstringgRsPgR;
