/********************************************************************
* base/src/G__Base1.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error base/src/G__Base1.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Base1();
extern void G__cpp_setup_inheritanceG__Base1();
extern void G__cpp_setup_typetableG__Base1();
extern void G__cpp_setup_memvarG__Base1();
extern void G__cpp_setup_globalG__Base1();
extern void G__cpp_setup_memfuncG__Base1();
extern void G__cpp_setup_funcG__Base1();
extern void G__set_cpp_environmentG__Base1();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "base/inc/TSystem.h"
#include "base/inc/TComplex.h"
#include "base/inc/TBuffer3DTypes.h"
#include "base/inc/TView.h"
#include "base/inc/TROOT.h"
#include "base/inc/TDirectory.h"
#include "base/inc/TStringLong.h"
#include "base/inc/TPoint.h"
#include "base/inc/TException.h"
#include "base/inc/TAttAxis.h"
#include "base/inc/TMemberInspector.h"
#include "base/inc/TQConnection.h"
#include "base/inc/TAttPad.h"
#include "base/inc/TVirtualPS.h"
#include "base/inc/TError.h"
#include "base/inc/TRefCnt.h"
#include "base/inc/TNamed.h"
#include "base/inc/TVirtualGL.h"
#include "base/inc/TAttMarker.h"
#include "base/inc/TCanvasImp.h"
#include "base/inc/TVirtualViewer3D.h"
#include "base/inc/TKey.h"
#include "base/inc/TEnv.h"
#include "base/inc/TVirtualUtilPad.h"
#include "base/inc/TContextMenu.h"
#include "base/inc/TPadView3D.h"
#include "base/inc/TFree.h"
#include "base/inc/TMD5.h"
#include "base/inc/TProcessID.h"
#include "base/inc/TContextMenuImp.h"
#include "base/inc/TBrowserImp.h"
#include "base/inc/TTask.h"
#include "base/inc/TRandom3.h"
#include "base/inc/TSysEvtHandler.h"
#include "base/inc/TExec.h"
#include "base/inc/TQCommand.h"
#include "base/inc/TVirtualPad.h"
#include "base/inc/TApplicationImp.h"
#include "base/inc/TSystemDirectory.h"
#include "base/inc/TStopwatch.h"
#include "base/inc/TKeyMapFile.h"
#include "base/inc/TSystemFile.h"
#include "base/inc/TObject.h"
#include "base/inc/TStorage.h"
#include "base/inc/TMessageHandler.h"
#include "base/inc/TRegexp.h"
#include "base/inc/TAtt3D.h"
#include "base/inc/TPluginManager.h"
#include "base/inc/TProcessUUID.h"
#include "base/inc/TString.h"
#include "base/inc/TAttLine.h"
#include "base/inc/TRef.h"
#include "base/inc/TUUID.h"
#include "base/inc/TFolder.h"
#include "base/inc/TMath.h"
#include "base/inc/TBuffer.h"
#include "base/inc/TGuiFactory.h"
#include "base/inc/TRandom.h"
#include "base/inc/TRealData.h"
#include "base/inc/TVirtualUtil3D.h"
#include "base/inc/TObjString.h"
#include "base/inc/TRandom2.h"
#include "base/inc/TBrowser.h"
#include "base/inc/TVirtualFitter.h"
#include "base/inc/TFile.h"
#include "base/inc/TQObject.h"
#include "base/inc/TMapFile.h"
#include "base/inc/TDatime.h"
#include "base/inc/TApplication.h"
#include "base/inc/TVirtualUtilHist.h"
#include "base/inc/TControlBarImp.h"
#include "base/inc/TTimer.h"
#include "base/inc/TAttText.h"
#include "base/inc/TVirtualPadEditor.h"
#include "base/inc/TInspectorImp.h"
#include "base/inc/TAttFill.h"
#include "base/inc/TTime.h"
#include "base/inc/TBenchmark.h"
#include "base/inc/TColor.h"
#include "base/inc/TBuffer3D.h"
#include "base/inc/TStyle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Base1LN_type_info;
extern G__linked_taginfo G__G__Base1LN_TClass;
extern G__linked_taginfo G__G__Base1LN_TBuffer;
extern G__linked_taginfo G__G__Base1LN_TMemberInspector;
extern G__linked_taginfo G__G__Base1LN_TObject;
extern G__linked_taginfo G__G__Base1LN_TNamed;
extern G__linked_taginfo G__G__Base1LN_TMemberStreamer;
extern G__linked_taginfo G__G__Base1LN_ROOT;
extern G__linked_taginfo G__G__Base1LN_ROOTcLcLTInitBehavior;
extern G__linked_taginfo G__G__Base1LN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base1LN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base1LN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base1LN_TList;
extern G__linked_taginfo G__G__Base1LN_TBrowser;
extern G__linked_taginfo G__G__Base1LN_TObjArray;
extern G__linked_taginfo G__G__Base1LN_TMethod;
extern G__linked_taginfo G__G__Base1LN_TTimer;
extern G__linked_taginfo G__G__Base1LN_EObjBits;
extern G__linked_taginfo G__G__Base1LN_TStreamerInfo;
extern G__linked_taginfo G__G__Base1LN_TStreamerElement;
extern G__linked_taginfo G__G__Base1LN_TExMap;
extern G__linked_taginfo G__G__Base1LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__Base1LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base1LN_TBuffercLcLEMode;
extern G__linked_taginfo G__G__Base1LN_TBuffercLcLdA;
extern G__linked_taginfo G__G__Base1LN_TString;
extern G__linked_taginfo G__G__Base1LN_TSeqCollection;
extern G__linked_taginfo G__G__Base1LN_TDatime;
extern G__linked_taginfo G__G__Base1LN_TFile;
extern G__linked_taginfo G__G__Base1LN_TDirectory;
extern G__linked_taginfo G__G__Base1LN_TUUID;
extern G__linked_taginfo G__G__Base1LN_TKey;
extern G__linked_taginfo G__G__Base1LN_TDirectorycLcLdA;
extern G__linked_taginfo G__G__Base1LN_TColor;
extern G__linked_taginfo G__G__Base1LN_TStyle;
extern G__linked_taginfo G__G__Base1LN_TVirtualPad;
extern G__linked_taginfo G__G__Base1LN_TApplication;
extern G__linked_taginfo G__G__Base1LN_TFunction;
extern G__linked_taginfo G__G__Base1LN_TROOT;
extern G__linked_taginfo G__G__Base1LN_TSystem;
extern G__linked_taginfo G__G__Base1LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__Base1LN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base1LN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__Base1LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base1LN_TCache;
extern G__linked_taginfo G__G__Base1LN_TArrayC;
extern G__linked_taginfo G__G__Base1LN_TArchiveFile;
extern G__linked_taginfo G__G__Base1LN_TFilecLcLdA;
extern G__linked_taginfo G__G__Base1LN_TFilecLcLERelativeTo;
extern G__linked_taginfo G__G__Base1LN_TMethodCall;
extern G__linked_taginfo G__G__Base1LN_TQObject;
extern G__linked_taginfo G__G__Base1LN_ROOTcLcLTQObjectInitBehavior;
extern G__linked_taginfo G__G__Base1LN_TSysEvtHandler;
extern G__linked_taginfo G__G__Base1LN_TFileHandler;
extern G__linked_taginfo G__G__Base1LN_TFileHandlercLcLdA;
extern G__linked_taginfo G__G__Base1LN_TSignalHandler;
extern G__linked_taginfo G__G__Base1LN_TAttLine;
extern G__linked_taginfo G__G__Base1LN_TView;
extern G__linked_taginfo G__G__Base1LN_TViewcLcLdA;
extern G__linked_taginfo G__G__Base1LN_TPoint;
extern G__linked_taginfo G__G__Base1LN_TAttAxis;
extern G__linked_taginfo G__G__Base1LN_TAttPad;
extern G__linked_taginfo G__G__Base1LN_TAttFill;
extern G__linked_taginfo G__G__Base1LN_TAttText;
extern G__linked_taginfo G__G__Base1LN_TAttMarker;
extern G__linked_taginfo G__G__Base1LN_TVirtualPS;
extern G__linked_taginfo G__G__Base1LN_EGEventType;
extern G__linked_taginfo G__G__Base1LN_SetWindowAttributes_t;
extern G__linked_taginfo G__G__Base1LN_WindowAttributes_t;
extern G__linked_taginfo G__G__Base1LN_Event_t;
extern G__linked_taginfo G__G__Base1LN_EMouseButton;
extern G__linked_taginfo G__G__Base1LN_GCValues_t;
extern G__linked_taginfo G__G__Base1LN_ColorStruct_t;
extern G__linked_taginfo G__G__Base1LN_PictureAttributes_t;
extern G__linked_taginfo G__G__Base1LN_EInitialState;
extern G__linked_taginfo G__G__Base1LN_Segment_t;
extern G__linked_taginfo G__G__Base1LN_Point_t;
extern G__linked_taginfo G__G__Base1LN_Rectangle_t;
extern G__linked_taginfo G__G__Base1LN_EG3D2GLmode;
extern G__linked_taginfo G__G__Base1LN_TGLSceneObject;
extern G__linked_taginfo G__G__Base1LN_TPoints3DABC;
extern G__linked_taginfo G__G__Base1LN_TGLRender;
extern G__linked_taginfo G__G__Base1LN_TGLWindow;
extern G__linked_taginfo G__G__Base1LN_TVirtualGLImp;
extern G__linked_taginfo G__G__Base1LN_TVirtualGL;
extern G__linked_taginfo G__G__Base1LN_TCanvas;
extern G__linked_taginfo G__G__Base1LN_TCanvasImp;
extern G__linked_taginfo G__G__Base1LN_TBuffer3D;
extern G__linked_taginfo G__G__Base1LN_TVirtualViewer3D;
extern G__linked_taginfo G__G__Base1LN_TOrdCollection;
extern G__linked_taginfo G__G__Base1LN_TEnv;
extern G__linked_taginfo G__G__Base1LN_EEnvLevel;
extern G__linked_taginfo G__G__Base1LN_TEnvRec;
extern G__linked_taginfo G__G__Base1LN_TVirtualUtilPad;
extern G__linked_taginfo G__G__Base1LN_TContextMenu;
extern G__linked_taginfo G__G__Base1LN_TContextMenuImp;
extern G__linked_taginfo G__G__Base1LN_TMethodArg;
extern G__linked_taginfo G__G__Base1LN_TToggle;
extern G__linked_taginfo G__G__Base1LN_TClassMenuItem;
extern G__linked_taginfo G__G__Base1LN_TPolyMarker3D;
extern G__linked_taginfo G__G__Base1LN_TPolyLine3D;
extern G__linked_taginfo G__G__Base1LN_TNode;
extern G__linked_taginfo G__G__Base1LN_TRotMatrix;
extern G__linked_taginfo G__G__Base1LN_TPadView3D;
extern G__linked_taginfo G__G__Base1LN_TBrowserImp;
extern G__linked_taginfo G__G__Base1LN_TRandom;
extern G__linked_taginfo G__G__Base1LN_ECursor;
extern G__linked_taginfo G__G__Base1LN_TGWin32Command;
extern G__linked_taginfo G__G__Base1LN_TVirtualX;
extern G__linked_taginfo G__G__Base1LN_TVirtualXcLcLEDrawMode;
extern G__linked_taginfo G__G__Base1LN_TVirtualXcLcLEBoxMode;
extern G__linked_taginfo G__G__Base1LN_TVirtualXcLcLETextMode;
extern G__linked_taginfo G__G__Base1LN_TVirtualXcLcLETextSetMode;
extern G__linked_taginfo G__G__Base1LN_TH1F;
extern G__linked_taginfo G__G__Base1LN_TFrame;
extern G__linked_taginfo G__G__Base1LN_TBox;
extern G__linked_taginfo G__G__Base1LN_TApplicationImp;
extern G__linked_taginfo G__G__Base1LN_TStopwatch;
extern G__linked_taginfo G__G__Base1LN_TAtt3D;
extern G__linked_taginfo G__G__Base1LN_TControlBarImp;
extern G__linked_taginfo G__G__Base1LN_TControlBar;
extern G__linked_taginfo G__G__Base1LN_TInspectorImp;
extern G__linked_taginfo G__G__Base1LN_TGuiFactory;
extern G__linked_taginfo G__G__Base1LN_TVirtualUtil3D;
extern G__linked_taginfo G__G__Base1LN_TBrowserTimer;
extern G__linked_taginfo G__G__Base1LN_TBrowsercLcLdA;
extern G__linked_taginfo G__G__Base1LN_Foption_t;
extern G__linked_taginfo G__G__Base1LN_TVirtualFitter;
extern G__linked_taginfo G__G__Base1LN_TMatrixFBase;
extern G__linked_taginfo G__G__Base1LN_TMatrixDBase;
extern G__linked_taginfo G__G__Base1LN_TVectorF;
extern G__linked_taginfo G__G__Base1LN_TVectorD;
extern G__linked_taginfo G__G__Base1LN_TVirtualUtilHist;
extern G__linked_taginfo G__G__Base1LN_TControlBarButton;
extern G__linked_taginfo G__G__Base1LN_TVirtualPadEditor;
extern G__linked_taginfo G__G__Base1LN_TBenchmark;
extern G__linked_taginfo G__G__Base1LN_TBuffer3DcLcLEBoolOpCode;
extern G__linked_taginfo G__G__Base1LN_TBuffer3DcLcLESection;
extern G__linked_taginfo G__G__Base1LN_TArrayI;
extern G__linked_taginfo G__G__Base1LN_TStylecLcLEPaperSize;

/* STUB derived class for protected member access */
