/********************************************************************
* html/src/G__Html.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error html/src/G__Html.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Html();
extern void G__cpp_setup_inheritanceG__Html();
extern void G__cpp_setup_typetableG__Html();
extern void G__cpp_setup_memvarG__Html();
extern void G__cpp_setup_globalG__Html();
extern void G__cpp_setup_memfuncG__Html();
extern void G__cpp_setup_funcG__Html();
extern void G__set_cpp_environmentG__Html();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "html/inc/THtml.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__HtmlLN_TClass;
extern G__linked_taginfo G__G__HtmlLN_TBuffer;
extern G__linked_taginfo G__G__HtmlLN_TMemberInspector;
extern G__linked_taginfo G__G__HtmlLN_TObject;
extern G__linked_taginfo G__G__HtmlLN_TNamed;
extern G__linked_taginfo G__G__HtmlLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__HtmlLN_TList;
extern G__linked_taginfo G__G__HtmlLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__HtmlLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__HtmlLN_TString;
extern G__linked_taginfo G__G__HtmlLN_TVirtualPad;
extern G__linked_taginfo G__G__HtmlLN_TDictionary;
extern G__linked_taginfo G__G__HtmlLN_TMap;
extern G__linked_taginfo G__G__HtmlLN_THashList;
extern G__linked_taginfo G__G__HtmlLN_TPaveText;
extern G__linked_taginfo G__G__HtmlLN_THtml;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTDocElement;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTLocalType;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTLocalTypecLcLESpec;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTParseStack;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTParseStackcLcLEContext;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTParseStackcLcLEBlockSpec;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLTParseStackcLcLTParseElement;
extern G__linked_taginfo G__G__HtmlLN_THtmlcLcLETraverse;

/* STUB derived class for protected member access */
