/********************************************************************
* ldap/src/G__LDAP.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ldap/src/G__LDAP.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__LDAP();
extern void G__cpp_setup_inheritanceG__LDAP();
extern void G__cpp_setup_typetableG__LDAP();
extern void G__cpp_setup_memvarG__LDAP();
extern void G__cpp_setup_globalG__LDAP();
extern void G__cpp_setup_memfuncG__LDAP();
extern void G__cpp_setup_funcG__LDAP();
extern void G__set_cpp_environmentG__LDAP();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "ldap/inc/TLDAPAttribute.h"
#include "ldap/inc/TLDAPServer.h"
#include "ldap/inc/CintLDAP.h"
#include "ldap/inc/TLDAPResult.h"
#include "ldap/inc/TLDAPEntry.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__LDAPLN_TClass;
extern G__linked_taginfo G__G__LDAPLN_TBuffer;
extern G__linked_taginfo G__G__LDAPLN_TMemberInspector;
extern G__linked_taginfo G__G__LDAPLN_TObject;
extern G__linked_taginfo G__G__LDAPLN_TNamed;
extern G__linked_taginfo G__G__LDAPLN_TList;
extern G__linked_taginfo G__G__LDAPLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__LDAPLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__LDAPLN_TString;
extern G__linked_taginfo G__G__LDAPLN_LDAP;
extern G__linked_taginfo G__G__LDAPLN_LDAPMessage;
extern G__linked_taginfo G__G__LDAPLN_LDAPMod;
extern G__linked_taginfo G__G__LDAPLN_TLDAPEntry;
extern G__linked_taginfo G__G__LDAPLN_TLDAPAttribute;
extern G__linked_taginfo G__G__LDAPLN_TLDAPResult;
extern G__linked_taginfo G__G__LDAPLN_TLDAPServer;

/* STUB derived class for protected member access */
