/********************************************************************
* qt/src/G__GQt.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error qt/src/G__GQt.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__GQt();
extern void G__cpp_setup_inheritanceG__GQt();
extern void G__cpp_setup_typetableG__GQt();
extern void G__cpp_setup_memvarG__GQt();
extern void G__cpp_setup_globalG__GQt();
extern void G__cpp_setup_memfuncG__GQt();
extern void G__cpp_setup_funcG__GQt();
extern void G__set_cpp_environmentG__GQt();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "qt/inc/TGQt.h"
#include "qt/inc/TQtThread.h"
#include "qt/inc/TQtApplication.h"
#include "qt/inc/TQtBrush.h"
#include "qt/inc/TQMimeTypes.h"
#include "qt/inc/TQtClientFilter.h"
#include "qt/inc/TQtClientWidget.h"
#include "qt/inc/TQtWidget.h"
#include "qt/inc/TQtMarker.h"
#include "qt/inc/TQtTimer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GQtLN_TClass;
extern G__linked_taginfo G__G__GQtLN_TBuffer;
extern G__linked_taginfo G__G__GQtLN_TMemberInspector;
extern G__linked_taginfo G__G__GQtLN_TObject;
extern G__linked_taginfo G__G__GQtLN_TNamed;
extern G__linked_taginfo G__G__GQtLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__GQtLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GQtLN_TString;
extern G__linked_taginfo G__G__GQtLN_TVirtualPad;
extern G__linked_taginfo G__G__GQtLN_QObject;
extern G__linked_taginfo G__G__GQtLN_QEvent;
extern G__linked_taginfo G__G__GQtLN_QPaintDevice;
extern G__linked_taginfo G__G__GQtLN_TAttLine;
extern G__linked_taginfo G__G__GQtLN_TAttFill;
extern G__linked_taginfo G__G__GQtLN_TAttText;
extern G__linked_taginfo G__G__GQtLN_TAttMarker;
extern G__linked_taginfo G__G__GQtLN_EGEventType;
extern G__linked_taginfo G__G__GQtLN_SetWindowAttributes_t;
extern G__linked_taginfo G__G__GQtLN_WindowAttributes_t;
extern G__linked_taginfo G__G__GQtLN_Event_t;
extern G__linked_taginfo G__G__GQtLN_EMouseButton;
extern G__linked_taginfo G__G__GQtLN_GCValues_t;
extern G__linked_taginfo G__G__GQtLN_ColorStruct_t;
extern G__linked_taginfo G__G__GQtLN_PictureAttributes_t;
extern G__linked_taginfo G__G__GQtLN_EInitialState;
extern G__linked_taginfo G__G__GQtLN_Segment_t;
extern G__linked_taginfo G__G__GQtLN_Point_t;
extern G__linked_taginfo G__G__GQtLN_Rectangle_t;
extern G__linked_taginfo G__G__GQtLN_ECursor;
extern G__linked_taginfo G__G__GQtLN_TPoint;
extern G__linked_taginfo G__G__GQtLN_TGWin32Command;
extern G__linked_taginfo G__G__GQtLN_TVirtualX;
extern G__linked_taginfo G__G__GQtLN_TVirtualXcLcLEDrawMode;
extern G__linked_taginfo G__G__GQtLN_TVirtualXcLcLEBoxMode;
extern G__linked_taginfo G__G__GQtLN_TVirtualXcLcLETextMode;
extern G__linked_taginfo G__G__GQtLN_TVirtualXcLcLETextSetMode;
extern G__linked_taginfo G__G__GQtLN_TQtMarker;
extern G__linked_taginfo G__G__GQtLN_TQtBrush;
extern G__linked_taginfo G__G__GQtLN_TQtApplication;
extern G__linked_taginfo G__G__GQtLN_TQtClientFilter;
extern G__linked_taginfo G__G__GQtLN_TQtEventQueue;
extern G__linked_taginfo G__G__GQtLN_TGQt;
extern G__linked_taginfo G__G__GQtLN_TQtThread;
extern G__linked_taginfo G__G__GQtLN_TQtApplicationThread;
extern G__linked_taginfo G__G__GQtLN_QColor;
extern G__linked_taginfo G__G__GQtLN_QBrush;
extern G__linked_taginfo G__G__GQtLN_QFileIconProvider;
extern G__linked_taginfo G__G__GQtLN_TOrdCollection;
extern G__linked_taginfo G__G__GQtLN_QIconSet;
extern G__linked_taginfo G__G__GQtLN_TSystemFile;
extern G__linked_taginfo G__G__GQtLN_TQMime;
extern G__linked_taginfo G__G__GQtLN_TQMimeTypes;
extern G__linked_taginfo G__G__GQtLN_QPtrListlETQtClientWidgetgR;
extern G__linked_taginfo G__G__GQtLN_QFrame;
extern G__linked_taginfo G__G__GQtLN_QCursor;
extern G__linked_taginfo G__G__GQtLN_QAccel;
extern G__linked_taginfo G__G__GQtLN_QCloseEvent;
extern G__linked_taginfo G__G__GQtLN_TQtClientGuard;
extern G__linked_taginfo G__G__GQtLN_TQtWidget;
extern G__linked_taginfo G__G__GQtLN_TQtClientWidget;
extern G__linked_taginfo G__G__GQtLN_TQtClientWidgetcLcLdA;
extern G__linked_taginfo G__G__GQtLN_TQtNextEventMessage;
extern G__linked_taginfo G__G__GQtLN_TCanvas;
extern G__linked_taginfo G__G__GQtLN_QWidget;
extern G__linked_taginfo G__G__GQtLN_QPixmap;
extern G__linked_taginfo G__G__GQtLN_QMouseEvent;
extern G__linked_taginfo G__G__GQtLN_QFocusEvent;
extern G__linked_taginfo G__G__GQtLN_QCustomEvent;
extern G__linked_taginfo G__G__GQtLN_QKeyEvent;
extern G__linked_taginfo G__G__GQtLN_QShowEvent;
extern G__linked_taginfo G__G__GQtLN_QPaintEvent;
extern G__linked_taginfo G__G__GQtLN_QResizeEvent;
extern G__linked_taginfo G__G__GQtLN_QSize;
extern G__linked_taginfo G__G__GQtLN_QString;
extern G__linked_taginfo G__G__GQtLN_QSizePolicy;
extern G__linked_taginfo G__G__GQtLN_TQtWidgetBuffer;
extern G__linked_taginfo G__G__GQtLN_TQtWidgetcLcLdA;
extern G__linked_taginfo G__G__GQtLN_QPointArray;
extern G__linked_taginfo G__G__GQtLN_QTimer;
extern G__linked_taginfo G__G__GQtLN_TQtTimer;

/* STUB derived class for protected member access */
