include $(UAL)/env/$(UAL_ARCH)/Makefile.config

INC      =
INC     += -I$(UAL_ETEAPOT2)/src
INC     += -I$(UAL_PAC)/src
INC     += -I$(UAL_CORE)/include
INC     += -I$(UAL_ZLIB)/src
INC     += -I$(UAL_EXTRA)/UI/src
INC     += -I$(UAL_TEAPOT)/src
INC     += -I$(UAL_EXTRA)/SXF/src
INC     += -I$(UAL_SIMBAD)/src
INC     += -I$(UAL)/tools/sxf/src
INC     += -I$(UAL)/tools/include
INC     += -I$(UAL_EXTRA)/ADXF/src
INC     += -I$(UAL_ETEAPOT)/src
INC     += -I$(UAL_ETEAPOT_MltTurn)/src
INC     += -I$(UAL_E4_interim)/src

LIBS     =
LIBS    += -L$(UAL_ETEAPOT2)/lib/$(UAL_ARCH)        -lETeapot2
LIBS    += -L$(UAL_PAC)/lib/$(UAL_ARCH)             -lPac -lPacSMF -lPacOptics -lPacSurvey
LIBS    += -L$(UAL_ZLIB)/lib/$(UAL_ARCH)            -lZTps
LIBS    += -L$(UAL_CORE)/lib/$(UAL_ARCH)            -lUal -ldl
LIBS    += -L$(UAL_TEAPOT)/lib/$(UAL_ARCH)          -lTeapot
LIBS    += -L$(UAL_CORE)/lib/$(UAL_ARCH)            -lUal
LIBS    += -L$(UAL_ETEAPOT)/lib/$(UAL_ARCH)         -lETeapot
LIBS    += -L$(UAL_ETEAPOT_MltTurn)/lib/$(UAL_ARCH) -lETEAPOT_MltTurn
LIBS    += -L$(UAL)/tools/lib/$(UAL_ARCH)           -lgsl -lgslcblas

$(UAL_E4_interim)/lib/$(UAL_ARCH)/obj/%.o : %.cc
	$(CC) $(CCFLAGS) $(INC) -c $< -o $@;
