/********************************************************************
* tree/src/G__Tree.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tree/src/G__Tree.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Tree();
extern void G__cpp_setup_inheritanceG__Tree();
extern void G__cpp_setup_typetableG__Tree();
extern void G__cpp_setup_memvarG__Tree();
extern void G__cpp_setup_globalG__Tree();
extern void G__cpp_setup_memfuncG__Tree();
extern void G__cpp_setup_funcG__Tree();
extern void G__set_cpp_environmentG__Tree();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "tree/inc/TSelector.h"
#include "tree/inc/TDSet.h"
#include "tree/inc/TVirtualTreePlayer.h"
#include "tree/inc/TVirtualIndex.h"
#include "tree/inc/TBasket.h"
#include "tree/inc/TLeafS.h"
#include "tree/inc/TLeaf.h"
#include "tree/inc/TSelectorCint.h"
#include "tree/inc/TBranchObject.h"
#include "tree/inc/TTreeResult.h"
#include "tree/inc/TLeafI.h"
#include "tree/inc/TBranchBrowsable.h"
#include "tree/inc/TLeafF.h"
#include "tree/inc/TLeafD.h"
#include "tree/inc/TTreeRow.h"
#include "tree/inc/TChainProof.h"
#include "tree/inc/TEventList.h"
#include "tree/inc/TNtuple.h"
#include "tree/inc/TBranchClones.h"
#include "tree/inc/TCut.h"
#include "tree/inc/TBranchRef.h"
#include "tree/inc/TLeafL.h"
#include "tree/inc/TLeafElement.h"
#include "tree/inc/TBranchElement.h"
#include "tree/inc/TChain.h"
#include "tree/inc/TLeafC.h"
#include "tree/inc/TTree.h"
#include "tree/inc/TSelectorScalar.h"
#include "tree/inc/TChainElement.h"
#include "tree/inc/TBranch.h"
#include "tree/inc/TLeafO.h"
#include "tree/inc/TNtupleD.h"
#include "tree/inc/TLeafB.h"
#include "tree/inc/TLeafObject.h"
#include "tree/inc/TFriendElement.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__TreeLN_TClass;
extern G__linked_taginfo G__G__TreeLN_TBuffer;
extern G__linked_taginfo G__G__TreeLN_TMemberInspector;
extern G__linked_taginfo G__G__TreeLN_TObject;
extern G__linked_taginfo G__G__TreeLN_TNamed;
extern G__linked_taginfo G__G__TreeLN_TVirtualCollectionProxy;
extern G__linked_taginfo G__G__TreeLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__TreeLN_TList;
extern G__linked_taginfo G__G__TreeLN_TBrowser;
extern G__linked_taginfo G__G__TreeLN_TObjArray;
extern G__linked_taginfo G__G__TreeLN_TMethod;
extern G__linked_taginfo G__G__TreeLN_TStreamerInfo;
extern G__linked_taginfo G__G__TreeLN_TStreamerElement;
extern G__linked_taginfo G__G__TreeLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__TreeLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__TreeLN_TCollection;
extern G__linked_taginfo G__G__TreeLN_TIterator;
extern G__linked_taginfo G__G__TreeLN_TString;
extern G__linked_taginfo G__G__TreeLN_TIter;
extern G__linked_taginfo G__G__TreeLN_TSeqCollection;
extern G__linked_taginfo G__G__TreeLN_TFile;
extern G__linked_taginfo G__G__TreeLN_TDirectory;
extern G__linked_taginfo G__G__TreeLN_TKey;
extern G__linked_taginfo G__G__TreeLN_TVirtualProof;
extern G__linked_taginfo G__G__TreeLN_TTree;
extern G__linked_taginfo G__G__TreeLN_TSelector;
extern G__linked_taginfo G__G__TreeLN_TEventList;
extern G__linked_taginfo G__G__TreeLN_TDSet;
extern G__linked_taginfo G__G__TreeLN_TCut;
extern G__linked_taginfo G__G__TreeLN_TChain;
extern G__linked_taginfo G__G__TreeLN_TDSetElementPfn;
extern G__linked_taginfo G__G__TreeLN_TDSetElementMsn;
extern G__linked_taginfo G__G__TreeLN_TDSetElement;
extern G__linked_taginfo G__G__TreeLN_TClonesArray;
extern G__linked_taginfo G__G__TreeLN_G__ClassInfo;
extern G__linked_taginfo G__G__TreeLN_TMethodCall;
extern G__linked_taginfo G__G__TreeLN_TH1;
extern G__linked_taginfo G__G__TreeLN_TTreeFormula;
extern G__linked_taginfo G__G__TreeLN_TSQLResult;
extern G__linked_taginfo G__G__TreeLN_TPrincipal;
extern G__linked_taginfo G__G__TreeLN_TVirtualIndex;
extern G__linked_taginfo G__G__TreeLN_TVirtualTreePlayer;
extern G__linked_taginfo G__G__TreeLN_TBranch;
extern G__linked_taginfo G__G__TreeLN_TBasket;
extern G__linked_taginfo G__G__TreeLN_TAttFill;
extern G__linked_taginfo G__G__TreeLN_TLeaf;
extern G__linked_taginfo G__G__TreeLN_TBranchcLcLdA;
extern G__linked_taginfo G__G__TreeLN_TLeafcLcLdA;
extern G__linked_taginfo G__G__TreeLN_TLeafS;
extern G__linked_taginfo G__G__TreeLN_G__CallFunc;
extern G__linked_taginfo G__G__TreeLN_TSelectorCint;
extern G__linked_taginfo G__G__TreeLN_TBranchObject;
extern G__linked_taginfo G__G__TreeLN_TBranchObjectcLcLdA;
extern G__linked_taginfo G__G__TreeLN_TSQLRow;
extern G__linked_taginfo G__G__TreeLN_TTreeResult;
extern G__linked_taginfo G__G__TreeLN_TLeafI;
extern G__linked_taginfo G__G__TreeLN_TBranchElement;
extern G__linked_taginfo G__G__TreeLN_TVirtualBranchBrowsable;
extern G__linked_taginfo G__G__TreeLN_listlEvoidmUcOallocatorlEvoidmUgRsPgR;
extern G__linked_taginfo G__G__TreeLN_TMethodBrowsable;
extern G__linked_taginfo G__G__TreeLN_TNonSplitBrowsable;
extern G__linked_taginfo G__G__TreeLN_TCollectionPropertyBrowsable;
extern G__linked_taginfo G__G__TreeLN_TCollectionMethodBrowsable;
extern G__linked_taginfo G__G__TreeLN_TLeafF;
extern G__linked_taginfo G__G__TreeLN_TLeafD;
extern G__linked_taginfo G__G__TreeLN_TTreeRow;
extern G__linked_taginfo G__G__TreeLN_TAttLine;
extern G__linked_taginfo G__G__TreeLN_TAttMarker;
extern G__linked_taginfo G__G__TreeLN_TArrayD;
extern G__linked_taginfo G__G__TreeLN_TArrayI;
extern G__linked_taginfo G__G__TreeLN_EDataType;
extern G__linked_taginfo G__G__TreeLN_TFriendElement;
extern G__linked_taginfo G__G__TreeLN_TBranchRef;
extern G__linked_taginfo G__G__TreeLN_TTreecLcLdA;
extern G__linked_taginfo G__G__TreeLN_TTreeFriendLeafIter;
extern G__linked_taginfo G__G__TreeLN_TDrawFeedback;
extern G__linked_taginfo G__G__TreeLN_TChainProof;
extern G__linked_taginfo G__G__TreeLN_TNtuple;
extern G__linked_taginfo G__G__TreeLN_TBranchClones;
extern G__linked_taginfo G__G__TreeLN_TRefTable;
extern G__linked_taginfo G__G__TreeLN_TLeafL;
extern G__linked_taginfo G__G__TreeLN_TBranchElementcLcLdA;
extern G__linked_taginfo G__G__TreeLN_TLeafElement;
extern G__linked_taginfo G__G__TreeLN_TChaincLcLdA;
extern G__linked_taginfo G__G__TreeLN_TLeafC;
extern G__linked_taginfo G__G__TreeLN_TSelectorScalar;
extern G__linked_taginfo G__G__TreeLN_TParameterlElongsPlonggR;
extern G__linked_taginfo G__G__TreeLN_TChainElement;
extern G__linked_taginfo G__G__TreeLN_TLeafO;
extern G__linked_taginfo G__G__TreeLN_TNtupleD;
extern G__linked_taginfo G__G__TreeLN_TLeafB;
extern G__linked_taginfo G__G__TreeLN_TLeafObject;
extern G__linked_taginfo G__G__TreeLN_TLeafObjectcLcLdA;
extern G__linked_taginfo G__G__TreeLN_TFriendElementcLcLdA;

/* STUB derived class for protected member access */
class G__G__TreeLN_TSelector_PR : public TSelector {
 public:
  long G__OS_fStatus(){return((long)(&fStatus)-(long)this);}
  long G__OS_fOption(){return((long)(&fOption)-(long)this);}
  long G__OS_fObject(){return((long)(&fObject)-(long)this);}
  long G__OS_fInput(){return((long)(&fInput)-(long)this);}
  long G__OS_fOutput(){return((long)(&fOutput)-(long)this);}
};
