/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Beam.xs. Do not edit this file, edit Beam.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Beam.xs"
#include "PAC/Beam/Bunch.hh"

#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif

using namespace PAC;


#line 26 "Beam.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 168 "Beam.c"

XS_EUPXS(XS_Pac__BeamAttributes_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	BeamAttributes *	RETVAL;

	RETVAL = new BeamAttributes();
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__BeamAttributes_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	BeamAttributes *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (BeamAttributes *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::BeamAttributes::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__BeamAttributes_energy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_energy)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	BeamAttributes *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (BeamAttributes *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::BeamAttributes::energy() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 27 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getEnergy(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setEnergy(value);
        RETVAL = value;
   }  
#line 238 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__BeamAttributes_charge); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_charge)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	BeamAttributes *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (BeamAttributes *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::BeamAttributes::charge() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 40 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getCharge(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setCharge(value);
        RETVAL = value;
   }  
#line 271 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__BeamAttributes_mass); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_mass)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	BeamAttributes *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (BeamAttributes *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::BeamAttributes::mass() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 54 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getMass(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setMass(value);
        RETVAL = value;
   }  
#line 304 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__BeamAttributes_revfreq); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_revfreq)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	BeamAttributes *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (BeamAttributes *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::BeamAttributes::revfreq() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 67 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getRevfreq(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setRevfreq(value);
        RETVAL = value;
   }  
#line 337 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__BeamAttributes_macrosize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__BeamAttributes_macrosize)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	BeamAttributes *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (BeamAttributes *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::BeamAttributes::macrosize() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 80 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getMacrosize(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setMacrosize(value);
        RETVAL = value;
   }  
#line 370 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, size");
    {
	int	size = (int)SvIV(ST(1))
;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	Bunch *	RETVAL;

	RETVAL = new Bunch(size);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Bunch *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__Bunch_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Bunch *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::size() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	RETVAL = THIS->size();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_add)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, bunch");
    {
	Bunch*	bunch;
	Bunch *	THIS;

	if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		bunch = (Bunch *) SvIV((SV*) SvRV( ST(1) ));
	else{
		warn( "Pac::Bunch::add() -- bunch is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::add() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 106 "Beam.xs"
   (*THIS).add(*bunch);
#line 474 "Beam.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__Bunch_position); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_position)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	Position *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::position() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 111 "Beam.xs"
   char* CLASS = "Pac::Position";
   int index = (int ) SvIV(ST(1));
   if(items == 3) {
            if(SvTYPE(SvRV(ST(2))) == SVt_PVMG) 
	    {
                (*THIS)[index].setPosition(*((Position *) SvIV((SV*) SvRV( ST(2) ))) );
            } 
            else
	    {
                warn( "PacBunch::position(...) -- arguments are not a blessed SV reference" );
                XSRETURN_UNDEF;
            }
   }
   RETVAL = new Position((*THIS)[index].getPosition());
#line 512 "Beam.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_flag); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_flag)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::flag() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 131 "Beam.xs"
   int value;
   int index = (int ) SvIV(ST(1));
   if(items == 2) { RETVAL =(*THIS)[index].getFlag(); }
   if(items == 3) {
        value = (int ) SvIV(ST(2));
 	(*THIS)[index].setFlag(value);
        RETVAL = value;
   }  
#line 547 "Beam.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_energy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_energy)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::energy() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 145 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getBeamAttributes().getEnergy(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->getBeamAttributes().setEnergy(value);
        RETVAL = value;
   }  
#line 580 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_charge); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_charge)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::charge() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 158 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getBeamAttributes().getCharge(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->getBeamAttributes().setCharge(value);
        RETVAL = value;
   }  
#line 613 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_mass); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_mass)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::mass() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 172 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getBeamAttributes().getMass(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->getBeamAttributes().setMass(value);
        RETVAL = value;
   }  
#line 646 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_revfreq); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_revfreq)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::revfreq() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 186 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getBeamAttributes().getRevfreq(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->getBeamAttributes().setRevfreq(value);
        RETVAL = value;
   }  
#line 679 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Bunch_macrosize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Bunch_macrosize)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Bunch *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Bunch *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Bunch::macrosize() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 199 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getBeamAttributes().getMacrosize(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->getBeamAttributes().setMacrosize(value);
        RETVAL = value;
   }  
#line 712 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	Position *	RETVAL;

	RETVAL = new Position();
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Position *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__Position_set); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_set)
{
    dVAR; dXSARGS;
    if (items != 7)
       croak_xs_usage(cv,  "THIS, x, px, y, py, ct, de");
    {
	double	x = (double)SvNV(ST(1))
;
	double	px = (double)SvNV(ST(2))
;
	double	y = (double)SvNV(ST(3))
;
	double	py = (double)SvNV(ST(4))
;
	double	ct = (double)SvNV(ST(5))
;
	double	de = (double)SvNV(ST(6))
;
	Position *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::set() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	THIS->set(x, px, y, py, ct, de);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__Position_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Position *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::size() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	RETVAL = THIS->size();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_x); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_x)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::x() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 232 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getX(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setX(value);
        RETVAL = value;
   }  
#line 848 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_px); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_px)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::px() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 245 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getPX(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setPX(value);
        RETVAL = value;
   }  
#line 881 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_y); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_y)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::y() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 258 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getY(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setY(value);
        RETVAL = value;
   }  
#line 914 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_py); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_py)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::py() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 271 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getPY(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setPY(value);
        RETVAL = value;
   }  
#line 947 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_ct); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_ct)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::ct() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 284 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getCT(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setCT(value);
        RETVAL = value;
   }  
#line 980 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_de); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_de)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::de() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 297 "Beam.xs"
   double value;
   if(items == 1) RETVAL = THIS->getDE(); 
   if(items == 2) {
        value = (double ) SvNV(ST(1));
        THIS->setDE(value);
        RETVAL = value;
   }  
#line 1013 "Beam.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_add); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_add)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	Position *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::add() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 310 "Beam.xs"
	char* CLASS = "Pac::Position";
	if(SvTYPE(SvRV(ST(1))) == SVt_PVMG) 
	{
	        RETVAL = new Position(*THIS);
		(*RETVAL) += *((Position *) SvIV((SV*) SvRV( ST(1) ))); 
	}
	else
	{
		warn( "PacPosition::add(...) -- argument is not Position" );
             	XSRETURN_UNDEF;
	}
#line 1049 "Beam.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__Position_multiply); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__Position_multiply)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	Position *	THIS;
	Position *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Position *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::Position::multiply() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 327 "Beam.xs"
	char* CLASS = "Pac::Position";
	if(SvNOK(ST(1)) != 0 || SvIOK(ST(1)) != 0)
	{
	        RETVAL = new Position(*THIS);		    
		(*RETVAL) *= (double ) SvNV( ST(1) );
	}
	else
	{
		warn( "PacPosition::multiply(...) -- argument is not double" );
             	XSRETURN_UNDEF;
	}
#line 1086 "Beam.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Pac__Beam); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Pac__Beam)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Pac::BeamAttributes::new", XS_Pac__BeamAttributes_new, file, "$");
        (void)newXSproto_portable("Pac::BeamAttributes::DESTROY", XS_Pac__BeamAttributes_DESTROY, file, "$");
        (void)newXSproto_portable("Pac::BeamAttributes::energy", XS_Pac__BeamAttributes_energy, file, "$;@");
        (void)newXSproto_portable("Pac::BeamAttributes::charge", XS_Pac__BeamAttributes_charge, file, "$;@");
        (void)newXSproto_portable("Pac::BeamAttributes::mass", XS_Pac__BeamAttributes_mass, file, "$;@");
        (void)newXSproto_portable("Pac::BeamAttributes::revfreq", XS_Pac__BeamAttributes_revfreq, file, "$;@");
        (void)newXSproto_portable("Pac::BeamAttributes::macrosize", XS_Pac__BeamAttributes_macrosize, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::new", XS_Pac__Bunch_new, file, "$$");
        (void)newXSproto_portable("Pac::Bunch::DESTROY", XS_Pac__Bunch_DESTROY, file, "$");
        (void)newXSproto_portable("Pac::Bunch::size", XS_Pac__Bunch_size, file, "$");
        (void)newXSproto_portable("Pac::Bunch::add", XS_Pac__Bunch_add, file, "$$");
        (void)newXSproto_portable("Pac::Bunch::position", XS_Pac__Bunch_position, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::flag", XS_Pac__Bunch_flag, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::energy", XS_Pac__Bunch_energy, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::charge", XS_Pac__Bunch_charge, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::mass", XS_Pac__Bunch_mass, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::revfreq", XS_Pac__Bunch_revfreq, file, "$;@");
        (void)newXSproto_portable("Pac::Bunch::macrosize", XS_Pac__Bunch_macrosize, file, "$;@");
        (void)newXSproto_portable("Pac::Position::new", XS_Pac__Position_new, file, "$");
        (void)newXSproto_portable("Pac::Position::DESTROY", XS_Pac__Position_DESTROY, file, "$");
        (void)newXSproto_portable("Pac::Position::set", XS_Pac__Position_set, file, "$$$$$$$");
        (void)newXSproto_portable("Pac::Position::size", XS_Pac__Position_size, file, "$");
        (void)newXSproto_portable("Pac::Position::x", XS_Pac__Position_x, file, "$;@");
        (void)newXSproto_portable("Pac::Position::px", XS_Pac__Position_px, file, "$;@");
        (void)newXSproto_portable("Pac::Position::y", XS_Pac__Position_y, file, "$;@");
        (void)newXSproto_portable("Pac::Position::py", XS_Pac__Position_py, file, "$;@");
        (void)newXSproto_portable("Pac::Position::ct", XS_Pac__Position_ct, file, "$;@");
        (void)newXSproto_portable("Pac::Position::de", XS_Pac__Position_de, file, "$;@");
        (void)newXSproto_portable("Pac::Position::add", XS_Pac__Position_add, file, "$;@");
        (void)newXSproto_portable("Pac::Position::multiply", XS_Pac__Position_multiply, file, "$;@");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

