/********************************************************************
* xml/src/G__XML.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error xml/src/G__XML.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__XML();
extern void G__cpp_setup_inheritanceG__XML();
extern void G__cpp_setup_typetableG__XML();
extern void G__cpp_setup_memvarG__XML();
extern void G__cpp_setup_globalG__XML();
extern void G__cpp_setup_memfuncG__XML();
extern void G__cpp_setup_funcG__XML();
extern void G__set_cpp_environmentG__XML();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "xml/inc/TXMLSetup.h"
#include "xml/inc/TXMLBuffer.h"
#include "xml/inc/TXMLFile.h"
#include "xml/inc/TXMLKey.h"
#include "xml/inc/TXMLPlayer.h"
#include "xml/inc/TXMLEngine.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__XMLLN_type_info;
extern G__linked_taginfo G__G__XMLLN_TClass;
extern G__linked_taginfo G__G__XMLLN_TBuffer;
extern G__linked_taginfo G__G__XMLLN_TMemberInspector;
extern G__linked_taginfo G__G__XMLLN_TObject;
extern G__linked_taginfo G__G__XMLLN_TNamed;
extern G__linked_taginfo G__G__XMLLN_TMemberStreamer;
extern G__linked_taginfo G__G__XMLLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__XMLLN_TList;
extern G__linked_taginfo G__G__XMLLN_TBrowser;
extern G__linked_taginfo G__G__XMLLN_TObjArray;
extern G__linked_taginfo G__G__XMLLN_TStreamerInfo;
extern G__linked_taginfo G__G__XMLLN_TStreamerElement;
extern G__linked_taginfo G__G__XMLLN_TExMap;
extern G__linked_taginfo G__G__XMLLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__XMLLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__XMLLN_TBuffercLcLEMode;
extern G__linked_taginfo G__G__XMLLN_TString;
extern G__linked_taginfo G__G__XMLLN_TFile;
extern G__linked_taginfo G__G__XMLLN_TDirectory;
extern G__linked_taginfo G__G__XMLLN_TKey;
extern G__linked_taginfo G__G__XMLLN_TXMLSetup;
extern G__linked_taginfo G__G__XMLLN_TXMLSetupcLcLEXMLLayout;
extern G__linked_taginfo G__G__XMLLN_TXMLInputStream;
extern G__linked_taginfo G__G__XMLLN_TXMLOutputStream;
extern G__linked_taginfo G__G__XMLLN_TXMLEngine;
extern G__linked_taginfo G__G__XMLLN_TXMLFile;
extern G__linked_taginfo G__G__XMLLN_TXMLStackObj;
extern G__linked_taginfo G__G__XMLLN_TXMLBuffer;
extern G__linked_taginfo G__G__XMLLN_TFilecLcLERelativeTo;
extern G__linked_taginfo G__G__XMLLN_TXMLKey;
extern G__linked_taginfo G__G__XMLLN_TStreamerSTL;
extern G__linked_taginfo G__G__XMLLN_TDataMember;
extern G__linked_taginfo G__G__XMLLN_TXMLPlayer;

/* STUB derived class for protected member access */
