/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Optics.xs. Do not edit this file, edit Optics.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Optics.xs"
#include <assert.h> 

#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif

#ifdef do_open
#undef do_open
#endif

#ifdef do_close
#undef do_close
#endif

#include "Optics/PacChromData.h"
#include "Optics/PacTMap.h"

using namespace ZLIB;
using namespace PAC;

#line 37 "Optics.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 179 "Optics.c"

XS_EUPXS(XS_Pac__TMap_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, size");
    {
	int	size = (int)SvIV(ST(1))
;
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	PacTMap *	RETVAL;

	RETVAL = new PacTMap(size);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TMap_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PacTMap *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__TMap_mltOrder); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_mltOrder)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTMap *	THIS;
	int	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::mltOrder() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 39 "Optics.xs"
        if(items == 1) { RETVAL = THIS->mltOrder(); }
   	if(items == 2) {
            int order = (int) SvIV( ST(1) );
            THIS->mltOrder(order);
            RETVAL = order;
	}
#line 250 "Optics.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TMap_refOrbit); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_refOrbit)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTMap *	THIS;
	Position *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::refOrbit() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 51 "Optics.xs"
	char* CLASS = "Pac::Position";
        Position* p;		
        if(items == 1) RETVAL = new Position(THIS->refOrbit()); 
   	if(items == 2) {
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
        	p = (Position *) SvIV((SV*) SvRV( ST(1) ));
        	THIS->refOrbit(*p);
        	RETVAL = new Position(*p);
	  }
	  else{
	    warn( "PacTMap::refOrbit(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	  }
	}
#line 289 "Optics.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TMap_daVTps); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_daVTps)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTMap *	THIS;
	VTps *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::daVTps() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 71 "Optics.xs"
	char* CLASS = "Zlib::VTps";
        ZLIB::VTps* p;		
        if(items == 1) RETVAL = new ZLIB::VTps(*(THIS->operator->())); 
   	if(items == 2) {
	  if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
        	p = (ZLIB::VTps *) SvIV((SV*) SvRV( ST(1) ));
        	THIS->operator=(*p);
        	RETVAL = new ZLIB::VTps(*p);
	  }
	  else{
	    warn( "PacTMap::daVTps(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	  }
	}
#line 329 "Optics.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TMap_propagate); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_propagate)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTMap *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::propagate() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 91 "Optics.xs"
        int turns = 1;
        if(items = 3){
		if(SvNOK(ST(2))){ turns = (int ) SvNV( ST(2) ); }
		if(SvIOK(ST(2))){ turns = (int ) SvIV( ST(2) ); }
	}	  
	if(SvTYPE(SvRV(ST(1))) == SVt_PVMG ){
        	THIS->propagate(*(Bunch *) SvIV((SV*) SvRV( ST(1) )), turns);
	}
	else{
	    warn( "PacTMap::propagate(...) -- argument is not double or a blessed SV reference" );
            XSRETURN_UNDEF;
	}
#line 366 "Optics.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TMap_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_read)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, nfile");
    {
	char*	nfile = (char *)SvPV_nolen(ST(1))
;
	PacTMap *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::read() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	THIS->read(nfile);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__TMap_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TMap_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, nfile");
    {
	char*	nfile = (char *)SvPV_nolen(ST(1))
;
	PacTMap *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTMap *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TMap::write() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	THIS->write(nfile);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__TwissData_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	PacTwissData *	RETVAL;

	RETVAL = new PacTwissData();
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TwissData_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PacTwissData *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__TwissData_dimension); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_dimension)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PacTwissData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::dimension() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	RETVAL = THIS->dimension();
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TwissData_copy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_copy)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, in");
    {
	PacTwissData*	in;
	PacTwissData *	THIS;

	if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		in = (PacTwissData *) SvIV((SV*) SvRV( ST(1) ));
	else{
		warn( "Pac::TwissData::copy() -- in is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::copy() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 128 "Optics.xs"
	THIS->operator=(*in);
#line 517 "Optics.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__TwissData_beta); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_beta)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTwissData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::beta() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 133 "Optics.xs"
	int dim = (int) SvIV(ST(1));
	double value;
   	if(items == 2) RETVAL = THIS->beta(dim); 
   	if(items == 3) {
		value = (double ) SvNV(ST(2));
		THIS->beta(dim, value);
		RETVAL = value;
	}
#line 550 "Optics.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TwissData_alpha); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_alpha)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTwissData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::alpha() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 147 "Optics.xs"
	int dim = (int) SvIV(ST(1));
	double value;
   	if(items == 2) RETVAL = THIS->alpha(dim); 
   	if(items == 3) {
		value = (double ) SvNV(ST(2));
		THIS->alpha(dim, value);
		RETVAL = value;
	}
#line 584 "Optics.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TwissData_mu); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_mu)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTwissData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::mu() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 161 "Optics.xs"
	int dim = (int) SvIV(ST(1));
	double value;
   	if(items == 2) RETVAL = THIS->mu(dim); 
   	if(items == 3) {
		value = (double ) SvNV(ST(2));
		THIS->mu(dim, value);
		RETVAL = value;
	}
#line 618 "Optics.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TwissData_d); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_d)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTwissData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::d() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 176 "Optics.xs"
	int dim = (int) SvIV(ST(1));
	double value;
   	if(items == 2) RETVAL = THIS->d(dim); 
   	if(items == 3) {
		value = (double ) SvNV(ST(2));
		THIS->d(dim, value);
		RETVAL = value;
	}
#line 652 "Optics.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__TwissData_dp); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__TwissData_dp)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	PacTwissData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacTwissData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::TwissData::dp() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 190 "Optics.xs"
	int dim = (int) SvIV(ST(1));
	double value;
   	if(items == 2) RETVAL = THIS->dp(dim); 
   	if(items == 3) {
		value = (double ) SvNV(ST(2));
		THIS->dp(dim, value);
		RETVAL = value;
	}
#line 686 "Optics.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__ChromData_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__ChromData_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	PacChromData *	RETVAL;

	RETVAL = new PacChromData();
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__ChromData_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__ChromData_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PacChromData *	THIS;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacChromData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::ChromData::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__ChromData_dimension); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__ChromData_dimension)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PacChromData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacChromData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::ChromData::dimension() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	RETVAL = THIS->dimension();
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__ChromData_copy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__ChromData_copy)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, in");
    {
	PacChromData*	in;
	PacChromData *	THIS;

	if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		in = (PacChromData *) SvIV((SV*) SvRV( ST(1) ));
	else{
		warn( "Pac::ChromData::copy() -- in is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacChromData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::ChromData::copy() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 216 "Optics.xs"
	THIS->operator=(*in);
#line 788 "Optics.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pac__ChromData_twiss); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__ChromData_twiss)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PacChromData *	THIS;
	PacTwissData *	RETVAL;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacChromData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::ChromData::twiss() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 221 "Optics.xs"
   char* CLASS = "Pac::TwissData";
   RETVAL = new PacTwissData((*THIS).twiss());	
#line 814 "Optics.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pac__ChromData_dmu); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pac__ChromData_dmu)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, dim");
    {
	int	dim = (int)SvIV(ST(1))
;
	PacChromData *	THIS;
	double	RETVAL;
	dXSTARG;

	if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PacChromData *) SvIV((SV*) SvRV( ST(0) ));
	else{
		warn( "Pac::ChromData::dmu() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 231 "Optics.xs"
	RETVAL = THIS->dmu(dim);
#line 844 "Optics.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Pac__Optics); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Pac__Optics)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Pac::TMap::new", XS_Pac__TMap_new, file, "$$");
        (void)newXSproto_portable("Pac::TMap::DESTROY", XS_Pac__TMap_DESTROY, file, "$");
        (void)newXSproto_portable("Pac::TMap::mltOrder", XS_Pac__TMap_mltOrder, file, "$;@");
        (void)newXSproto_portable("Pac::TMap::refOrbit", XS_Pac__TMap_refOrbit, file, "$;@");
        (void)newXSproto_portable("Pac::TMap::daVTps", XS_Pac__TMap_daVTps, file, "$;@");
        (void)newXSproto_portable("Pac::TMap::propagate", XS_Pac__TMap_propagate, file, "$;@");
        (void)newXSproto_portable("Pac::TMap::read", XS_Pac__TMap_read, file, "$$");
        (void)newXSproto_portable("Pac::TMap::write", XS_Pac__TMap_write, file, "$$");
        (void)newXSproto_portable("Pac::TwissData::new", XS_Pac__TwissData_new, file, "$");
        (void)newXSproto_portable("Pac::TwissData::DESTROY", XS_Pac__TwissData_DESTROY, file, "$");
        (void)newXSproto_portable("Pac::TwissData::dimension", XS_Pac__TwissData_dimension, file, "$");
        (void)newXSproto_portable("Pac::TwissData::copy", XS_Pac__TwissData_copy, file, "$$");
        (void)newXSproto_portable("Pac::TwissData::beta", XS_Pac__TwissData_beta, file, "$;@");
        (void)newXSproto_portable("Pac::TwissData::alpha", XS_Pac__TwissData_alpha, file, "$;@");
        (void)newXSproto_portable("Pac::TwissData::mu", XS_Pac__TwissData_mu, file, "$;@");
        (void)newXSproto_portable("Pac::TwissData::d", XS_Pac__TwissData_d, file, "$;@");
        (void)newXSproto_portable("Pac::TwissData::dp", XS_Pac__TwissData_dp, file, "$;@");
        (void)newXSproto_portable("Pac::ChromData::new", XS_Pac__ChromData_new, file, "$");
        (void)newXSproto_portable("Pac::ChromData::DESTROY", XS_Pac__ChromData_DESTROY, file, "$");
        (void)newXSproto_portable("Pac::ChromData::dimension", XS_Pac__ChromData_dimension, file, "$");
        (void)newXSproto_portable("Pac::ChromData::copy", XS_Pac__ChromData_copy, file, "$$");
        (void)newXSproto_portable("Pac::ChromData::twiss", XS_Pac__ChromData_twiss, file, "$");
        (void)newXSproto_portable("Pac::ChromData::dmu", XS_Pac__ChromData_dmu, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

