include $(UAL)/env/$(UAL_ARCH)/Makefile.config

# DIRS = ../codes/ACCSIM/api ../codes/AIM/api ../codes/DA/api ../codes/PAC/api ../codes/SIMBAD/api ../codes/TEAPOT/api ../codes/UAL/api ../codes/ZLIB/api ../ext/ADXF/api
DIRS = ../codes/ACCSIM/api ../codes/PAC/api ../codes/TEAPOT/api ../codes/ZLIB/api ../ext/ADXF/api

compile:  
	@for dir in $(DIRS); do \
		(cd $$dir; if [ -f ./Makefile ]; then $(MAKE) compile; fi;); \
	done

clean: 
	@for dir in $(DIRS) ; do \
		(cd $$dir; if [ -f ./Makefile ]; then $(MAKE) clean; fi;); \
	done
