/********************************************************************
* eg/src/G__EG.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eg/src/G__EG.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__EG();
extern void G__cpp_setup_inheritanceG__EG();
extern void G__cpp_setup_typetableG__EG();
extern void G__cpp_setup_memvarG__EG();
extern void G__cpp_setup_globalG__EG();
extern void G__cpp_setup_memfuncG__EG();
extern void G__cpp_setup_funcG__EG();
extern void G__set_cpp_environmentG__EG();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "eg/inc/TDecayChannel.h"
#include "eg/inc/TAttParticle.h"
#include "eg/inc/TParticleClassPDG.h"
#include "eg/inc/TPrimary.h"
#include "eg/inc/TGenerator.h"
#include "eg/inc/TParticle.h"
#include "eg/inc/TDatabasePDG.h"
#include "eg/inc/TParticlePDG.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__EGLN_TClass;
extern G__linked_taginfo G__G__EGLN_TBuffer;
extern G__linked_taginfo G__G__EGLN_TMemberInspector;
extern G__linked_taginfo G__G__EGLN_TObject;
extern G__linked_taginfo G__G__EGLN_TNamed;
extern G__linked_taginfo G__G__EGLN_TBrowser;
extern G__linked_taginfo G__G__EGLN_TObjArray;
extern G__linked_taginfo G__G__EGLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__EGLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__EGLN_TString;
extern G__linked_taginfo G__G__EGLN_TArrayI;
extern G__linked_taginfo G__G__EGLN_TDecayChannel;
extern G__linked_taginfo G__G__EGLN_TAttLine;
extern G__linked_taginfo G__G__EGLN_THashList;
extern G__linked_taginfo G__G__EGLN_TAttParticle;
extern G__linked_taginfo G__G__EGLN_TClonesArray;
extern G__linked_taginfo G__G__EGLN_TParticlePDG;
extern G__linked_taginfo G__G__EGLN_TParticleClassPDG;
extern G__linked_taginfo G__G__EGLN_TAtt3D;
extern G__linked_taginfo G__G__EGLN_TPrimary;
extern G__linked_taginfo G__G__EGLN_TParticle;
extern G__linked_taginfo G__G__EGLN_TGenerator;
extern G__linked_taginfo G__G__EGLN_TVector3;
extern G__linked_taginfo G__G__EGLN_TLorentzVector;
extern G__linked_taginfo G__G__EGLN_TDatabasePDG;

/* STUB derived class for protected member access */
