//
// File generated by utils/src/rootcint_tmp at Sun May 10 15:58:05 2020.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "G__ASImage.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"

#include "TCollectionProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void TASImage_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TASImage_IsA(const void*);
   static void *new_TASImage(void *p = 0);
   static void *newArray_TASImage(Long_t size);
   static void delete_TASImage(void *p);
   static void deleteArray_TASImage(void *p);
   static void destruct_TASImage(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::TASImage*)
   {
      ::TASImage *ptr = 0;
      static ::ROOT::TGenericClassInfo 
         instance("TASImage", ::TASImage::Class_Version(), "asimage/inc/TASImage.h", 46,
                  typeid(::TASImage), DefineBehavior(ptr, ptr),
                  &::TASImage::Dictionary, &TASImage_IsA, 0,
                  sizeof(::TASImage) );
      instance.SetNew(&new_TASImage);
      instance.SetNewArray(&newArray_TASImage);
      instance.SetDelete(&delete_TASImage);
      instance.SetDeleteArray(&deleteArray_TASImage);
      instance.SetDestructor(&destruct_TASImage);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::TASImage*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *TASImage::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TASImage::Class_Name()
{
   return "TASImage";
}

//______________________________________________________________________________
const char *TASImage::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::TASImage*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TASImage::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::TASImage*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TASImage::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::TASImage*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TASImage::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::TASImage*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TASImage::Streamer(TBuffer &R__b)
{
   // Stream an object of class TASImage.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TImage::Streamer(R__b);
      R__b >> fMaxValue;
      R__b >> fMinValue;
      R__b >> fZoomOffX;
      R__b >> fZoomOffY;
      R__b >> fZoomWidth;
      R__b >> fZoomHeight;
      R__b >> fZoomUpdate;
      R__b >> fEditable;
      R__b >> fPaintMode;
      R__b.CheckByteCount(R__s, R__c, TASImage::IsA());
   } else {
      R__c = R__b.WriteVersion(TASImage::IsA(), kTRUE);
      TImage::Streamer(R__b);
      R__b << fMaxValue;
      R__b << fMinValue;
      R__b << fZoomOffX;
      R__b << fZoomOffY;
      R__b << fZoomWidth;
      R__b << fZoomHeight;
      R__b << fZoomUpdate;
      R__b << fEditable;
      R__b << fPaintMode;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TASImage::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TASImage.

      TClass *R__cl = ::TASImage::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fImage", &fImage);
      R__insp.Inspect(R__cl, R__parent, "*fScaledImage", &fScaledImage);
      R__insp.Inspect(R__cl, R__parent, "fMaxValue", &fMaxValue);
      R__insp.Inspect(R__cl, R__parent, "fMinValue", &fMinValue);
      R__insp.Inspect(R__cl, R__parent, "fZoomOffX", &fZoomOffX);
      R__insp.Inspect(R__cl, R__parent, "fZoomOffY", &fZoomOffY);
      R__insp.Inspect(R__cl, R__parent, "fZoomWidth", &fZoomWidth);
      R__insp.Inspect(R__cl, R__parent, "fZoomHeight", &fZoomHeight);
      R__insp.Inspect(R__cl, R__parent, "fZoomUpdate", &fZoomUpdate);
      R__insp.Inspect(R__cl, R__parent, "fEditable", &fEditable);
      R__insp.Inspect(R__cl, R__parent, "fPaintMode", &fPaintMode);
      TImage::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TASImage_IsA(const void *obj) {
      return ((::TASImage*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_TASImage(void *p) {
      return  p ? new(p) ::TASImage : new ::TASImage;
   }
   static void *newArray_TASImage(Long_t size) {
      return new ::TASImage[size];
   }
   // Wrapper around operator delete
   static void delete_TASImage(void *p) {
      delete ((::TASImage*)p);
   }
   static void deleteArray_TASImage(void *p) {
      delete [] ((::TASImage*)p);
   }
   static void destruct_TASImage(void *p) {
      typedef ::TASImage current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TASImage

/********************************************************
* asimage/src/G__ASImage.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableG__ASImage();

extern "C" void G__set_cpp_environmentG__ASImage() {
  G__add_compiledheader("base/inc/TROOT.h");
  G__add_compiledheader("base/inc/TMemberInspector.h");
  G__add_compiledheader("asimage/inc/TASImage.h");
  G__cpp_reset_tagtableG__ASImage();
}
class G__asimagedIsrcdIG__ASImagedOcxx_tag {};

void* operator new(size_t size,G__asimagedIsrcdIG__ASImagedOcxx_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__asimagedIsrcdIG__ASImagedOcxx_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_asimagedIsrcdIG__ASImagedOcxx() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevG__ASImage() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TASImage */
static int G__G__ASImage_161_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
   if(G__getaryconstruct()) p=new TASImage[G__getaryconstruct()];
   else                    p=new TASImage;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
      p = new TASImage((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
   switch(libp->paran) {
   case 2:
      p = new TASImage((const char*)G__int(libp->para[0]),(TImage::EImageFileTypes)G__int(libp->para[1]));
      break;
   case 1:
      p = new TASImage((const char*)G__int(libp->para[0]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
   switch(libp->paran) {
   case 5:
      p = new TASImage(
(const char*)G__int(libp->para[0]),(const Double_t*)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(TImagePalette*)G__int(libp->para[4]));
      break;
   case 4:
      p = new TASImage(
(const char*)G__int(libp->para[0]),(const Double_t*)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
   switch(libp->paran) {
   case 4:
      p = new TASImage(
(const char*)G__int(libp->para[0]),*(TArrayD*)libp->para[1].ref
,(UInt_t)G__int(libp->para[2]),(TImagePalette*)G__int(libp->para[3]));
      break;
   case 3:
      p = new TASImage(
(const char*)G__int(libp->para[0]),*(TArrayD*)libp->para[1].ref
,(UInt_t)G__int(libp->para[2]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
   switch(libp->paran) {
   case 4:
      p = new TASImage(
(const char*)G__int(libp->para[0]),*(TVectorD*)libp->para[1].ref
,(UInt_t)G__int(libp->para[2]),(TImagePalette*)G__int(libp->para[3]));
      break;
   case 3:
      p = new TASImage(
(const char*)G__int(libp->para[0]),*(TVectorD*)libp->para[1].ref
,(UInt_t)G__int(libp->para[2]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TASImage *p=NULL;
      p = new TASImage(*(TASImage*)libp->para[0].ref);
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__G__ASImageLN_TASImage);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        const TASImage& obj=((TASImage*)(G__getstructoffset()))->operator=(*(TASImage*)libp->para[0].ref);
         result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TASImage*)(G__getstructoffset()))->Clone((const char*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetEditable((Bool_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetEditable();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((const TASImage*)(G__getstructoffset()))->IsEditable());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FromPad((TVirtualPad*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FromPad((TVirtualPad*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FromPad((TVirtualPad*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FromPad((TVirtualPad*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FromPad((TVirtualPad*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Draw((Option_t*)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Draw();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Paint((Option_t*)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Paint();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TASImage*)(G__getstructoffset()))->DistancetoPrimitive((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->ExecuteEvent((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((const TASImage*)(G__getstructoffset()))->GetObjectInfo((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetPalette((const TImagePalette*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Zoom((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->UnZoom();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Flip((Int_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Flip();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Mirror((Bool_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Mirror();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Scale((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Tile((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Crop((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Crop((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Crop((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Crop((Int_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Crop();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Pad((const char*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Pad((const char*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Pad((const char*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Pad((const char*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Pad((const char*)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Pad();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Blur((Double_t)G__double(libp->para[0]),(Double_t)G__double(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Blur((Double_t)G__double(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Blur();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Vectorize((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Vectorize((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Vectorize((UInt_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Vectorize();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->StartPaletteEditor();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 9:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV(
(UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]),(UInt_t)G__int(libp->para[7])
,(UInt_t)G__int(libp->para[8]));
      break;
   case 8:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV(
(UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]),(UInt_t)G__int(libp->para[7]));
      break;
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV(
(UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV((UInt_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->HSV();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Merge((const TImage*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Merge((const TImage*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Merge((const TImage*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Merge((const TImage*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Append((const TImage*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Append((const TImage*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Append((const TImage*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient(
(UInt_t)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5])
,(UInt_t)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient((UInt_t)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient((UInt_t)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient((UInt_t)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient((UInt_t)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient((UInt_t)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient((UInt_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Gradient();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 8:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(UShort_t)G__int(libp->para[6]),(Bool_t)G__int(libp->para[7]));
      break;
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(UShort_t)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel((Int_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Bevel();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 9:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(TImage::EText3DType)G__int(libp->para[6]),(const char*)G__int(libp->para[7])
,(Float_t)G__double(libp->para[8]));
      break;
   case 8:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(TImage::EText3DType)G__int(libp->para[6]),(const char*)G__int(libp->para[7]));
      break;
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(TImage::EText3DType)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(const char*)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(Int_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText((Int_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawText();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->BeginPaint((Bool_t)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->BeginPaint();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->EndPaint();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawLine((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawLine((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawLine((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 8:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawDashLine(
(UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(const char*)G__int(libp->para[6]),(UInt_t)G__int(libp->para[7]));
      break;
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawDashLine(
(UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(const char*)G__int(libp->para[5])
,(const char*)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawDashLine((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(const char*)G__int(libp->para[5]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawBox(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawBox((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawBox((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawBox((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawRectangle((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawRectangle((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawRectangle((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillRectangle((const char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillRectangle((const char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillRectangle((const char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillRectangle((const char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillRectangle((const char*)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillRectangle();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_5(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawPolyLine((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(TImage::ECoordMode)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawPolyLine((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawPolyLine((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawPolyLine((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->PutPixel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->PutPixel((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->PolyPoint((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(TImage::ECoordMode)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->PolyPoint((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->PolyPoint((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawSegments((UInt_t)G__int(libp->para[0]),(Segment_t*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawSegments((UInt_t)G__int(libp->para[0]),(Segment_t*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawSegments((UInt_t)G__int(libp->para[0]),(Segment_t*)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(const char*)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(TImage*)G__int(libp->para[2]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CropPolygon((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawFillArea((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawFillArea((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawFillArea((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]),(const char*)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawFillArea((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawFillArea((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawFillArea((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(TImage*)G__int(libp->para[2]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillSpans(
(UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5])
,(UInt_t)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillSpans((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]),(UInt_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillSpans((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])
,(const char*)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillSpans((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]),(const char*)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillSpans((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->FillSpans((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]),(TImage*)G__int(libp->para[3]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CropSpans((UInt_t)G__int(libp->para[0]),(TPoint*)G__int(libp->para[1])
,(UInt_t*)G__int(libp->para[2]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 9:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CopyArea(
(TImage*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]),(Int_t)G__int(libp->para[7])
,(TImage::EColorChan)G__int(libp->para[8]));
      break;
   case 8:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CopyArea(
(TImage*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]),(Int_t)G__int(libp->para[7]));
      break;
   case 7:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CopyArea(
(TImage*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(Int_t)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CopyArea((TImage*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->CopyArea((TImage*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->DrawCellArray(
(Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(Int_t)G__int(libp->para[2]),(Int_t)G__int(libp->para[3])
,(Int_t)G__int(libp->para[4]),(Int_t)G__int(libp->para[5])
,(UInt_t*)G__int(libp->para[6]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->ReadImage((const char*)G__int(libp->para[0]),(TImage::EImageFileTypes)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->ReadImage((const char*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->WriteImage((const char*)G__int(libp->para[0]),(TImage::EImageFileTypes)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->WriteImage((const char*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage((const Double_t*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(TImagePalette*)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage((const Double_t*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage(*(TArrayD*)libp->para[0].ref,(UInt_t)G__int(libp->para[1])
,(TImagePalette*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage(*(TArrayD*)libp->para[0].ref,(UInt_t)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage(*(TVectorD*)libp->para[0].ref,(UInt_t)G__int(libp->para[1])
,(TImagePalette*)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage(*(TVectorD*)libp->para[0].ref,(UInt_t)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage((Pixmap_t)G__int(libp->para[0]),(Pixmap_t)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->SetImage((Pixmap_t)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_7(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,104,(long)((const TASImage*)(G__getstructoffset()))->GetWidth());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,104,(long)((const TASImage*)(G__getstructoffset()))->GetHeight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,104,(long)((const TASImage*)(G__getstructoffset()))->GetScaledWidth());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,104,(long)((const TASImage*)(G__getstructoffset()))->GetScaledHeight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((const TASImage*)(G__getstructoffset()))->IsValid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TASImage*)(G__getstructoffset()))->GetImage());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TASImage*)(G__getstructoffset()))->GetScaledImage());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,107,(long)((TASImage*)(G__getstructoffset()))->GetPixmap());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,107,(long)((TASImage*)(G__getstructoffset()))->GetMask());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetPixels((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])));
      break;
   case 3:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetPixels((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2])));
      break;
   case 2:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetPixels((Int_t)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetPixels((Int_t)G__int(libp->para[0])));
      break;
   case 0:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetPixels());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetArray((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(TImagePalette*)G__int(libp->para[2])));
      break;
   case 2:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetArray((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetArray((UInt_t)G__int(libp->para[0])));
      break;
   case 0:
   G__letint(result7,85,(long)((TASImage*)(G__getstructoffset()))->GetArray());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,72,(long)((TASImage*)(G__getstructoffset()))->GetArgbArray());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,72,(long)((TASImage*)(G__getstructoffset()))->GetScanline((UInt_t)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TASImage::GetVisual());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,104,(long)TASImage::AlphaBlend((UInt_t)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TASImage::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TASImage::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_6_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TASImage::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_7_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TASImage::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_8_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TASImage*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_9_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_0_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_1_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TASImage*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_2_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TASImage::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_3_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TASImage::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_4_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TASImage::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__ASImage_161_5_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TASImage::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TASImage G__TTASImage;
static int G__G__ASImage_161_6_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TASImage *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TASImage *)((G__getstructoffset())+sizeof(TASImage)*i);
   else  delete (TASImage *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TASImage */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__ASImage {
 public:
  G__Sizep2memfuncG__ASImage() {p=&G__Sizep2memfuncG__ASImage::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__ASImage::*p)();
};

size_t G__get_sizep2memfuncG__ASImage()
{
  G__Sizep2memfuncG__ASImage a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__ASImage() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__ASImageLN_TASImage))) {
     TASImage *G__Lderived;
     G__Lderived=(TASImage*)0x1000;
     {
       TImage *G__Lpbase=(TImage*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage),G__get_linked_tagnum(&G__G__ASImageLN_TImage),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage),G__get_linked_tagnum(&G__G__ASImageLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage),G__get_linked_tagnum(&G__G__ASImageLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttImage *G__Lpbase=(TAttImage*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage),G__get_linked_tagnum(&G__G__ASImageLN_TAttImage),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__ASImage() {

   /* Setting up typedef entry */
   G__search_typename2("UShort_t",114,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Float_t",102,-1,0,
-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,
-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,
-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__G__ASImageLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.42 2005/03/10 17:57:04 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__ASImageLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ASImageLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.42 2005/03/10 17:57:04 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__ASImageLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__ASImageLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.42 2005/03/10 17:57:04 rdm Exp $",0);
   G__search_typename2("Pixmap_t",107,-1,0,
-1);
   G__setnewtype(-1,"Pixmap handle",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TASImage */
static void G__setup_memvarTASImage(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage));
   { TASImage *p; p=(TASImage*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__ASImageLN_TASImagecLcLdA),-1,-2,1,"kNoZoom=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__ASImageLN_TASImagecLcLdA),-1,-2,1,"kZoom=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__G__ASImageLN_TASImagecLcLdA),-1,-2,1,"kZoomOps=-1",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__ASImageLN_ASImage),-1,-1,2,"fImage=",0,"! pointer to image structure of original image");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,-1,2,"fScaledImage=",0,"! temporary scaled and zoomed image produced from original image");
   G__memvar_setup((void*)NULL,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fMaxValue=",0,"max value in image");
   G__memvar_setup((void*)NULL,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fMinValue=",0,"min value in image");
   G__memvar_setup((void*)NULL,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fZoomOffX=",0,"X - offset for zooming in image pixels");
   G__memvar_setup((void*)NULL,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fZoomOffY=",0,"Y - offset for zooming im image pixels");
   G__memvar_setup((void*)NULL,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fZoomWidth=",0,"width of zoomed image in image pixels");
   G__memvar_setup((void*)NULL,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fZoomHeight=",0,"hight of zoomed image in image pixels");
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fZoomUpdate=",0,"kZoom - new zooming required, kZoomOps - other ops in action, kNoZoom - no zooming or ops");
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fEditable=",0,"kTRUE image can be resized, moved by resizing/moving gPad ");
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fPaintMode=",0,"kTRUE - fast mode, kFALSE - low memory mode");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__ASImageLN_ASVisual),-1,-2,2,"fgVisual=",0,"pointer to visual structure");
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-2,2,"fgInit=",0,"global flag to init afterimage only once");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__G__ASImageLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__ASImage() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTASImage(void) {
   /* TASImage */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage));
   G__memfunc_setup("DrawVLine",876,(G__InterfaceMethod)NULL,121,-1,-1,0,5,1,4,0,
"h - 'UInt_t' 0 - x h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - y2 h - 'UInt_t' 0 - col "
"h - 'UInt_t' 0 - thick",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawHLine",862,(G__InterfaceMethod)NULL,121,-1,-1,0,5,1,4,0,
"h - 'UInt_t' 0 - y h - 'UInt_t' 0 - x1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - col "
"h - 'UInt_t' 0 - thick",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawLineInternal",1619,(G__InterfaceMethod)NULL,121,-1,-1,0,6,1,4,0,
"h - 'UInt_t' 0 - x1 h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - y2 "
"h - 'UInt_t' 0 - col h - 'UInt_t' 0 - thick",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawWideLine",1183,(G__InterfaceMethod)NULL,121,-1,-1,0,6,1,4,0,
"h - 'UInt_t' 0 - x1 h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - y2 "
"h - 'UInt_t' 0 - col h - 'UInt_t' 0 - thick",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawDashHLine",1246,(G__InterfaceMethod)NULL,121,-1,-1,0,7,1,4,0,
"h - 'UInt_t' 0 - y h - 'UInt_t' 0 - x1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - nDash "
"C - - 10 - pDash h - 'UInt_t' 0 - col "
"h - 'UInt_t' 0 - thick",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawDashVLine",1260,(G__InterfaceMethod)NULL,121,-1,-1,0,7,1,4,0,
"h - 'UInt_t' 0 - x h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - y2 h - 'UInt_t' 0 - nDash "
"C - - 10 - pDash h - 'UInt_t' 0 - col "
"h - 'UInt_t' 0 - thick",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawDashZLine",1264,(G__InterfaceMethod)NULL,121,-1,-1,0,7,1,4,0,
"h - 'UInt_t' 0 - x1 h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - y2 "
"h - 'UInt_t' 0 - nDash C - - 10 - pDash "
"h - 'UInt_t' 0 - col",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetPolygonSpans",1549,(G__InterfaceMethod)NULL,103,-1,G__defined_typename("Bool_t"),0,5,1,4,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"H - 'UInt_t' 0 - nspans U 'TPoint' - 2 - firstPoint "
"H - 'UInt_t' 2 - firstWidth",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetFillAreaSpans",1573,(G__InterfaceMethod)NULL,121,-1,-1,0,5,1,4,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"H - 'UInt_t' 0 - nspans U 'TPoint' - 2 - firstPoint "
"H - 'UInt_t' 2 - firstWidth",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("FillRectangleInternal",2137,(G__InterfaceMethod)NULL,121,-1,-1,0,5,1,4,0,
"h - 'UInt_t' 0 - col i - 'Int_t' 0 - x "
"i - 'Int_t' 0 - y h - 'UInt_t' 0 - width "
"h - 'UInt_t' 0 - height",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawTextTTF",1057,(G__InterfaceMethod)NULL,121,-1,-1,0,7,1,4,0,
"i - 'Int_t' 0 - x i - 'Int_t' 0 - y "
"C - - 10 - text i - 'Int_t' 0 - size "
"h - 'UInt_t' 0 - color C - - 10 - font_name "
"f - 'Float_t' 0 - angle",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawGlyph",914,(G__InterfaceMethod)NULL,121,-1,-1,0,4,1,4,0,
"Y - - 0 - bitmap h - 'UInt_t' 0 - color "
"i - 'Int_t' 0 - x i - 'Int_t' 0 - y",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetFileType",1090,(G__InterfaceMethod)NULL,105,G__get_linked_tagnum(&G__G__ASImageLN_TImagecLcLEImageFileTypes),-1,0,1,1,2,0,"C - - 10 - ext",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MapFileTypes",1203,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,2,0,
"i 'TImage::EImageFileTypes' - 1 - type h - 'UInt_t' 1 - astype "
"g - 'Bool_t' 0 kTRUE toas",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MapQuality",1031,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,2,0,
"i 'TAttImage::EImageQuality' - 1 - quality h - 'UInt_t' 1 - asquality "
"g - 'Bool_t' 0 kTRUE toas",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("InitVisual",1032,(G__InterfaceMethod)NULL,103,-1,G__defined_typename("Bool_t"),0,0,3,2,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_7_1,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_8_1,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,2,1,1,0,
"h - 'UInt_t' 0 - w h - 'UInt_t' 0 - h",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_9_1,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,2,1,1,0,
"C - - 10 - file i 'TImage::EImageFileTypes' - 0 kUnknown type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_0_2,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,5,1,1,0,
"C - - 10 - name D - 'Double_t' 10 - imageData "
"h - 'UInt_t' 0 - width h - 'UInt_t' 0 - height "
"U 'TImagePalette' - 0 0 palette",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_1_2,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,4,1,1,0,
"C - - 10 - name u 'TArrayD' - 11 - imageData "
"h - 'UInt_t' 0 - width U 'TImagePalette' - 0 0 palette",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_2_2,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,4,1,1,0,
"C - - 10 - name u 'TVectorD' - 11 - imageData "
"h - 'UInt_t' 0 - width U 'TImagePalette' - 0 0 palette",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TASImage",715,G__G__ASImage_161_3_2,105,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,0,1,1,1,0,"u 'TASImage' - 11 - img",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("operator=",937,G__G__ASImage_161_4_2,117,G__get_linked_tagnum(&G__G__ASImageLN_TASImage),-1,1,1,1,1,0,"u 'TASImage' - 11 - img",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Clone",497,G__G__ASImage_161_5_2,85,G__get_linked_tagnum(&G__G__ASImageLN_TObject),-1,0,1,1,1,8,"C - - 10 - newname",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetEditable",1094,G__G__ASImage_161_6_2,121,-1,-1,0,1,1,1,0,"g - 'Bool_t' 0 kTRUE on","*TOGGLE*",(void*)NULL,1);
   G__memfunc_setup("IsEditable",982,G__G__ASImage_161_7_2,103,-1,G__defined_typename("Bool_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("FromPad",681,G__G__ASImage_161_8_2,121,-1,-1,0,5,1,1,0,
"U 'TVirtualPad' - 0 - pad i - 'Int_t' 0 0 x "
"i - 'Int_t' 0 0 y h - 'UInt_t' 0 0 w "
"h - 'UInt_t' 0 0 h",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Draw",398,G__G__ASImage_161_9_2,121,-1,-1,0,1,1,1,0,"C - 'Option_t' 10 \"\" option",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Paint",508,G__G__ASImage_161_0_3,121,-1,-1,0,1,1,1,0,"C - 'Option_t' 10 \"\" option",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DistancetoPrimitive",1991,G__G__ASImage_161_1_3,105,-1,G__defined_typename("Int_t"),0,2,1,1,0,
"i - 'Int_t' 0 - px i - 'Int_t' 0 - py",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ExecuteEvent",1237,G__G__ASImage_161_2_3,121,-1,-1,0,3,1,1,0,
"i - 'Int_t' 0 - event i - 'Int_t' 0 - px "
"i - 'Int_t' 0 - py",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetObjectInfo",1283,G__G__ASImage_161_3_3,67,-1,-1,0,2,1,1,8,
"i - 'Int_t' 0 - px i - 'Int_t' 0 - py",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetPalette",1019,G__G__ASImage_161_4_3,121,-1,-1,0,1,1,1,0,"U 'TImagePalette' - 10 - palette",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Zoom",421,G__G__ASImage_161_5_3,121,-1,-1,0,4,1,1,0,
"h - 'UInt_t' 0 - offX h - 'UInt_t' 0 - offY "
"h - 'UInt_t' 0 - width h - 'UInt_t' 0 - height","*MENU*",(void*)NULL,1);
   G__memfunc_setup("UnZoom",616,G__G__ASImage_161_6_3,121,-1,-1,0,0,1,1,0,"","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Flip",395,G__G__ASImage_161_7_3,121,-1,-1,0,1,1,1,0,"i - 'Int_t' 0 180 flip","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Mirror",635,G__G__ASImage_161_8_3,121,-1,-1,0,1,1,1,0,"g - 'Bool_t' 0 kTRUE vert","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Scale",488,G__G__ASImage_161_9_3,121,-1,-1,0,2,1,1,0,
"h - 'UInt_t' 0 - width h - 'UInt_t' 0 - height","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Tile",398,G__G__ASImage_161_0_4,121,-1,-1,0,2,1,1,0,
"h - 'UInt_t' 0 - width h - 'UInt_t' 0 - height","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Crop",404,G__G__ASImage_161_1_4,121,-1,-1,0,4,1,1,0,
"i - 'Int_t' 0 0 x i - 'Int_t' 0 0 y "
"h - 'UInt_t' 0 0 width h - 'UInt_t' 0 0 height","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Pad",277,G__G__ASImage_161_2_4,121,-1,-1,0,5,1,1,0,
"C - - 10 \"#00FFFFFF\" color h - 'UInt_t' 0 0 left "
"h - 'UInt_t' 0 0 right h - 'UInt_t' 0 0 top "
"h - 'UInt_t' 0 0 bottom","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Blur",405,G__G__ASImage_161_3_4,121,-1,-1,0,2,1,1,0,
"d - 'Double_t' 0 3 hr d - 'Double_t' 0 3 vr","*MENU*",(void*)NULL,1);
   G__memfunc_setup("Vectorize",955,G__G__ASImage_161_4_4,121,-1,-1,0,3,1,1,0,
"h - 'UInt_t' 0 256 max_colors h - 'UInt_t' 0 4 dither "
"i - 'Int_t' 0 1 opaque_threshold","*MENU*",(void*)NULL,1);
   G__memfunc_setup("StartPaletteEditor",1860,G__G__ASImage_161_5_4,121,-1,-1,0,0,1,1,0,"","*MENU*",(void*)NULL,1);
   G__memfunc_setup("HSV",241,G__G__ASImage_161_6_4,121,-1,-1,0,9,1,1,0,
"h - 'UInt_t' 0 0 hue h - 'UInt_t' 0 360 radius "
"i - 'Int_t' 0 0 H i - 'Int_t' 0 0 S "
"i - 'Int_t' 0 0 V i - 'Int_t' 0 0 x "
"i - 'Int_t' 0 0 y h - 'UInt_t' 0 0 width "
"h - 'UInt_t' 0 0 height",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Merge",496,G__G__ASImage_161_7_4,121,-1,-1,0,4,1,1,0,
"U 'TImage' - 10 - im C - - 10 \"alphablend\" op "
"i - 'Int_t' 0 0 x i - 'Int_t' 0 0 y",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Append",600,G__G__ASImage_161_8_4,121,-1,-1,0,3,1,1,0,
"U 'TImage' - 10 - im C - - 10 \"+\" option "
"C - - 10 \"#00000000\" color",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Gradient",814,G__G__ASImage_161_9_4,121,-1,-1,0,7,1,1,0,
"h - 'UInt_t' 0 0 angle C - - 10 \"#FFFFFF #000000\" colors "
"C - - 10 0 offsets i - 'Int_t' 0 0 x "
"i - 'Int_t' 0 0 y h - 'UInt_t' 0 0 width "
"h - 'UInt_t' 0 0 height",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Bevel",494,G__G__ASImage_161_0_5,121,-1,-1,0,8,1,1,0,
"i - 'Int_t' 0 0 x i - 'Int_t' 0 0 y "
"h - 'UInt_t' 0 0 width h - 'UInt_t' 0 0 height "
"C - - 10 \"#ffdddddd\" hi C - - 10 \"#ff555555\" lo "
"r - 'UShort_t' 0 1 thick g - 'Bool_t' 0 kFALSE pressed",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawText",819,G__G__ASImage_161_1_5,121,-1,-1,0,9,1,1,0,
"i - 'Int_t' 0 0 x i - 'Int_t' 0 0 y "
"C - - 10 \"\" text i - 'Int_t' 0 12 size "
"C - - 10 0 color C - - 10 \"fixed\" font "
"i 'TImage::EText3DType' - 0 TImage::kPlain type C - - 10 0 fore_file "
"f - 'Float_t' 0 0 angle",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("BeginPaint",993,G__G__ASImage_161_2_5,121,-1,-1,0,1,1,1,0,"g - 'Bool_t' 0 kTRUE fast",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("EndPaint",787,G__G__ASImage_161_3_5,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawLine",790,G__G__ASImage_161_4_5,121,-1,-1,0,6,1,1,0,
"h - 'UInt_t' 0 - x1 h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - y2 "
"C - - 10 \"#000000\" col h - 'UInt_t' 0 1 thick",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawDashLine",1174,G__G__ASImage_161_5_5,121,-1,-1,0,8,1,1,0,
"h - 'UInt_t' 0 - x1 h - 'UInt_t' 0 - y1 "
"h - 'UInt_t' 0 - x2 h - 'UInt_t' 0 - y2 "
"h - 'UInt_t' 0 - nDash C - - 10 - pDash "
"C - - 10 \"#000000\" col h - 'UInt_t' 0 1 thick",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawBox",695,G__G__ASImage_161_6_5,121,-1,-1,0,7,1,1,0,
"i - 'Int_t' 0 - x1 i - 'Int_t' 0 - y1 "
"i - 'Int_t' 0 - x2 i - 'Int_t' 0 - y2 "
"C - - 10 \"#000000\" col h - 'UInt_t' 0 1 thick "
"i - 'Int_t' 0 0 mode",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawRectangle",1315,G__G__ASImage_161_7_5,121,-1,-1,0,6,1,1,0,
"h - 'UInt_t' 0 - x h - 'UInt_t' 0 - y "
"h - 'UInt_t' 0 - w h - 'UInt_t' 0 - h "
"C - - 10 \"#000000\" col h - 'UInt_t' 0 1 thick",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("FillRectangle",1308,G__G__ASImage_161_8_5,121,-1,-1,0,5,1,1,0,
"C - - 10 0 col i - 'Int_t' 0 0 x "
"i - 'Int_t' 0 0 y h - 'UInt_t' 0 0 width "
"h - 'UInt_t' 0 0 height",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawPolyLine",1210,G__G__ASImage_161_9_5,121,-1,-1,0,5,1,1,0,
"h - 'UInt_t' 0 - nn U 'TPoint' - 0 - xy "
"C - - 10 \"#000000\" col h - 'UInt_t' 0 1 thick "
"i 'TImage::ECoordMode' - 0 kCoordModeOrigin mode",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("PutPixel",827,G__G__ASImage_161_0_6,121,-1,-1,0,3,1,1,0,
"i - 'Int_t' 0 - x i - 'Int_t' 0 - y "
"C - - 10 \"#000000\" col",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("PolyPoint",942,G__G__ASImage_161_1_6,121,-1,-1,0,4,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"C - - 10 \"#000000\" col i 'TImage::ECoordMode' - 0 kCoordModeOrigin mode",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawSegments",1236,G__G__ASImage_161_2_6,121,-1,-1,0,4,1,1,0,
"h - 'UInt_t' 0 - nseg U 'Segment_t' - 0 - seg "
"C - - 10 \"#000000\" col h - 'UInt_t' 0 1 thick",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("FillPolygon",1135,G__G__ASImage_161_3_6,121,-1,-1,0,6,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"C - - 10 \"#000000\" col C - - 10 0 stipple "
"h - 'UInt_t' 0 16 w h - 'UInt_t' 0 16 h",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("FillPolygon",1135,G__G__ASImage_161_4_6,121,-1,-1,0,3,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"U 'TImage' - 0 - tile",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("CropPolygon",1148,G__G__ASImage_161_5_6,121,-1,-1,0,2,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawFillArea",1166,G__G__ASImage_161_6_6,121,-1,-1,0,6,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"C - - 10 \"#000000\" col C - - 10 0 stipple "
"h - 'UInt_t' 0 16 w h - 'UInt_t' 0 16 h",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawFillArea",1166,G__G__ASImage_161_7_6,121,-1,-1,0,3,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"U 'TImage' - 0 - tile",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("FillSpans",908,G__G__ASImage_161_8_6,121,-1,-1,0,7,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"H - 'UInt_t' 0 - widths C - - 10 \"#000000\" col "
"C - - 10 0 stipple h - 'UInt_t' 0 16 w "
"h - 'UInt_t' 0 16 h",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("FillSpans",908,G__G__ASImage_161_9_6,121,-1,-1,0,4,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"H - 'UInt_t' 0 - widths U 'TImage' - 0 - tile",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("CropSpans",921,G__G__ASImage_161_0_7,121,-1,-1,0,3,1,1,0,
"h - 'UInt_t' 0 - npt U 'TPoint' - 0 - ppt "
"H - 'UInt_t' 0 - widths",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("CopyArea",788,G__G__ASImage_161_1_7,121,-1,-1,0,9,1,1,0,
"U 'TImage' - 0 - dst i - 'Int_t' 0 - xsrc "
"i - 'Int_t' 0 - ysrc h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h i - 'Int_t' 0 0 xdst "
"i - 'Int_t' 0 0 ydst i - 'Int_t' 0 3 gfunc "
"i 'TImage::EColorChan' - 0 kAllChan chan",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("DrawCellArray",1293,G__G__ASImage_161_2_7,121,-1,-1,0,7,1,1,0,
"i - 'Int_t' 0 - x1 i - 'Int_t' 0 - y1 "
"i - 'Int_t' 0 - x2 i - 'Int_t' 0 - y2 "
"i - 'Int_t' 0 - nx i - 'Int_t' 0 - ny "
"H - 'UInt_t' 0 - ic",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ReadImage",863,G__G__ASImage_161_3_7,121,-1,-1,0,2,1,1,0,
"C - - 10 - file i 'TImage::EImageFileTypes' - 0 TImage::kUnknown type",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("WriteImage",1006,G__G__ASImage_161_4_7,121,-1,-1,0,2,1,1,0,
"C - - 10 - file i 'TImage::EImageFileTypes' - 0 TImage::kUnknown type","*MENU*",(void*)NULL,1);
   G__memfunc_setup("SetImage",783,G__G__ASImage_161_5_7,121,-1,-1,0,4,1,1,0,
"D - 'Double_t' 10 - imageData h - 'UInt_t' 0 - width "
"h - 'UInt_t' 0 - height U 'TImagePalette' - 0 0 palette",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetImage",783,G__G__ASImage_161_6_7,121,-1,-1,0,3,1,1,0,
"u 'TArrayD' - 11 - imageData h - 'UInt_t' 0 - width "
"U 'TImagePalette' - 0 0 palette",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetImage",783,G__G__ASImage_161_7_7,121,-1,-1,0,3,1,1,0,
"u 'TVectorD' - 11 - imageData h - 'UInt_t' 0 - width "
"U 'TImagePalette' - 0 0 palette",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("SetImage",783,G__G__ASImage_161_8_7,121,-1,-1,0,2,1,1,0,
"k - 'Pixmap_t' 0 - pxm k - 'Pixmap_t' 0 0 mask",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetWidth",800,G__G__ASImage_161_9_7,104,-1,G__defined_typename("UInt_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetHeight",889,G__G__ASImage_161_0_8,104,-1,G__defined_typename("UInt_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetScaledWidth",1388,G__G__ASImage_161_1_8,104,-1,G__defined_typename("UInt_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetScaledHeight",1477,G__G__ASImage_161_2_8,104,-1,G__defined_typename("UInt_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsValid",684,G__G__ASImage_161_3_8,103,-1,G__defined_typename("Bool_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetImage",771,G__G__ASImage_161_4_8,85,G__get_linked_tagnum(&G__G__ASImageLN_ASImage),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetScaledImage",1359,G__G__ASImage_161_5_8,85,G__get_linked_tagnum(&G__G__ASImageLN_TImage),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetPixmap",911,G__G__ASImage_161_6_8,107,-1,G__defined_typename("Pixmap_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetMask",684,G__G__ASImage_161_7_8,107,-1,G__defined_typename("Pixmap_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetPixels",917,G__G__ASImage_161_8_8,85,G__get_linked_tagnum(&G__G__ASImageLN_TArrayL),-1,0,4,1,1,0,
"i - 'Int_t' 0 0 x i - 'Int_t' 0 0 y "
"h - 'UInt_t' 0 0 w h - 'UInt_t' 0 0 h",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetArray",799,G__G__ASImage_161_9_8,85,G__get_linked_tagnum(&G__G__ASImageLN_TArrayD),-1,0,3,1,1,0,
"h - 'UInt_t' 0 0 w h - 'UInt_t' 0 0 h "
"U 'TImagePalette' - 0 gWebImagePalette pal",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetArgbArray",1179,G__G__ASImage_161_0_9,72,-1,G__defined_typename("UInt_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetScanline",1101,G__G__ASImage_161_1_9,72,-1,G__defined_typename("UInt_t"),0,1,1,1,0,"h - 'UInt_t' 0 - y",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetVisual",916,G__G__ASImage_161_2_9,85,G__get_linked_tagnum(&G__G__ASImageLN_ASVisual),-1,0,0,3,1,1,"",(char*)NULL,(void*)(const ASVisual* (*)())(&TASImage::GetVisual),0);
   G__memfunc_setup("AlphaBlend",971,G__G__ASImage_161_3_9,104,-1,G__defined_typename("UInt_t"),0,2,3,1,0,
"h - 'UInt_t' 0 - bot h - 'UInt_t' 0 - top",(char*)NULL,(void*)(UInt_t (*)(UInt_t,UInt_t))(&TASImage::AlphaBlend),0);
   G__memfunc_setup("Class",502,G__G__ASImage_161_4_9,85,G__get_linked_tagnum(&G__G__ASImageLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&TASImage::Class),0);
   G__memfunc_setup("Class_Name",982,G__G__ASImage_161_5_9,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TASImage::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__G__ASImage_161_6_9,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&TASImage::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__G__ASImage_161_7_9,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&TASImage::Dictionary),0);
   G__memfunc_setup("IsA",253,G__G__ASImage_161_8_9,85,G__get_linked_tagnum(&G__G__ASImageLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__G__ASImage_161_9_9,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__G__ASImage_161_0_10,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__ASImage_161_1_10,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__G__ASImage_161_2_10,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TASImage::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__G__ASImage_161_3_10,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TASImage::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__G__ASImage_161_4_10,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TASImage::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__G__ASImage_161_5_10,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TASImage::DeclFileLine),0);
   // automatic destructor
   G__memfunc_setup("~TASImage",841,G__G__ASImage_161_6_10,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__ASImage() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__ASImage() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__ASImage() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__ASImageLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TVirtualPad = { "TVirtualPad" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TAttImage = { "TAttImage" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TImagePalette = { "TImagePalette" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TAttImagecLcLEImageQuality = { "TAttImage::EImageQuality" , 101 , -1 };
G__linked_taginfo G__G__ASImageLN_Segment_t = { "Segment_t" , 115 , -1 };
G__linked_taginfo G__G__ASImageLN_TArrayD = { "TArrayD" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TVectorD = { "TVectorD" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TArrayL = { "TArrayL" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TPoint = { "TPoint" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TImage = { "TImage" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TImagecLcLEImageFileTypes = { "TImage::EImageFileTypes" , 101 , -1 };
G__linked_taginfo G__G__ASImageLN_TImagecLcLEText3DType = { "TImage::EText3DType" , 101 , -1 };
G__linked_taginfo G__G__ASImageLN_TImagecLcLECoordMode = { "TImage::ECoordMode" , 101 , -1 };
G__linked_taginfo G__G__ASImageLN_TImagecLcLEColorChan = { "TImage::EColorChan" , 101 , -1 };
G__linked_taginfo G__G__ASImageLN_ASImage = { "ASImage" , 115 , -1 };
G__linked_taginfo G__G__ASImageLN_ASVisual = { "ASVisual" , 115 , -1 };
G__linked_taginfo G__G__ASImageLN_TASImage = { "TASImage" , 99 , -1 };
G__linked_taginfo G__G__ASImageLN_TASImagecLcLdA = { "TASImage::$" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__ASImage() {
  G__G__ASImageLN_TClass.tagnum = -1 ;
  G__G__ASImageLN_TBuffer.tagnum = -1 ;
  G__G__ASImageLN_TMemberInspector.tagnum = -1 ;
  G__G__ASImageLN_TObject.tagnum = -1 ;
  G__G__ASImageLN_TNamed.tagnum = -1 ;
  G__G__ASImageLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__G__ASImageLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__ASImageLN_TVirtualPad.tagnum = -1 ;
  G__G__ASImageLN_TAttImage.tagnum = -1 ;
  G__G__ASImageLN_TImagePalette.tagnum = -1 ;
  G__G__ASImageLN_TAttImagecLcLEImageQuality.tagnum = -1 ;
  G__G__ASImageLN_Segment_t.tagnum = -1 ;
  G__G__ASImageLN_TArrayD.tagnum = -1 ;
  G__G__ASImageLN_TVectorD.tagnum = -1 ;
  G__G__ASImageLN_TArrayL.tagnum = -1 ;
  G__G__ASImageLN_TPoint.tagnum = -1 ;
  G__G__ASImageLN_TImage.tagnum = -1 ;
  G__G__ASImageLN_TImagecLcLEImageFileTypes.tagnum = -1 ;
  G__G__ASImageLN_TImagecLcLEText3DType.tagnum = -1 ;
  G__G__ASImageLN_TImagecLcLECoordMode.tagnum = -1 ;
  G__G__ASImageLN_TImagecLcLEColorChan.tagnum = -1 ;
  G__G__ASImageLN_ASImage.tagnum = -1 ;
  G__G__ASImageLN_ASVisual.tagnum = -1 ;
  G__G__ASImageLN_TASImage.tagnum = -1 ;
  G__G__ASImageLN_TASImagecLcLdA.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__ASImage() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__G__ASImageLN_TClass);
   G__get_linked_tagnum(&G__G__ASImageLN_TBuffer);
   G__get_linked_tagnum(&G__G__ASImageLN_TMemberInspector);
   G__get_linked_tagnum(&G__G__ASImageLN_TObject);
   G__get_linked_tagnum(&G__G__ASImageLN_TNamed);
   G__get_linked_tagnum(&G__G__ASImageLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__G__ASImageLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__G__ASImageLN_TVirtualPad);
   G__get_linked_tagnum(&G__G__ASImageLN_TAttImage);
   G__get_linked_tagnum(&G__G__ASImageLN_TImagePalette);
   G__get_linked_tagnum(&G__G__ASImageLN_TAttImagecLcLEImageQuality);
   G__get_linked_tagnum(&G__G__ASImageLN_Segment_t);
   G__get_linked_tagnum(&G__G__ASImageLN_TArrayD);
   G__get_linked_tagnum(&G__G__ASImageLN_TVectorD);
   G__get_linked_tagnum(&G__G__ASImageLN_TArrayL);
   G__get_linked_tagnum(&G__G__ASImageLN_TPoint);
   G__get_linked_tagnum(&G__G__ASImageLN_TImage);
   G__get_linked_tagnum(&G__G__ASImageLN_TImagecLcLEImageFileTypes);
   G__get_linked_tagnum(&G__G__ASImageLN_TImagecLcLEText3DType);
   G__get_linked_tagnum(&G__G__ASImageLN_TImagecLcLECoordMode);
   G__get_linked_tagnum(&G__G__ASImageLN_TImagecLcLEColorChan);
   G__get_linked_tagnum(&G__G__ASImageLN_ASImage);
   G__get_linked_tagnum(&G__G__ASImageLN_ASVisual);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__ASImageLN_TASImage),sizeof(TASImage),-1,65280,"Image display class",G__setup_memvarTASImage,G__setup_memfuncTASImage);
   G__get_linked_tagnum(&G__G__ASImageLN_TASImagecLcLdA);
}
extern "C" void G__cpp_setupG__ASImage(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__ASImage()");
  G__set_cpp_environmentG__ASImage();
  G__cpp_setup_tagtableG__ASImage();

  G__cpp_setup_inheritanceG__ASImage();

  G__cpp_setup_typetableG__ASImage();

  G__cpp_setup_memvarG__ASImage();

  G__cpp_setup_memfuncG__ASImage();
  G__cpp_setup_globalG__ASImage();
  G__cpp_setup_funcG__ASImage();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__ASImage();
  return;
}
class G__cpp_setup_initG__ASImage {
  public:
    G__cpp_setup_initG__ASImage() { G__add_setup_func("G__ASImage",(G__incsetup)(&G__cpp_setupG__ASImage)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__ASImage() { G__remove_setup_func("G__ASImage"); }
};
G__cpp_setup_initG__ASImage G__cpp_setup_initializerG__ASImage;

