/********************************************************************
* meta/src/G__Meta.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error meta/src/G__Meta.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Meta();
extern void G__cpp_setup_inheritanceG__Meta();
extern void G__cpp_setup_typetableG__Meta();
extern void G__cpp_setup_memvarG__Meta();
extern void G__cpp_setup_globalG__Meta();
extern void G__cpp_setup_memfuncG__Meta();
extern void G__cpp_setup_funcG__Meta();
extern void G__set_cpp_environmentG__Meta();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "meta/inc/TGlobal.h"
#include "meta/inc/TGenericClassInfo.h"
#include "meta/inc/TClassMenuItem.h"
#include "meta/inc/TMethodCall.h"
#include "meta/inc/TCint.h"
#include "meta/inc/TClassGenerator.h"
#include "meta/inc/TMemberStreamer.h"
#include "meta/inc/TClassStreamer.h"
#include "meta/inc/TDataMember.h"
#include "meta/inc/TClassRef.h"
#include "meta/inc/TFunction.h"
#include "meta/inc/TStreamer.h"
#include "meta/inc/TBaseClass.h"
#include "meta/inc/TStreamerInfo.h"
#include "meta/inc/TMethod.h"
#include "meta/inc/TInterpreter.h"
#include "meta/inc/TDataType.h"
#include "meta/inc/TToggle.h"
#include "meta/inc/TToggleGroup.h"
#include "meta/inc/TMethodArg.h"
#include "meta/inc/TStreamerElement.h"
#include "meta/inc/TDictionary.h"
#include "meta/inc/TClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MetaLN_type_info;
extern G__linked_taginfo G__G__MetaLN_TClass;
extern G__linked_taginfo G__G__MetaLN_TBuffer;
extern G__linked_taginfo G__G__MetaLN_TMemberInspector;
extern G__linked_taginfo G__G__MetaLN_TObject;
extern G__linked_taginfo G__G__MetaLN_TNamed;
extern G__linked_taginfo G__G__MetaLN_TClassStreamer;
extern G__linked_taginfo G__G__MetaLN_TMemberStreamer;
extern G__linked_taginfo G__G__MetaLN_TVirtualCollectionProxy;
extern G__linked_taginfo G__G__MetaLN_ROOT;
extern G__linked_taginfo G__G__MetaLN_ROOTcLcLTInitBehavior;
extern G__linked_taginfo G__G__MetaLN_TList;
extern G__linked_taginfo G__G__MetaLN_TBrowser;
extern G__linked_taginfo G__G__MetaLN_TObjArray;
extern G__linked_taginfo G__G__MetaLN_TMethod;
extern G__linked_taginfo G__G__MetaLN_TStreamerInfo;
extern G__linked_taginfo G__G__MetaLN_TStreamerElement;
extern G__linked_taginfo G__G__MetaLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__MetaLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MetaLN_TString;
extern G__linked_taginfo G__G__MetaLN_TFile;
extern G__linked_taginfo G__G__MetaLN_TDataType;
extern G__linked_taginfo G__G__MetaLN_TInterpreter;
extern G__linked_taginfo G__G__MetaLN_TGlobal;
extern G__linked_taginfo G__G__MetaLN_TFunction;
extern G__linked_taginfo G__G__MetaLN_TClassGenerator;
extern G__linked_taginfo G__G__MetaLN_TROOT;
extern G__linked_taginfo G__G__MetaLN_TCint;
extern G__linked_taginfo G__G__MetaLN_EProperty;
extern G__linked_taginfo G__G__MetaLN_TDictionary;
extern G__linked_taginfo G__G__MetaLN_TDictionarycLcLESTLType;
extern G__linked_taginfo G__G__MetaLN_G__DataMemberInfo;
extern G__linked_taginfo G__G__MetaLN_TClassMenuItem;
extern G__linked_taginfo G__G__MetaLN_TClassMenuItemcLcLEClassMenuItemType;
extern G__linked_taginfo G__G__MetaLN_TClassMenuItemcLcLdA;
extern G__linked_taginfo G__G__MetaLN_G__CallFunc;
extern G__linked_taginfo G__G__MetaLN_TMethodCall;
extern G__linked_taginfo G__G__MetaLN_TMethodCallcLcLEReturnType;
extern G__linked_taginfo G__G__MetaLN_TInterpretercLcLEErrorCode;
extern G__linked_taginfo G__G__MetaLN_G__dictposition;
extern G__linked_taginfo G__G__MetaLN_G__ClassInfo;
extern G__linked_taginfo G__G__MetaLN_TEnv;
extern G__linked_taginfo G__G__MetaLN_TDataMember;
extern G__linked_taginfo G__G__MetaLN_TDataMembercLcLdA;
extern G__linked_taginfo G__G__MetaLN_TClonesArray;
extern G__linked_taginfo G__G__MetaLN_TStreamerBasicType;
extern G__linked_taginfo G__G__MetaLN_TStreamerInfocLcLCompInfo;
extern G__linked_taginfo G__G__MetaLN_TStreamerInfocLcLdA;
extern G__linked_taginfo G__G__MetaLN_TStreamerInfocLcLEReadWrite;
extern G__linked_taginfo G__G__MetaLN_TBaseClass;
extern G__linked_taginfo G__G__MetaLN_TClassRef;
extern G__linked_taginfo G__G__MetaLN_TRealData;
extern G__linked_taginfo G__G__MetaLN_TClasscLcLdA;
extern G__linked_taginfo G__G__MetaLN_TClasscLcLENewType;
extern G__linked_taginfo G__G__MetaLN_G__MethodInfo;
extern G__linked_taginfo G__G__MetaLN_G__BaseClassInfo;
extern G__linked_taginfo G__G__MetaLN_EMenuItemKind;
extern G__linked_taginfo G__G__MetaLN_EDataType;
extern G__linked_taginfo G__G__MetaLN_G__TypedefInfo;
extern G__linked_taginfo G__G__MetaLN_TToggle;
extern G__linked_taginfo G__G__MetaLN_TOrdCollection;
extern G__linked_taginfo G__G__MetaLN_TToggleGroup;
extern G__linked_taginfo G__G__MetaLN_G__MethodArgInfo;
extern G__linked_taginfo G__G__MetaLN_TMethodArg;
extern G__linked_taginfo G__G__MetaLN_TStreamerElementcLcLESTLtype;
extern G__linked_taginfo G__G__MetaLN_TStreamerElementcLcLdA;
extern G__linked_taginfo G__G__MetaLN_TStreamerBase;
extern G__linked_taginfo G__G__MetaLN_TStreamerBasicPointer;
extern G__linked_taginfo G__G__MetaLN_TStreamerLoop;
extern G__linked_taginfo G__G__MetaLN_TStreamerObject;
extern G__linked_taginfo G__G__MetaLN_TStreamerObjectAny;
extern G__linked_taginfo G__G__MetaLN_TStreamerObjectPointer;
extern G__linked_taginfo G__G__MetaLN_TStreamerObjectAnyPointer;
extern G__linked_taginfo G__G__MetaLN_TStreamerString;
extern G__linked_taginfo G__G__MetaLN_TStreamerSTL;
extern G__linked_taginfo G__G__MetaLN_TStreamerSTLstring;

/* STUB derived class for protected member access */
