/********************************************************************
* ged/src/G__Ged.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ged/src/G__Ged.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Ged();
extern void G__cpp_setup_inheritanceG__Ged();
extern void G__cpp_setup_typetableG__Ged();
extern void G__cpp_setup_memvarG__Ged();
extern void G__cpp_setup_globalG__Ged();
extern void G__cpp_setup_memfuncG__Ged();
extern void G__cpp_setup_funcG__Ged();
extern void G__set_cpp_environmentG__Ged();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "ged/inc/TAttFillEditor.h"
#include "ged/inc/TGedFrame.h"
#include "ged/inc/TGedMarkerSelect.h"
#include "ged/inc/TGraphEditor.h"
#include "ged/inc/TH2Editor.h"
#include "ged/inc/TAttLineEditor.h"
#include "ged/inc/TAxisEditor.h"
#include "ged/inc/TAttMarkerEditor.h"
#include "ged/inc/TPaveStatsEditor.h"
#include "ged/inc/TFrameEditor.h"
#include "ged/inc/TCurlyArcEditor.h"
#include "ged/inc/TAttTextEditor.h"
#include "ged/inc/TCurlyLineEditor.h"
#include "ged/inc/TGedEditor.h"
#include "ged/inc/TH1Editor.h"
#include "ged/inc/TGedPatternSelect.h"
#include "ged/inc/TArrowEditor.h"
#include "ged/inc/TGedToolBox.h"
#include "ged/inc/TPadEditor.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GedLN_TClass;
extern G__linked_taginfo G__G__GedLN_TBuffer;
extern G__linked_taginfo G__G__GedLN_TMemberInspector;
extern G__linked_taginfo G__G__GedLN_TObject;
extern G__linked_taginfo G__G__GedLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__GedLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__GedLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GedLN_TString;
extern G__linked_taginfo G__G__GedLN_TVirtualPad;
extern G__linked_taginfo G__G__GedLN_Event_t;
extern G__linked_taginfo G__G__GedLN_TGWindow;
extern G__linked_taginfo G__G__GedLN_TGWidget;
extern G__linked_taginfo G__G__GedLN_TGObject;
extern G__linked_taginfo G__G__GedLN_TGPicture;
extern G__linked_taginfo G__G__GedLN_TGGC;
extern G__linked_taginfo G__G__GedLN_TAttLine;
extern G__linked_taginfo G__G__GedLN_TAttFill;
extern G__linked_taginfo G__G__GedLN_TAttText;
extern G__linked_taginfo G__G__GedLN_TAttMarker;
extern G__linked_taginfo G__G__GedLN_TQObject;
extern G__linked_taginfo G__G__GedLN_TGDimension;
extern G__linked_taginfo G__G__GedLN_TGFrame;
extern G__linked_taginfo G__G__GedLN_TGCompositeFrame;
extern G__linked_taginfo G__G__GedLN_TGMainFrame;
extern G__linked_taginfo G__G__GedLN_TCanvas;
extern G__linked_taginfo G__G__GedLN_TGLabel;
extern G__linked_taginfo G__G__GedLN_TGTab;
extern G__linked_taginfo G__G__GedLN_TGedFrame;
extern G__linked_taginfo G__G__GedLN_TGedElement;
extern G__linked_taginfo G__G__GedLN_TGedNameFrame;
extern G__linked_taginfo G__G__GedLN_TGColorSelect;
extern G__linked_taginfo G__G__GedLN_TGedPatternSelect;
extern G__linked_taginfo G__G__GedLN_TAttFillEditor;
extern G__linked_taginfo G__G__GedLN_TGToolTip;
extern G__linked_taginfo G__G__GedLN_TGButtonGroup;
extern G__linked_taginfo G__G__GedLN_TGButton;
extern G__linked_taginfo G__G__GedLN_TGTextButton;
extern G__linked_taginfo G__G__GedLN_TGCheckButton;
extern G__linked_taginfo G__G__GedLN_TGRadioButton;
extern G__linked_taginfo G__G__GedLN_TGedPopup;
extern G__linked_taginfo G__G__GedLN_TGedPatternFrame;
extern G__linked_taginfo G__G__GedLN_TGedPatternSelector;
extern G__linked_taginfo G__G__GedLN_TGedPatternPopup;
extern G__linked_taginfo G__G__GedLN_TGedSelect;
extern G__linked_taginfo G__G__GedLN_TGedMarkerPopup;
extern G__linked_taginfo G__G__GedLN_TGedMarkerSelect;
extern G__linked_taginfo G__G__GedLN_TH1;
extern G__linked_taginfo G__G__GedLN_TAxis;
extern G__linked_taginfo G__G__GedLN_TGraph;
extern G__linked_taginfo G__G__GedLN_TGTextEntry;
extern G__linked_taginfo G__G__GedLN_TGraphEditor;
extern G__linked_taginfo G__G__GedLN_TH2;
extern G__linked_taginfo G__G__GedLN_TGComboBox;
extern G__linked_taginfo G__G__GedLN_TGDoubleHSlider;
extern G__linked_taginfo G__G__GedLN_TGHSlider;
extern G__linked_taginfo G__G__GedLN_TGNumberEntry;
extern G__linked_taginfo G__G__GedLN_TGHButtonGroup;
extern G__linked_taginfo G__G__GedLN_TGNumberEntryField;
extern G__linked_taginfo G__G__GedLN_TH2Editor;
extern G__linked_taginfo G__G__GedLN_TGLineStyleComboBox;
extern G__linked_taginfo G__G__GedLN_TGLineWidthComboBox;
extern G__linked_taginfo G__G__GedLN_TAttLineEditor;
extern G__linked_taginfo G__G__GedLN_TGFontTypeComboBox;
extern G__linked_taginfo G__G__GedLN_TAxisEditor;
extern G__linked_taginfo G__G__GedLN_TAttMarkerEditor;
extern G__linked_taginfo G__G__GedLN_TPaveStats;
extern G__linked_taginfo G__G__GedLN_TPaveStatsEditor;
extern G__linked_taginfo G__G__GedLN_TFrame;
extern G__linked_taginfo G__G__GedLN_TFrameEditor;
extern G__linked_taginfo G__G__GedLN_TCurlyArc;
extern G__linked_taginfo G__G__GedLN_TCurlyArcEditor;
extern G__linked_taginfo G__G__GedLN_TAttTextEditor;
extern G__linked_taginfo G__G__GedLN_TCurlyLine;
extern G__linked_taginfo G__G__GedLN_TCurlyLineEditor;
extern G__linked_taginfo G__G__GedLN_TVirtualPadEditor;
extern G__linked_taginfo G__G__GedLN_TGCanvas;
extern G__linked_taginfo G__G__GedLN_TGedEditor;
extern G__linked_taginfo G__G__GedLN_TPad;
extern G__linked_taginfo G__G__GedLN_TH1Editor;
extern G__linked_taginfo G__G__GedLN_TArrow;
extern G__linked_taginfo G__G__GedLN_TArrowEditor;
extern G__linked_taginfo G__G__GedLN_ToolBarData_t;
extern G__linked_taginfo G__G__GedLN_TGToolBar;
extern G__linked_taginfo G__G__GedLN_TGedToolBox;
extern G__linked_taginfo G__G__GedLN_TPadEditor;

/* STUB derived class for protected member access */
