/********************************************************************
* geompainter/src/G__GeomPainter.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error geompainter/src/G__GeomPainter.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__GeomPainter();
extern void G__cpp_setup_inheritanceG__GeomPainter();
extern void G__cpp_setup_typetableG__GeomPainter();
extern void G__cpp_setup_memvarG__GeomPainter();
extern void G__cpp_setup_globalG__GeomPainter();
extern void G__cpp_setup_memfuncG__GeomPainter();
extern void G__cpp_setup_funcG__GeomPainter();
extern void G__set_cpp_environmentG__GeomPainter();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "geompainter/inc/TGeoTrack.h"
#include "geompainter/inc/TGeoChecker.h"
#include "geompainter/inc/TGeoPainter.h"
#include "geompainter/inc/TGeoOverlap.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GeomPainterLN_TClass;
extern G__linked_taginfo G__G__GeomPainterLN_TBuffer;
extern G__linked_taginfo G__G__GeomPainterLN_TMemberInspector;
extern G__linked_taginfo G__G__GeomPainterLN_TObject;
extern G__linked_taginfo G__G__GeomPainterLN_TNamed;
extern G__linked_taginfo G__G__GeomPainterLN_TBrowser;
extern G__linked_taginfo G__G__GeomPainterLN_TObjArray;
extern G__linked_taginfo G__G__GeomPainterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__GeomPainterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoAtt;
extern G__linked_taginfo G__G__GeomPainterLN_TAttLine;
extern G__linked_taginfo G__G__GeomPainterLN_TAttMarker;
extern G__linked_taginfo G__G__GeomPainterLN_TVirtualGeoTrack;
extern G__linked_taginfo G__G__GeomPainterLN_TAtt3D;
extern G__linked_taginfo G__G__GeomPainterLN_TPolyMarker3D;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoTrack;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoTrackcLcLEGeoParticleActions;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoVolume;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoVoxelFinder;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoNode;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoManager;
extern G__linked_taginfo G__G__GeomPainterLN_TH2F;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoChecker;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoShape;
extern G__linked_taginfo G__G__GeomPainterLN_TVirtualGeoPainter;
extern G__linked_taginfo G__G__GeomPainterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__GeomPainterLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GeomPainterLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__GeomPainterLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GeomPainterLN_TAttFill;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoMatrix;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoPhysicalNode;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoOverlap;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoPainter;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoExtrusion;
extern G__linked_taginfo G__G__GeomPainterLN_TGeoNodeOverlap;

/* STUB derived class for protected member access */
