/********************************************************************
* qtroot/src/G__QtRoot.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error qtroot/src/G__QtRoot.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__QtRoot();
extern void G__cpp_setup_inheritanceG__QtRoot();
extern void G__cpp_setup_typetableG__QtRoot();
extern void G__cpp_setup_memvarG__QtRoot();
extern void G__cpp_setup_globalG__QtRoot();
extern void G__cpp_setup_memfuncG__QtRoot();
extern void G__cpp_setup_funcG__QtRoot();
extern void G__set_cpp_environmentG__QtRoot();
}


#include "base/inc/TROOT.h"
#include "base/inc/TMemberInspector.h"
#include "qtroot/inc/TQtRootGuiFactory.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__QtRootLN_TClass;
extern G__linked_taginfo G__G__QtRootLN_TBuffer;
extern G__linked_taginfo G__G__QtRootLN_TMemberInspector;
extern G__linked_taginfo G__G__QtRootLN_TObject;
extern G__linked_taginfo G__G__QtRootLN_TNamed;
extern G__linked_taginfo G__G__QtRootLN_TBrowser;
extern G__linked_taginfo G__G__QtRootLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__QtRootLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__QtRootLN_TApplicationImp;
extern G__linked_taginfo G__G__QtRootLN_TCanvasImp;
extern G__linked_taginfo G__G__QtRootLN_TCanvas;
extern G__linked_taginfo G__G__QtRootLN_TBrowserImp;
extern G__linked_taginfo G__G__QtRootLN_TContextMenuImp;
extern G__linked_taginfo G__G__QtRootLN_TContextMenu;
extern G__linked_taginfo G__G__QtRootLN_TControlBarImp;
extern G__linked_taginfo G__G__QtRootLN_TControlBar;
extern G__linked_taginfo G__G__QtRootLN_TInspectorImp;
extern G__linked_taginfo G__G__QtRootLN_TGuiFactory;
extern G__linked_taginfo G__G__QtRootLN_TGClient;
extern G__linked_taginfo G__G__QtRootLN_TQtRootGuiFactory;

/* STUB derived class for protected member access */
